//go:build go1.22

// Package indexes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package indexes

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/antflydb/antfly/lib/ai"
	externalRef1 "github.com/antflydb/antfly/lib/chunking"
	externalRef2 "github.com/antflydb/antfly/lib/embeddings"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AntflyType.
const (
	AntflyTypeBlob            AntflyType = "blob"
	AntflyTypeBoolean         AntflyType = "boolean"
	AntflyTypeDatetime        AntflyType = "datetime"
	AntflyTypeEmbedding       AntflyType = "embedding"
	AntflyTypeGeopoint        AntflyType = "geopoint"
	AntflyTypeGeoshape        AntflyType = "geoshape"
	AntflyTypeHtml            AntflyType = "html"
	AntflyTypeKeyword         AntflyType = "keyword"
	AntflyTypeLink            AntflyType = "link"
	AntflyTypeNumeric         AntflyType = "numeric"
	AntflyTypeSearchAsYouType AntflyType = "search_as_you_type"
	AntflyTypeText            AntflyType = "text"
)

// Defines values for DistanceMetric.
const (
	DistanceMetricCosine       DistanceMetric = "cosine"
	DistanceMetricInnerProduct DistanceMetric = "inner_product"
	DistanceMetricL2Squared    DistanceMetric = "l2_squared"
)

// Defines values for EdgeDirection.
const (
	EdgeDirectionBoth EdgeDirection = "both"
	EdgeDirectionIn   EdgeDirection = "in"
	EdgeDirectionOut  EdgeDirection = "out"
)

// Defines values for EdgeTypeConfigTopology.
const (
	EdgeTypeConfigTopologyGraph EdgeTypeConfigTopology = "graph"
	EdgeTypeConfigTopologyTree  EdgeTypeConfigTopology = "tree"
)

// Defines values for GraphQueryType.
const (
	GraphQueryTypeKShortestPaths GraphQueryType = "k_shortest_paths"
	GraphQueryTypeNeighbors      GraphQueryType = "neighbors"
	GraphQueryTypePattern        GraphQueryType = "pattern"
	GraphQueryTypeShortestPath   GraphQueryType = "shortest_path"
	GraphQueryTypeTraverse       GraphQueryType = "traverse"
)

// Defines values for IndexType.
const (
	IndexTypeEmbeddings IndexType = "embeddings"
	IndexTypeFullText   IndexType = "full_text"
	IndexTypeGraph      IndexType = "graph"
)

// Defines values for MergeStrategy.
const (
	MergeStrategyFailover MergeStrategy = "failover"
	MergeStrategyRrf      MergeStrategy = "rrf"
	MergeStrategyRsf      MergeStrategy = "rsf"
)

// Defines values for PathFindWeightMode.
const (
	PathFindWeightModeMaxWeight PathFindWeightMode = "max_weight"
	PathFindWeightModeMinHops   PathFindWeightMode = "min_hops"
	PathFindWeightModeMinWeight PathFindWeightMode = "min_weight"
)

// Defines values for PathWeightMode.
const (
	PathWeightModeMaxWeight PathWeightMode = "max_weight"
	PathWeightModeMinHops   PathWeightMode = "min_hops"
	PathWeightModeMinWeight PathWeightMode = "min_weight"
)

// AntflyType defines model for AntflyType.
type AntflyType string

// DistanceMetric Distance metric for the vector index (dense only). Use "cosine" for models trained with cosine similarity (e.g. CLIP, OpenAI). Use "inner_product" for models trained with dot product similarity. Use "l2_squared" (default) for models trained with Euclidean distance.
type DistanceMetric string

// Edge A typed, weighted connection between documents
type Edge struct {
	// CreatedAt When the edge was created
	CreatedAt time.Time `json:"created_at,omitempty"`

	// Metadata Optional edge metadata
	Metadata map[string]interface{} `json:"metadata,omitempty"`

	// Source Base64-encoded source document key
	Source []byte `json:"source"`

	// Target Base64-encoded target document key
	Target []byte `json:"target"`

	// Type Edge type (e.g., "cites", "similar_to", "authored_by")
	Type string `json:"type"`

	// UpdatedAt When the edge was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// Weight Edge weight/confidence (0.0 to 1.0)
	Weight float64 `json:"weight"`
}

// EdgeDirection Direction of edges to query:
// - out: Outgoing edges from the node
// - in: Incoming edges to the node
// - both: Both outgoing and incoming edges
type EdgeDirection string

// EdgeTypeConfig Configuration for a specific edge type
type EdgeTypeConfig struct {
	// AllowSelfLoops Whether to allow edges from a node to itself
	AllowSelfLoops bool `json:"allow_self_loops,omitempty"`

	// Field Document field containing target node key(s) for automatic edge creation.
	// Supports string (single target) or array of strings (multiple targets).
	// When omitted, edges must be provided explicitly via _edges.
	Field string `json:"field,omitempty"`

	// MaxWeight Maximum allowed edge weight
	MaxWeight float64 `json:"max_weight,omitempty"`

	// MinWeight Minimum allowed edge weight
	MinWeight float64 `json:"min_weight,omitempty"`

	// Name Edge type name (e.g., 'cites', 'similar_to')
	Name string `json:"name"`

	// RequiredMetadata Required metadata fields for this edge type
	RequiredMetadata *[]string `json:"required_metadata,omitempty"`

	// Topology Topology constraint for this edge type:
	// - tree: Single parent per node, no cycles
	// - graph: No constraints (default)
	Topology EdgeTypeConfigTopology `json:"topology,omitempty"`
}

// EdgeTypeConfigTopology Topology constraint for this edge type:
// - tree: Single parent per node, no cycles
// - graph: No constraints (default)
type EdgeTypeConfigTopology string

// EmbeddingsIndexConfig Unified configuration for embeddings indexes. When sparse is true, creates a sparse vector index (SPLADE inverted index). When sparse is false (default), creates a dense vector index (HNSW). For dense indexes, dimension can be omitted if an embedder is configured — it will be auto-detected.
type EmbeddingsIndexConfig struct {
	// ChunkSize Number of documents per posting list chunk (sparse only)
	ChunkSize int `json:"chunk_size,omitempty"`

	// Chunker A unified configuration for a chunking provider.
	Chunker *externalRef1.ChunkerConfig `json:"chunker,omitempty"`

	// Dimension Vector dimension for dense indexes. Can be omitted when an embedder is configured (auto-detected via probe). Ignored for sparse indexes.
	Dimension int `json:"dimension,omitempty"`

	// DistanceMetric Distance metric for the vector index (dense only). Use "cosine" for models trained with cosine similarity (e.g. CLIP, OpenAI). Use "inner_product" for models trained with dot product similarity. Use "l2_squared" (default) for models trained with Euclidean distance.
	DistanceMetric DistanceMetric `json:"distance_metric,omitempty"`

	// Embedder A unified configuration for an embedding provider.
	//
	// Embedders can be configured with templates to customize how documents are
	// converted to text before embedding. Templates use Handlebars syntax and
	// support various built-in helpers.
	//
	// **Template System:**
	// - **Syntax**: Handlebars templating (https://handlebarsjs.com/guide/)
	// - **Caching**: Templates are automatically cached with configurable TTL (default: 5 minutes)
	// - **Context**: Templates receive the full document as context
	//
	// **Built-in Helpers:**
	//
	// 1. **scrubHtml** - Remove script/style tags and extract clean text from HTML
	//    ```handlebars
	//    {{scrubHtml html_content}}
	//    ```
	//    - Removes `<script>` and `<style>` tags
	//    - Adds newlines after block elements (p, div, h1-h6, li, etc.)
	//    - Returns plain text with preserved readability
	//
	// 2. **eq** - Equality comparison for conditionals
	//    ```handlebars
	//    {{#if (eq status "active")}}Active user{{/if}}
	//    {{#if (eq @key "special")}}Special field{{/if}}
	//    ```
	//
	// 3. **media** - GenKit dotprompt media directive for multimodal content
	//    ```handlebars
	//    {{media url=imageDataURI}}
	//    {{media url=this.image_url}}
	//    {{media url="https://example.com/image.jpg"}}
	//    {{media url="s3://endpoint/bucket/image.png"}}
	//    {{media url="file:///path/to/image.jpg"}}
	//    ```
	//
	//    **Supported URL Schemes:**
	//    - `data:` - Base64 encoded data URIs (e.g., `data:image/jpeg;base64,...`)
	//    - `http://` / `https://` - Web URLs with automatic content type detection
	//    - `file://` - Local filesystem paths
	//    - `s3://` - S3-compatible storage (format: `s3://endpoint/bucket/key`)
	//
	//    **Automatic Content Processing:**
	//    - **Images**: Downloaded, resized (if needed), converted to data URIs
	//    - **PDFs**: Text extracted or first page rendered as image
	//    - **HTML**: Readable text extracted using Mozilla Readability
	//
	//    **Security Controls:**
	//    Downloads are protected by content security settings (see Configuration Reference):
	//    - Allowed host whitelist
	//    - Private IP blocking (prevents SSRF attacks)
	//    - Download size limits (default: 100MB)
	//    - Download timeouts (default: 30s)
	//    - Image dimension limits (default: 2048px, auto-resized)
	//
	//    See: https://antfly.io/docs/configuration#security--cors
	//
	// 4. **encodeToon** - Encode data in TOON format (Token-Oriented Object Notation)
	//    ```handlebars
	//    {{encodeToon this.fields}}
	//    {{encodeToon this.fields lengthMarker=false indent=4}}
	//    {{encodeToon this.fields delimiter="\t"}}
	//    ```
	//
	//    **What is TOON?**
	//    TOON is a compact, human-readable format designed for passing structured data to LLMs.
	//    It provides **30-60% token reduction** compared to JSON while maintaining high LLM
	//    comprehension accuracy.
	//
	//    **Key Features:**
	//    - Compact syntax using `:` for key-value pairs
	//    - Array length markers: `tags[#3]: ai,search,ml`
	//    - Tabular format for uniform data structures
	//    - Optimized for LLM parsing and understanding
	//    - Maintains human readability
	//
	//    **Benefits:**
	//    - **Lower API costs** - Reduced token usage means lower LLM API costs
	//    - **Faster responses** - Less tokens to process
	//    - **More context** - Fit more documents within token limits
	//
	//    **Options:**
	//    - `lengthMarker` (bool): Add # prefix to array counts like `[#3]` (default: true)
	//    - `indent` (int): Indentation spacing for nested objects (default: 2)
	//    - `delimiter` (string): Field separator for tabular arrays (default: none, use `"\t"` for tabs)
	//
	//    **Example output:**
	//    ```
	//    title: Introduction to Vector Search
	//    author: Jane Doe
	//    tags[#3]: ai,search,ml
	//    metadata:
	//      edition: 2
	//      pages: 450
	//    ```
	//
	//    **Default in RAG:** TOON is the default format for document rendering in RAG queries.
	//
	//    **References:**
	//    - TOON Specification: https://github.com/toon-format/toon
	//    - Go Implementation: https://github.com/alpkeskin/gotoon
	//
	// **Template Examples:**
	//
	// Document with metadata:
	// ```handlebars
	// Title: {{metadata.title}}
	// Date: {{metadata.date}}
	// Tags: {{#each metadata.tags}}{{this}}, {{/each}}
	//
	// {{content}}
	// ```
	//
	// HTML content extraction:
	// ```handlebars
	// Product: {{name}}
	// Description: {{scrubHtml description_html}}
	// Price: ${{price}}
	// ```
	//
	// Multimodal with image:
	// ```handlebars
	// Product: {{title}}
	// {{media url=image}}
	// Description: {{description}}
	// ```
	//
	// Conditional formatting:
	// ```handlebars
	// {{title}}
	// {{#if author}}By: {{author}}{{/if}}
	// {{#if (eq category "premium")}}⭐ Premium Content{{/if}}
	// {{body}}
	// ```
	//
	// **Environment Variables:**
	// - `GEMINI_API_KEY` - API key for Google AI
	// - `OPENAI_API_KEY` - API key for OpenAI
	// - `OPENAI_BASE_URL` - Base URL for OpenAI-compatible APIs
	// - `OLLAMA_HOST` - Ollama server URL (e.g., http://localhost:11434)
	//
	// **Importing Pre-computed Embeddings:**
	//
	// You can import existing embeddings (from OpenAI, Cohere, or any provider) by including
	// them directly in your documents using the `_embeddings` field. This bypasses the
	// embedding generation step and writes vectors directly to the index.
	//
	// **Steps:**
	// 1. Create the index first with the appropriate dimension
	// 2. Write documents with `_embeddings: { "<indexName>": [...<embedding>...] }`
	//
	// **Example:**
	// ```json
	// {
	//   "title": "My Document",
	//   "content": "Document text...",
	//   "_embeddings": {
	//     "my_vector_index": [0.1, 0.2, 0.3, ...]
	//   }
	// }
	// ```
	//
	// **Use Cases:**
	// - Migrating from another vector database with existing embeddings
	// - Using embeddings generated by external systems
	// - Importing pre-computed OpenAI, Cohere, or other provider embeddings
	// - Batch processing embeddings offline before ingestion
	Embedder *externalRef2.EmbedderConfig `json:"embedder,omitempty"`

	// Field Field to extract embeddings from
	Field string `json:"field,omitempty"`

	// MemOnly Whether to use in-memory only storage (dense only)
	MemOnly bool `json:"mem_only,omitempty"`

	// MinWeight Minimum weight threshold for sparse vector entries (sparse only)
	MinWeight float32 `json:"min_weight,omitempty"`

	// Sparse When true, creates a sparse (SPLADE) inverted index. When false (default), creates a dense (HNSW) vector index.
	Sparse bool `json:"sparse,omitempty"`

	// Summarizer A unified configuration for a generative AI provider.
	//
	// Generators can be configured with custom prompts using templates. Templates use
	// Handlebars syntax and support various built-in helpers for formatting and data manipulation.
	//
	// **Template System:**
	// - **Syntax**: Handlebars templating (https://handlebarsjs.com/guide/)
	// - **Caching**: Templates are automatically cached with configurable TTL (default: 5 minutes)
	// - **Context**: Templates receive the full context data passed to the generator
	//
	// **Built-in Helpers:**
	//
	// 1. **scrubHtml** - Remove script/style tags and extract clean text from HTML
	//    ```handlebars
	//    {{scrubHtml html_content}}
	//    ```
	//    - Removes `<script>` and `<style>` tags
	//    - Adds newlines after block elements (p, div, h1-h6, li, etc.)
	//    - Returns plain text with preserved readability
	//    - Useful for cleaning web content before summarization
	//
	// 2. **eq** - Equality comparison for conditionals
	//    ```handlebars
	//    {{#if (eq status "active")}}Active{{/if}}
	//    {{#if (eq @key "special")}}Special field{{/if}}
	//    ```
	//    - Use in `{{#if}}` blocks for conditional logic
	//    - Compares any two values for equality
	//
	// 3. **media** - GenKit dotprompt media directive for multimodal content
	//    ```handlebars
	//    {{media url=imageDataURI}}
	//    {{media url=this.image_url}}
	//    {{media url="https://example.com/image.jpg"}}
	//    {{media url="s3://endpoint/bucket/image.png"}}
	//    {{media url="file:///path/to/image.jpg"}}
	//    ```
	//
	//    **Supported URL Schemes:**
	//    - `data:` - Base64 encoded data URIs (e.g., `data:image/jpeg;base64,...`)
	//    - `http://` / `https://` - Web URLs with automatic content type detection
	//    - `file://` - Local filesystem paths
	//    - `s3://` - S3-compatible storage (format: `s3://endpoint/bucket/key`)
	//
	//    **Automatic Content Processing:**
	//    - **Images**: Downloaded, resized (if needed), converted to data URIs
	//    - **PDFs**: Text extracted or first page rendered as image
	//    - **HTML**: Readable text extracted using Mozilla Readability
	//
	//    **Security Controls:**
	//    Downloads are protected by content security settings (see Configuration Reference):
	//    - Allowed host whitelist
	//    - Private IP blocking (prevents SSRF attacks)
	//    - Download size limits (default: 100MB)
	//    - Download timeouts (default: 30s)
	//    - Image dimension limits (default: 2048px, auto-resized)
	//
	//    See: https://antfly.io/docs/configuration#security--cors
	//
	// 4. **encodeToon** - Encode data in TOON format (Token-Oriented Object Notation)
	//    ```handlebars
	//    {{encodeToon this.fields}}
	//    {{encodeToon this.fields lengthMarker=false indent=4}}
	//    {{encodeToon this.fields delimiter="\t"}}
	//    ```
	//
	//    **What is TOON?**
	//    TOON is a compact, human-readable format designed for passing structured data to LLMs.
	//    It provides **30-60% token reduction** compared to JSON while maintaining high LLM
	//    comprehension accuracy.
	//
	//    **Key Features:**
	//    - Compact syntax using `:` for key-value pairs
	//    - Array length markers: `tags[#3]: ai,search,ml`
	//    - Tabular format for uniform data structures
	//    - Optimized for LLM parsing and understanding
	//    - Maintains human readability
	//
	//    **Benefits:**
	//    - **Lower API costs** - Reduced token usage means lower LLM API costs
	//    - **Faster responses** - Less tokens to process
	//    - **More context** - Fit more documents within token limits
	//
	//    **Options:**
	//    - `lengthMarker` (bool): Add # prefix to array counts like `[#3]` (default: true)
	//    - `indent` (int): Indentation spacing for nested objects (default: 2)
	//    - `delimiter` (string): Field separator for tabular arrays (default: none, use `"\t"` for tabs)
	//
	//    **Example output:**
	//    ```
	//    title: Introduction to Vector Search
	//    author: Jane Doe
	//    tags[#3]: ai,search,ml
	//    metadata:
	//      edition: 2
	//      pages: 450
	//    ```
	//
	//    **Default in RAG:** TOON is the default format for document rendering in RAG queries.
	//
	//    **References:**
	//    - TOON Specification: https://github.com/toon-format/toon
	//    - Go Implementation: https://github.com/alpkeskin/gotoon
	//
	// **Template Examples:**
	//
	// RAG summarization with document references:
	// ```handlebars
	// Based on these documents, provide a comprehensive summary:
	//
	// {{#each documents}}
	// Document {{this.id}}:
	// {{scrubHtml this.content}}
	//
	// {{/each}}
	//
	// Valid document IDs: {{#each documents}}{{this.id}}{{#unless @last}}, {{/unless}}{{/each}}
	// ```
	//
	// Conditional formatting:
	// ```handlebars
	// {{#if system_prompt}}System: {{system_prompt}}{{/if}}
	//
	// User Query: {{query}}
	//
	// {{#if context}}
	// Context:
	// {{#each context}}
	// - {{this}}
	// {{/each}}
	// {{/if}}
	// ```
	//
	// Multimodal prompt with images:
	// ```handlebars
	// Analyze this image:
	// {{media url=image_url}}
	//
	// Focus on: {{focus_area}}
	// ```
	//
	// Structured data encoding:
	// ```handlebars
	// User Profile:
	// {{encodeToon user_data indent=2 lengthMarker=true}}
	//
	// Please analyze this profile.
	// ```
	//
	// **Common Use Cases:**
	// - **RAG (Retrieval-Augmented Generation)**: Format retrieved documents with citations
	// - **Summarization**: Clean HTML content and structure summaries
	// - **Query Classification**: Format queries with metadata for better classification
	// - **Multimodal**: Include images/audio/video in prompts
	// - **Data Formatting**: Convert structured data to readable text
	//
	// **Best Practices:**
	// - Keep templates simple - complex logic belongs in application code
	// - Use clear, descriptive field names in context
	// - Handle missing fields gracefully (templates use "missingkey=zero" by default)
	// - Test templates with representative data before production use
	Summarizer *externalRef0.GeneratorConfig `json:"summarizer,omitempty"`

	// Template Handlebars template for generating prompts. See https://handlebarsjs.com/guide/ for more information.
	Template string `json:"template,omitempty"`

	// TopK Default number of results to return from search (sparse only)
	TopK int `json:"top_k,omitempty"`
}

// EmbeddingsIndexStats Statistics for an embeddings index (dense or sparse)
type EmbeddingsIndexStats struct {
	// BackfillItemsProcessed Total items processed during backfill
	BackfillItemsProcessed uint64 `json:"backfill_items_processed,omitempty"`

	// BackfillProgress Backfill progress as a ratio from 0.0 to 1.0
	BackfillProgress float64 `json:"backfill_progress,omitempty"`

	// DiskUsage Size of the index in bytes
	DiskUsage uint64 `json:"disk_usage,omitempty"`

	// Error Error message if stats could not be retrieved
	Error string `json:"error,omitempty"`

	// Rebuilding Whether the index enricher is currently backfilling
	Rebuilding bool `json:"rebuilding,omitempty"`

	// TotalIndexed Number of vectors/documents in the index
	TotalIndexed uint64 `json:"total_indexed,omitempty"`

	// TotalNodes Total number of nodes in the index (dense only)
	TotalNodes uint64 `json:"total_nodes,omitempty"`

	// TotalTerms Number of unique terms in the inverted index (sparse only)
	TotalTerms uint64 `json:"total_terms,omitempty"`

	// WalBacklog Number of documents pending enrichment in the WAL
	WalBacklog uint64 `json:"wal_backlog,omitempty"`
}

// FullTextIndexConfig defines model for FullTextIndexConfig.
type FullTextIndexConfig struct {
	// MemOnly Whether to use memory-only storage
	MemOnly bool `json:"mem_only,omitempty"`
}

// FullTextIndexStats defines model for FullTextIndexStats.
type FullTextIndexStats struct {
	// BackfillItemsProcessed Number of documents indexed during current rebuild
	BackfillItemsProcessed uint64 `json:"backfill_items_processed,omitempty"`

	// BackfillProgress Progress of ongoing rebuild as fraction [0.0, 1.0]
	BackfillProgress float64 `json:"backfill_progress,omitempty"`

	// DiskUsage Size of the index in bytes
	DiskUsage uint64 `json:"disk_usage,omitempty"`

	// Error Error message if stats could not be retrieved
	Error string `json:"error,omitempty"`

	// Rebuilding Whether the index is currently rebuilding
	Rebuilding bool `json:"rebuilding,omitempty"`

	// TotalIndexed Number of documents in the index
	TotalIndexed uint64 `json:"total_indexed,omitempty"`
}

// GraphIndexConfig Configuration for graph index type
type GraphIndexConfig struct {
	// EdgeTypes List of edge types with their configurations
	EdgeTypes *[]EdgeTypeConfig `json:"edge_types,omitempty"`

	// MaxEdgesPerDocument Maximum number of edges per document (0 = unlimited)
	MaxEdgesPerDocument int `json:"max_edges_per_document,omitempty"`

	// Summarizer A unified configuration for a generative AI provider.
	//
	// Generators can be configured with custom prompts using templates. Templates use
	// Handlebars syntax and support various built-in helpers for formatting and data manipulation.
	//
	// **Template System:**
	// - **Syntax**: Handlebars templating (https://handlebarsjs.com/guide/)
	// - **Caching**: Templates are automatically cached with configurable TTL (default: 5 minutes)
	// - **Context**: Templates receive the full context data passed to the generator
	//
	// **Built-in Helpers:**
	//
	// 1. **scrubHtml** - Remove script/style tags and extract clean text from HTML
	//    ```handlebars
	//    {{scrubHtml html_content}}
	//    ```
	//    - Removes `<script>` and `<style>` tags
	//    - Adds newlines after block elements (p, div, h1-h6, li, etc.)
	//    - Returns plain text with preserved readability
	//    - Useful for cleaning web content before summarization
	//
	// 2. **eq** - Equality comparison for conditionals
	//    ```handlebars
	//    {{#if (eq status "active")}}Active{{/if}}
	//    {{#if (eq @key "special")}}Special field{{/if}}
	//    ```
	//    - Use in `{{#if}}` blocks for conditional logic
	//    - Compares any two values for equality
	//
	// 3. **media** - GenKit dotprompt media directive for multimodal content
	//    ```handlebars
	//    {{media url=imageDataURI}}
	//    {{media url=this.image_url}}
	//    {{media url="https://example.com/image.jpg"}}
	//    {{media url="s3://endpoint/bucket/image.png"}}
	//    {{media url="file:///path/to/image.jpg"}}
	//    ```
	//
	//    **Supported URL Schemes:**
	//    - `data:` - Base64 encoded data URIs (e.g., `data:image/jpeg;base64,...`)
	//    - `http://` / `https://` - Web URLs with automatic content type detection
	//    - `file://` - Local filesystem paths
	//    - `s3://` - S3-compatible storage (format: `s3://endpoint/bucket/key`)
	//
	//    **Automatic Content Processing:**
	//    - **Images**: Downloaded, resized (if needed), converted to data URIs
	//    - **PDFs**: Text extracted or first page rendered as image
	//    - **HTML**: Readable text extracted using Mozilla Readability
	//
	//    **Security Controls:**
	//    Downloads are protected by content security settings (see Configuration Reference):
	//    - Allowed host whitelist
	//    - Private IP blocking (prevents SSRF attacks)
	//    - Download size limits (default: 100MB)
	//    - Download timeouts (default: 30s)
	//    - Image dimension limits (default: 2048px, auto-resized)
	//
	//    See: https://antfly.io/docs/configuration#security--cors
	//
	// 4. **encodeToon** - Encode data in TOON format (Token-Oriented Object Notation)
	//    ```handlebars
	//    {{encodeToon this.fields}}
	//    {{encodeToon this.fields lengthMarker=false indent=4}}
	//    {{encodeToon this.fields delimiter="\t"}}
	//    ```
	//
	//    **What is TOON?**
	//    TOON is a compact, human-readable format designed for passing structured data to LLMs.
	//    It provides **30-60% token reduction** compared to JSON while maintaining high LLM
	//    comprehension accuracy.
	//
	//    **Key Features:**
	//    - Compact syntax using `:` for key-value pairs
	//    - Array length markers: `tags[#3]: ai,search,ml`
	//    - Tabular format for uniform data structures
	//    - Optimized for LLM parsing and understanding
	//    - Maintains human readability
	//
	//    **Benefits:**
	//    - **Lower API costs** - Reduced token usage means lower LLM API costs
	//    - **Faster responses** - Less tokens to process
	//    - **More context** - Fit more documents within token limits
	//
	//    **Options:**
	//    - `lengthMarker` (bool): Add # prefix to array counts like `[#3]` (default: true)
	//    - `indent` (int): Indentation spacing for nested objects (default: 2)
	//    - `delimiter` (string): Field separator for tabular arrays (default: none, use `"\t"` for tabs)
	//
	//    **Example output:**
	//    ```
	//    title: Introduction to Vector Search
	//    author: Jane Doe
	//    tags[#3]: ai,search,ml
	//    metadata:
	//      edition: 2
	//      pages: 450
	//    ```
	//
	//    **Default in RAG:** TOON is the default format for document rendering in RAG queries.
	//
	//    **References:**
	//    - TOON Specification: https://github.com/toon-format/toon
	//    - Go Implementation: https://github.com/alpkeskin/gotoon
	//
	// **Template Examples:**
	//
	// RAG summarization with document references:
	// ```handlebars
	// Based on these documents, provide a comprehensive summary:
	//
	// {{#each documents}}
	// Document {{this.id}}:
	// {{scrubHtml this.content}}
	//
	// {{/each}}
	//
	// Valid document IDs: {{#each documents}}{{this.id}}{{#unless @last}}, {{/unless}}{{/each}}
	// ```
	//
	// Conditional formatting:
	// ```handlebars
	// {{#if system_prompt}}System: {{system_prompt}}{{/if}}
	//
	// User Query: {{query}}
	//
	// {{#if context}}
	// Context:
	// {{#each context}}
	// - {{this}}
	// {{/each}}
	// {{/if}}
	// ```
	//
	// Multimodal prompt with images:
	// ```handlebars
	// Analyze this image:
	// {{media url=image_url}}
	//
	// Focus on: {{focus_area}}
	// ```
	//
	// Structured data encoding:
	// ```handlebars
	// User Profile:
	// {{encodeToon user_data indent=2 lengthMarker=true}}
	//
	// Please analyze this profile.
	// ```
	//
	// **Common Use Cases:**
	// - **RAG (Retrieval-Augmented Generation)**: Format retrieved documents with citations
	// - **Summarization**: Clean HTML content and structure summaries
	// - **Query Classification**: Format queries with metadata for better classification
	// - **Multimodal**: Include images/audio/video in prompts
	// - **Data Formatting**: Convert structured data to readable text
	//
	// **Best Practices:**
	// - Keep templates simple - complex logic belongs in application code
	// - Use clear, descriptive field names in context
	// - Handle missing fields gracefully (templates use "missingkey=zero" by default)
	// - Test templates with representative data before production use
	Summarizer *externalRef0.GeneratorConfig `json:"summarizer,omitempty"`

	// Template Handlebars template for generating summarizer input text.
	// Uses document fields as template variables.
	// Same pattern as EmbeddingsConfig template.
	Template string `json:"template,omitempty"`
}

// GraphIndexStats Statistics for graph index
type GraphIndexStats struct {
	// BackfillItemsProcessed Number of edges indexed during current rebuild
	BackfillItemsProcessed uint64 `json:"backfill_items_processed,omitempty"`

	// BackfillProgress Rebuild progress as a ratio from 0.0 to 1.0
	BackfillProgress float64 `json:"backfill_progress,omitempty"`

	// EdgeTypes Count of edges per edge type
	EdgeTypes *map[string]uint64 `json:"edge_types,omitempty"`

	// Error Error message if stats could not be retrieved
	Error string `json:"error,omitempty"`

	// Rebuilding Whether the index is currently rebuilding
	Rebuilding bool `json:"rebuilding,omitempty"`

	// TotalEdges Total number of edges in the graph
	TotalEdges uint64 `json:"total_edges,omitempty"`
}

// GraphNodeSelector Defines how to select start/target nodes for graph queries
type GraphNodeSelector struct {
	// Keys Explicit list of node keys
	Keys []string `json:"keys,omitempty"`

	// Limit Maximum number of nodes to select from the referenced results
	Limit int `json:"limit,omitempty"`

	// NodeFilter Filter nodes during graph traversal using existing query primitives
	NodeFilter NodeFilter `json:"node_filter,omitempty"`

	// ResultRef Reference to search results to use as nodes:
	// - "$full_text_results" - use full-text search results
	// - "$embeddings_results.index_name" - use vector search results from specific index
	ResultRef string `json:"result_ref,omitempty"`
}

// GraphQuery Declarative graph query to execute after full-text/vector searches
type GraphQuery struct {
	// Fields Which fields to return from documents
	Fields []string `json:"fields,omitempty"`

	// IncludeDocuments Fetch full documents for graph results
	IncludeDocuments bool `json:"include_documents,omitempty"`

	// IncludeEdges Include edge details for each node
	IncludeEdges bool `json:"include_edges,omitempty"`

	// IndexName Graph index name (must be graph type)
	IndexName string `json:"index_name"`

	// Params Parameters for graph traversal and pathfinding
	Params GraphQueryParams `json:"params,omitempty"`

	// Pattern Pattern steps for pattern query type
	Pattern []PatternStep `json:"pattern,omitempty"`

	// ReturnAliases Which aliases to return from pattern query (empty = all)
	ReturnAliases []string `json:"return_aliases,omitempty"`

	// StartNodes Defines how to select start/target nodes for graph queries
	StartNodes GraphNodeSelector `json:"start_nodes,omitempty"`

	// TargetNodes Defines how to select start/target nodes for graph queries
	TargetNodes GraphNodeSelector `json:"target_nodes,omitempty"`

	// Type Type of graph query to execute
	Type GraphQueryType `json:"type"`
}

// GraphQueryParams Parameters for graph traversal and pathfinding
type GraphQueryParams struct {
	// Algorithm Graph algorithm to run (e.g., 'pagerank', 'betweenness')
	Algorithm string `json:"algorithm,omitempty"`

	// AlgorithmParams Parameters for the graph algorithm
	AlgorithmParams map[string]interface{} `json:"algorithm_params,omitempty"`

	// DeduplicateNodes Remove duplicate nodes (traversal)
	DeduplicateNodes bool `json:"deduplicate_nodes,omitempty"`

	// Direction Direction of edges to query:
	// - out: Outgoing edges from the node
	// - in: Incoming edges to the node
	// - both: Both outgoing and incoming edges
	Direction EdgeDirection `json:"direction,omitempty"`

	// EdgeTypes Filter by edge types
	EdgeTypes []string `json:"edge_types,omitempty"`

	// IncludePaths Include path information (traversal)
	IncludePaths bool `json:"include_paths,omitempty"`

	// K Number of paths to find (k-shortest-paths)
	K int `json:"k,omitempty"`

	// MaxDepth Maximum traversal depth
	MaxDepth int `json:"max_depth,omitempty"`

	// MaxResults Maximum number of results (traversal)
	MaxResults int `json:"max_results,omitempty"`

	// MaxWeight Maximum edge weight
	MaxWeight float64 `json:"max_weight,omitempty"`

	// MinWeight Minimum edge weight
	MinWeight float64 `json:"min_weight,omitempty"`

	// NodeFilter Filter nodes during graph traversal using existing query primitives
	NodeFilter NodeFilter `json:"node_filter,omitempty"`

	// WeightMode Path weighting algorithm for pathfinding:
	// - min_hops: Minimize number of edges
	// - min_weight: Minimize sum of edge weights
	// - max_weight: Maximize product of edge weights
	WeightMode PathWeightMode `json:"weight_mode,omitempty"`
}

// GraphQueryResult Results of a graph query
type GraphQueryResult struct {
	// Matches Pattern matches (for pattern queries)
	Matches []PatternMatch `json:"matches,omitempty"`

	// Nodes Result nodes
	Nodes []GraphResultNode `json:"nodes,omitempty"`

	// Paths Result paths (for pathfinding queries)
	Paths []Path `json:"paths,omitempty"`

	// Took Query execution time
	Took time.Duration `json:"took,omitempty"`

	// Total Total number of results
	Total int `json:"total"`

	// Type Type of graph query to execute
	Type GraphQueryType `json:"type"`
}

// GraphQueryType Type of graph query to execute
type GraphQueryType string

// GraphResultNode A node in graph query results
type GraphResultNode struct {
	// Depth Distance from start node
	Depth int `json:"depth,omitempty"`

	// Distance Weighted distance
	Distance float64 `json:"distance,omitempty"`

	// Document Full document (if include_documents=true)
	Document map[string]interface{} `json:"document,omitempty"`

	// Edges Connected edges (when include_edges=true)
	Edges []Edge `json:"edges,omitempty"`

	// Key Document key
	Key string `json:"key"`

	// Path Keys in path from start to this node
	Path []string `json:"path,omitempty"`

	// PathEdges Edges in path from start to this node
	PathEdges []PathEdge `json:"path_edges,omitempty"`
}

// IndexConfig Configuration for an index
type IndexConfig struct {
	// Description Optional description of the index and its purpose
	Description *string `json:"description,omitempty"`

	// Enrichments List of enrichment names to apply to documents before indexing. Enrichments must be defined at the table level.
	Enrichments []string `json:"enrichments,omitempty"`

	// Name Name of the index
	Name string `json:"name"`

	// Type The type of the index.
	Type IndexType `json:"type"`

	// Version Version of the index implementation. Defaults to 0.
	Version int `json:"version,omitempty"`
	union   json.RawMessage
}

// IndexStats Statistics for an index
type IndexStats struct {
	union json.RawMessage
}

// IndexType The type of the index.
type IndexType string

// MergeConfig Configuration for result fusion when combining multiple search indexes.
type MergeConfig struct {
	// RankConstant RRF k constant (1/(k+rank)). Defaults to 60.0.
	RankConstant float64 `json:"rank_constant,omitempty"`

	// Strategy Merge strategy for combining results from the semantic_search and full_text_search.
	// rrf: Reciprocal Rank Fusion - combines scores using reciprocal rank formula
	// rsf: Relative Score Fusion - normalizes scores by min/max within a window and combines weighted scores
	// failover: Use full_text_search if embedding generation fails
	Strategy *MergeStrategy `json:"strategy,omitempty"`

	// Weights Named weights keyed by index name. `full_text` for the full-text search index;
	// embedding index names for vector indexes.
	// Unspecified indexes default to 1.0. Applied in both RRF and RSF.
	Weights *map[string]float64 `json:"weights,omitempty"`

	// WindowSize RSF normalization window size. Defaults to `limit`.
	WindowSize int `json:"window_size,omitempty"`
}

// MergeStrategy Merge strategy for combining results from the semantic_search and full_text_search.
// rrf: Reciprocal Rank Fusion - combines scores using reciprocal rank formula
// rsf: Relative Score Fusion - normalizes scores by min/max within a window and combines weighted scores
// failover: Use full_text_search if embedding generation fails
type MergeStrategy string

// NodeFilter Filter nodes during graph traversal using existing query primitives
type NodeFilter struct {
	// FilterPrefix Filter by key prefix
	FilterPrefix string `json:"filter_prefix,omitempty"`

	// FilterQuery Bleve query to filter nodes (same syntax as search filter_query)
	FilterQuery map[string]interface{} `json:"filter_query,omitempty"`
}

// Path defines model for Path.
type Path struct {
	Edges  []PathEdge `json:"edges,omitempty"`
	Length int        `json:"length,omitempty"`

	// Nodes Ordered list of node keys (base64-encoded)
	Nodes       []string `json:"nodes,omitempty"`
	TotalWeight float64  `json:"total_weight,omitempty"`
}

// PathEdge defines model for PathEdge.
type PathEdge struct {
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Source   string                 `json:"source,omitempty"`
	Target   string                 `json:"target,omitempty"`
	Type     string                 `json:"type,omitempty"`
	Weight   float64                `json:"weight,omitempty"`
}

// PathFindRequest defines model for PathFindRequest.
type PathFindRequest struct {
	// Direction Direction of edges to query:
	// - out: Outgoing edges from the node
	// - in: Incoming edges to the node
	// - both: Both outgoing and incoming edges
	Direction EdgeDirection `json:"direction,omitempty"`

	// EdgeTypes Filter by specific edge types
	EdgeTypes []string `json:"edge_types,omitempty"`
	K         int      `json:"k,omitempty"`
	MaxDepth  int      `json:"max_depth,omitempty"`
	MaxWeight float64  `json:"max_weight,omitempty"`
	MinWeight float64  `json:"min_weight,omitempty"`

	// Source Source node key (base64-encoded)
	Source string `json:"source"`

	// Target Target node key (base64-encoded)
	Target string `json:"target"`

	// WeightMode Algorithm for path finding:
	// - min_hops: Shortest path by hop count (breadth-first search, ignores weights)
	// - max_weight: Path with maximum product of edge weights (strongest connection chain)
	// - min_weight: Path with minimum sum of edge weights (lowest cost route)
	WeightMode PathFindWeightMode `json:"weight_mode,omitempty"`
}

// PathFindResult defines model for PathFindResult.
type PathFindResult struct {
	Paths        []Path  `json:"paths,omitempty"`
	PathsFound   int     `json:"paths_found,omitempty"`
	SearchTimeMs float64 `json:"search_time_ms,omitempty"`
	Source       string  `json:"source,omitempty"`
	Target       string  `json:"target,omitempty"`

	// WeightMode Algorithm for path finding:
	// - min_hops: Shortest path by hop count (breadth-first search, ignores weights)
	// - max_weight: Path with maximum product of edge weights (strongest connection chain)
	// - min_weight: Path with minimum sum of edge weights (lowest cost route)
	WeightMode PathFindWeightMode `json:"weight_mode,omitempty"`
}

// PathFindWeightMode Algorithm for path finding:
// - min_hops: Shortest path by hop count (breadth-first search, ignores weights)
// - max_weight: Path with maximum product of edge weights (strongest connection chain)
// - min_weight: Path with minimum sum of edge weights (lowest cost route)
type PathFindWeightMode string

// PathWeightMode Path weighting algorithm for pathfinding:
// - min_hops: Minimize number of edges
// - min_weight: Minimize sum of edge weights
// - max_weight: Maximize product of edge weights
type PathWeightMode string

// PatternEdgeStep Edge constraints in a pattern step
type PatternEdgeStep struct {
	// Direction Direction of edges to query:
	// - out: Outgoing edges from the node
	// - in: Incoming edges to the node
	// - both: Both outgoing and incoming edges
	Direction EdgeDirection `json:"direction,omitempty"`

	// MaxHops Maximum number of hops (>1 = variable-length path)
	MaxHops int `json:"max_hops,omitempty"`

	// MaxWeight Maximum edge weight filter
	MaxWeight float64 `json:"max_weight,omitempty"`

	// MinHops Minimum number of hops (1 = direct edge)
	MinHops int `json:"min_hops,omitempty"`

	// MinWeight Minimum edge weight filter
	MinWeight float64 `json:"min_weight,omitempty"`

	// Types Edge types to traverse (empty = any)
	Types []string `json:"types,omitempty"`
}

// PatternMatch A single match from a pattern query
type PatternMatch struct {
	// Bindings Map of alias to matched node
	Bindings map[string]GraphResultNode `json:"bindings,omitempty"`

	// Path Edges traversed in this match
	Path []PathEdge `json:"path,omitempty"`
}

// PatternStep A step in a graph pattern query
type PatternStep struct {
	// Alias Name for this node (reuse alias for cycle detection)
	Alias string `json:"alias,omitempty"`

	// Edge Edge constraints in a pattern step
	Edge PatternEdgeStep `json:"edge,omitempty"`

	// NodeFilter Filter nodes during graph traversal using existing query primitives
	NodeFilter NodeFilter `json:"node_filter,omitempty"`
}

// Pruner Configuration for pruning search results based on score quality.
// Helps filter out low-relevance results in RAG pipelines by detecting
// score gaps or deviations from top results.
type Pruner struct {
	// MaxScoreGapPercent Stop returning results when the gap between consecutive scores
	// exceeds this percentage of the total score range (max - min).
	// Detects "elbows" in score distributions regardless of score scale.
	// For example, 30.0 stops when a gap spans 30% of the score range.
	MaxScoreGapPercent float64 `json:"max_score_gap_percent,omitempty"`

	// MinAbsoluteScore Hard minimum score threshold. Results with scores below this value
	// are excluded regardless of other pruning settings.
	MinAbsoluteScore float64 `json:"min_absolute_score,omitempty"`

	// MinScoreRatio Keep only results with score >= max_score * min_score_ratio.
	// For example, 0.5 keeps results scoring at least half of the top result.
	// Applied after fusion scoring.
	MinScoreRatio float64 `json:"min_score_ratio,omitempty"`

	// RequireMultiIndex Only keep results that appear in multiple indexes (both full-text
	// and vector search). Useful for increasing precision by requiring
	// agreement between different retrieval methods.
	RequireMultiIndex bool `json:"require_multi_index,omitempty"`

	// StdDevThreshold Keep results within N standard deviations below the mean score.
	// For example, 1.0 keeps results with score >= mean - 1*stddev.
	// Useful for statistical outlier detection in result sets.
	StdDevThreshold float64 `json:"std_dev_threshold,omitempty"`
}

// SortDirection Sort direction for a single field. true = descending, false = ascending.
type SortDirection = bool

// SortField A single sort field with direction.
type SortField struct {
	// Desc Sort direction. true = descending, false = ascending.
	Desc *bool `json:"desc,omitempty"`

	// Field The field name to sort by.
	Field string `json:"field"`
}

// TraversalResult A single result from graph traversal
type TraversalResult struct {
	// Depth Distance from start node (0 = start node)
	Depth int `json:"depth"`

	// Document Document data (if loaded)
	Document map[string]interface{} `json:"document,omitempty"`

	// Key Base64-encoded document key
	Key []byte `json:"key"`

	// Path Sequence of keys from start to this node (if include_paths=true)
	Path [][]byte `json:"path,omitempty"`

	// PathEdges Sequence of edges from start to this node (if include_paths=true)
	PathEdges []Edge `json:"path_edges,omitempty"`

	// TotalWeight Product of edge weights along the path
	TotalWeight float64 `json:"total_weight,omitempty"`
}

// TraversalRules Rules for graph traversal
type TraversalRules struct {
	// DeduplicateNodes Visit each node only once
	DeduplicateNodes bool `json:"deduplicate_nodes,omitempty"`

	// Direction Direction of edges to query:
	// - out: Outgoing edges from the node
	// - in: Incoming edges to the node
	// - both: Both outgoing and incoming edges
	Direction EdgeDirection `json:"direction,omitempty"`

	// EdgeTypes Filter edges by type (empty = all types)
	EdgeTypes []string `json:"edge_types,omitempty"`

	// IncludePaths Include path information in results
	IncludePaths bool `json:"include_paths,omitempty"`

	// MaxDepth Maximum traversal depth (0 = unlimited)
	MaxDepth int `json:"max_depth,omitempty"`

	// MaxResults Maximum results to return (0 = unlimited)
	MaxResults int `json:"max_results,omitempty"`

	// MaxWeight Maximum edge weight filter
	MaxWeight float64 `json:"max_weight,omitempty"`

	// MinWeight Minimum edge weight filter
	MinWeight float64 `json:"min_weight,omitempty"`
}

// AsFullTextIndexConfig returns the union data inside the IndexConfig as a FullTextIndexConfig
func (t IndexConfig) AsFullTextIndexConfig() (FullTextIndexConfig, error) {
	var body FullTextIndexConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFullTextIndexConfig overwrites any union data inside the IndexConfig as the provided FullTextIndexConfig
func (t *IndexConfig) FromFullTextIndexConfig(v FullTextIndexConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFullTextIndexConfig performs a merge with any union data inside the IndexConfig, using the provided FullTextIndexConfig
func (t *IndexConfig) MergeFullTextIndexConfig(v FullTextIndexConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbeddingsIndexConfig returns the union data inside the IndexConfig as a EmbeddingsIndexConfig
func (t IndexConfig) AsEmbeddingsIndexConfig() (EmbeddingsIndexConfig, error) {
	var body EmbeddingsIndexConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbeddingsIndexConfig overwrites any union data inside the IndexConfig as the provided EmbeddingsIndexConfig
func (t *IndexConfig) FromEmbeddingsIndexConfig(v EmbeddingsIndexConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbeddingsIndexConfig performs a merge with any union data inside the IndexConfig, using the provided EmbeddingsIndexConfig
func (t *IndexConfig) MergeEmbeddingsIndexConfig(v EmbeddingsIndexConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGraphIndexConfig returns the union data inside the IndexConfig as a GraphIndexConfig
func (t IndexConfig) AsGraphIndexConfig() (GraphIndexConfig, error) {
	var body GraphIndexConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGraphIndexConfig overwrites any union data inside the IndexConfig as the provided GraphIndexConfig
func (t *IndexConfig) FromGraphIndexConfig(v GraphIndexConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGraphIndexConfig performs a merge with any union data inside the IndexConfig, using the provided GraphIndexConfig
func (t *IndexConfig) MergeGraphIndexConfig(v GraphIndexConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t IndexConfig) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Description != nil {
		object["description"], err = json.Marshal(t.Description)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'description': %w", err)
		}
	}

	if t.Enrichments != nil {
		object["enrichments"], err = json.Marshal(t.Enrichments)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'enrichments': %w", err)
		}
	}

	object["name"], err = json.Marshal(t.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	object["type"], err = json.Marshal(t.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	object["version"], err = json.Marshal(t.Version)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'version': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *IndexConfig) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["description"]; found {
		err = json.Unmarshal(raw, &t.Description)
		if err != nil {
			return fmt.Errorf("error reading 'description': %w", err)
		}
	}

	if raw, found := object["enrichments"]; found {
		err = json.Unmarshal(raw, &t.Enrichments)
		if err != nil {
			return fmt.Errorf("error reading 'enrichments': %w", err)
		}
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &t.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &t.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
	}

	if raw, found := object["version"]; found {
		err = json.Unmarshal(raw, &t.Version)
		if err != nil {
			return fmt.Errorf("error reading 'version': %w", err)
		}
	}

	return err
}

// AsFullTextIndexStats returns the union data inside the IndexStats as a FullTextIndexStats
func (t IndexStats) AsFullTextIndexStats() (FullTextIndexStats, error) {
	var body FullTextIndexStats
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFullTextIndexStats overwrites any union data inside the IndexStats as the provided FullTextIndexStats
func (t *IndexStats) FromFullTextIndexStats(v FullTextIndexStats) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFullTextIndexStats performs a merge with any union data inside the IndexStats, using the provided FullTextIndexStats
func (t *IndexStats) MergeFullTextIndexStats(v FullTextIndexStats) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbeddingsIndexStats returns the union data inside the IndexStats as a EmbeddingsIndexStats
func (t IndexStats) AsEmbeddingsIndexStats() (EmbeddingsIndexStats, error) {
	var body EmbeddingsIndexStats
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbeddingsIndexStats overwrites any union data inside the IndexStats as the provided EmbeddingsIndexStats
func (t *IndexStats) FromEmbeddingsIndexStats(v EmbeddingsIndexStats) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbeddingsIndexStats performs a merge with any union data inside the IndexStats, using the provided EmbeddingsIndexStats
func (t *IndexStats) MergeEmbeddingsIndexStats(v EmbeddingsIndexStats) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGraphIndexStats returns the union data inside the IndexStats as a GraphIndexStats
func (t IndexStats) AsGraphIndexStats() (GraphIndexStats, error) {
	var body GraphIndexStats
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGraphIndexStats overwrites any union data inside the IndexStats as the provided GraphIndexStats
func (t *IndexStats) FromGraphIndexStats(v GraphIndexStats) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGraphIndexStats performs a merge with any union data inside the IndexStats, using the provided GraphIndexStats
func (t *IndexStats) MergeGraphIndexStats(v GraphIndexStats) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t IndexStats) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *IndexStats) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y961YjOZYv/ir6u2dWAmMHBjKrqz2r1gxFkll0J5c/kFXTp1zLyBGyrSZCipIUgIvF",
	"WvMI58O8xnmpeZKztHWJu7Gxya7pkx+6mnRICsXW1ta+/vTYCXmSckaYkp3BY0eGM5Jg+POQqUk8v56n",
	"RP+LsCzpDH7uSIJFOBthOZrzbKT0027nlszvuYg63Y4iD6rT7cxUEne6HZYlRNCw0+1EWBFFE914zHlM",
	"MOt0OzFlt51uZ0p4yilT5k85wzAmScYkiiib6i4xH3d+6XbgdYOOVEL//tTtvKdSYRaSU6L0ewaPnYhM",
	"cBarzqAT74/krxkWRM8rIjIUNFWUs87Ad0MJ9EMTLpCaEXRHQsUFoiwiD2grIkwSxFk83w7QZ0nQsBNy",
	"SRkZdqBHwiMSS6QEpoxE6J6qGTINkKQJjbGgao62SDAN0NGnk4suOk8JOzzxo1HGiBilgkdZqBYMGnGF",
	"bKvCyG6U/DuHHT1p+P7t1sGOszCmEcEMRZYKgaa2Xd4S0Urz63Tt19cXott56E15T//Yk7c07XEgNI57",
	"sK5EdAZKZOSp2zmOpsSsUnE5DpHuGnXRPaHTmSIRCjljJNSP0Zioe0IYiniYJcCm3U4qeEqEogQYNRQE",
	"KxKNsKoP/dOMMFhaEk0JuscS2dadbmfCRaL7AHP2LHe+9MsSonCEFdZTwFFETbOLwkR1wyojntvhzPT8",
	"GH4afPw3AqRfdhqSZyJsIPH3WJJv3vYIC3lEImSaeZqiWzIvEmQ8V+vQQmExJerZSZhmrzYJK7jKU9AM",
	"CNxm9mVX72mqiBx29J92c40UN//GmZpxQaLReD7sbK8xmSyNVmDRGEuFbJdN86nZYi2EMQ93Q84mNCJa",
	"QG71gz5SHO0F/e3SVHg2jgvzYFkyJmLpeTx1O4L8mlEtZ/ShYrjWc44d1s/2l5dvCP1d76kwwqR8QPBM",
	"NZwMtiniE1gQqb/+14yI+WDIeohnaoDOMzXllE1tg4ngCSwg4xHRjSgboBMW8iRvo3ipxZir2QB9z9VM",
	"j2gGwyxCtNRryAqS2cyWMjhB1WxdKazP9SO9ztM6L5jfM4GBEPogwUimJKQTGhoutctTlsM4jvn9SJJ4",
	"Moo5T2WJ2k3S76cZUTMiNHGgb5GeGGilH1Glh8xZLdcflv3eCSVxVP/M907wwHN95ihMmaa+lUwwg1sy",
	"35LmOMWZ4glWjghwklDOgiG7ytKUCyWRWQu0JSmbxsQOtI10ZyHwXHOVaSLRVpLFiqa+ldwOhgyEAU+o",
	"Uvo8NPRIMqnQmGgV4I5qwUke0piGVMVzdEcxGkGzALjlxccXfhgVRYNdtb3qkp3iB5pkiVkvPZVcbGxQ",
	"PHQ7CWVN8+nX5kPZF5kPw8nC00Q/d0fKGzhR3nTRm/w8eVM/PQoycFTUHsqvuLRNvHJguFVanZXK0oak",
	"iiSw72qvsj8AF8K/ecpjPp2XReJU4HRWE4rXtq3eIhKUSdXwepCPShAyQFeG+1Ms9PZKiYCt1EWMo3Ae",
	"xlqy9RC8a4DOeGFYmSuwJeGnh9XmAUzvxZKvcurAmtaOFi0fnekhT7Ql0CYmPzM6oUZZrYhLb7tIY0sQ",
	"GSDY2TLFQhJEtU6eka5VRiXIV3hStkCuLj4dvj9GlN0RodVi+Hm7NtYEx5LklCsOa2yY8qg/nF39tB2g",
	"D1zYx3aOXRTRhDCpvyLEWvN2kgjRCcLMfhYR+p3uo0mE/vs//wtRhe5pHOs+Wkr2IqJIqEgU1LX1WcZu",
	"R5L+RsqSpr//tsp3Z7BLtcz0yj8wU8ql0lI2plIhGA9tWWqAtdYB+aHlQmfwzVu/wJoVpivtehhb//ux",
	"80+CTDqDzh92c3t51xrLuzEdj6ApZdMRTwnDKR0dmb6WeZ66HU/cOif9aNYnJ/+kujYBOiqvyL1mgfY1",
	"2SqtAhwTqeBjsh2gkynTOi28w/GQfUmRcHtr0M1ZlqPE2+WL6Fex4p+c8b8c5fPN5ml/bLvnxG9RAT7A",
	"ya84Ig9K4FAVd65WQ9YyCJOR5sZGhd+pPRkQv5eQhIs5MC+Sigs8JSX3wzrKz6onqWmL1EwQOeNxiU+s",
	"HCFMCUpkbdP543YSc6zWOG3NuKX5gozrNppOzZLUCs/tivS0wvNZkWmkZElyBussg8ySBAv623I8jann",
	"5Y+EEYEVLzCzIkkaY9WgkPyAWRSTMRYSuUawflMziBaaqeBJqmSArghBM6VSOdjdnfl+f5NByJPdaUYj",
	"smudSEIzqVlcre7qc/kBJ2msKfEDiWPeRY+Pf6ATtEV+RWdaExp2/sxnbNjZfnrSf2A1w+zxkcSSPD09",
	"Puom+v936eTp6f9Df+UZwoKgx8fDKXl6QnOi58/jKFjH/Ofp6LZywtSMPfMIMX/OCCKzWIG5JojKBDPG",
	"iHF6th8yL5eVT8+rH1cKK1lfav0zlYqGRhX0R0GudXgR4vbvdu0wHuPwdkLjeASK4ygVPCRSkgZJec0V",
	"jhE0Q74ZijIwd9wwRRmQUaa+edtZ4xTxk0sFnwoiZZNHyTRBrgnCeguDKmaWLvdfbNQeiKi8HWUSN7kz",
	"r+hvRDOTNvjNQlCGxnNF5GbpQ4TgosEo0T+jhEg9O625Sc1AKORZHCHGwZQU+qQld+BeeukOE2Sc0Rg8",
	"9O1HnCcBYYKGM6unZEIbBvHcM45584uFq9LMOTJaTAPv5nqkEedyN9cnKcsnudnlMZPSho9s20654IFm",
	"pclUFYCNz0wRkchFxMoY/TUjCNrlUysepu0awPqTvMfxSLNHzKeLJlm0DFgErjPgNHDs2En/dPhpk3Nr",
	"ktkfsji+Jg+qYjCWpe3SKqHRB3tFffDl2+PZ6foD5qVnQ9Nq2M3oTgi75ZEVGl/8oLhw5wOfIM6Mw9XO",
	"RR8ZE638a8Pr537Q7+rT4pevx8Xf87gonRKFrl/ikHj9w6FpS34UOJ0t9DfV3fLgD7MUa3TJk2hKIEjf",
	"sCU+UalclAN6SxMgVjNCRdmpJYuuxUW2SyWy0OB3TPCD8VePUiJGjtT12TlHc35EGmd4SkQeMdzqo+9Q",
	"xmKaUEWi7XV2x+/GPssngihLM4UUeVDBkH2WROZfbp3AuDDOHRYUj2OIBFxpIyzFShHBdKPcpDCz9L1M",
	"1CA35x4fFVUxeXoassfHkDNFmHp66qzhcV3A6MtZNgUmX8N+Oavw0e/sfLq0Z9GXtmPKAqI5ceHxeVo8",
	"dWuyKmOqvGuLcYoaU3w9nPThBMR63lhwHAxTciGb1z+cznhErkgMJlRDNJVMKCMSzfi9ZlQJDfV6CbVb",
	"iKcW9/SvGRGU1BN6bsm8gQrHNupp3P7WZkLQdunA1/ILAmfKMseS+aj8i302gCATIggLSeTcSuvIEP2a",
	"0YTG6vkDSq/TB9MSWFu/ewTt61LHTtHMH5xcBReYNkWwNF8I0b1h558mWaxNxwc9IjQcdlAPWuonPf2k",
	"MpLtWHDT2wcB7KYRwwnxg1h/a2UuxgnnMhCg2xrR7qeXZ5PAPvj/MyLmTRsgjLGW2HekwN9zE10gYaYI",
	"whNFRE6o3dLXNmwEc8o3iSQazpwOUPFVFvPkNr4rKAvjLCKj/CX1kApRem5ZHBcU6XzP17bC6rLSTaJF",
	"Wp6Yx+a8iYjCNDYTIDicATOv93LHs/U3fyyo4yYhwKVumG/Xw6+TRZZigZ/XwXMevTDtoSeogg12sdUR",
	"pSKpoZLTGi3zVvIKFr3YjnWlSLoGixleHuGYYklaed8+rjJ/efJbJEnVHH2HcBxvv8Z2gNMtd/E9uyql",
	"E9QnSq4zgE1yXI4fIJe7mgXhVjjn6182IR8vPK9WGU7ghCgiikJBCXxHhMQxJMGlWM0mlFmVqppjNuWC",
	"qlnStvt8A2CNjPmknBRPicDs9k0XvbE5xYxI+WadDelfNsq35vLJvxVSeGUu/4Y1EoEjEmVaX8KKtPmg",
	"L0nC7wjy7awqs+VXY624c1RMunzOZ5BnaNZskmrAXus1aDwvuC1e86DTvLjgjNGPi7HRTRHvdpEBC3PS",
	"7K03Cdq67ckZF4pI1YMna7lBEvwwikiqZu2qb75ZTcM13+YUgiVUbacONhL5ZW9vS4d2L/9S+Y1NmRiv",
	"lsv4UlPCzGWUaBXqeV1g9hM0P9WtN6NzX8L6Nwkywxd8gnBR9a6dHglWoGe3qkG2AdqqakKUyO0V9aBT",
	"PdYaIqhVakvIWYCnS84ISGg6nsFyvHhSLfLQTspIJkc8d4i/hIDrEE5x3iA/gYOsJaYlta2j8Nvqea9J",
	"Z9DRnYL31iu+qnvnecfOBvwEm9MIzZw3ogxeN9bi6F/1Vzcby6XsXxD3+iemZcqYC00jd+zBId3pdm5H",
	"pV/AnLZ2zxrFEtW901C9Bo4oykofki9lWQS1HK6+ItG4OrRdUTFVX56F2WBDuTo732Sjwc5CUGd5bfhD",
	"0WOAtugE1ZwN3+l+22soxS0egyNTbWjLByTaguTakpvBv3rpMNgaAuyWzBdUq5gyuZf7EJrY7y9kDg5l",
	"0GcLLAhlS1Q6Vty4mq3f1+bHOXZe7mUn9dyRstaqVGSkXoQ1ROOKcV7MfPyLM3I+6Qx+Xvy5TekoT91n",
	"mLax6uG5XrWw9dMvdZFX+LrHtgrYws/lbAioi1MSpZlIuSRNdTR5ys+iOHeeF8RwYnxHOE1jOHRyV+WY",
	"TEzCa0QeKJsG6Dgf3JdiRRDsiBBWMFGFxzFBMbkjcSk79ueOJAlmioamPgBOLYjvAvdsfDs1uyUhI7dI",
	"0iYSLqM3wDIblaHb0SdytaSylmH7o2lUSW/RxNH0NOnEyKbhwoL0g7UCV7XyHjtYU5XPasm1a+w/844V",
	"t99ynaqx9KfWD21RwWa2fq24QEU8AB/uKSIyyPZSrKdu55SI6QqlpUZRQpMMGAVO3pAnY1OI6UskbUCo",
	"UKhSljECs9sR1JHhpmySy8sP6Ba552hrb3fr9l90n+3tMv990w+ABTenDUklsCKm0G7RUgLZrlxjb20v",
	"F5dvmWUtLK9FQWR9ClJrEiRC43khZBGgG7/kN94tWQvtQYd/HTLPEoUhzJYpFk5ASspnZgN4LnmUSGQF",
	"h01sCNBhmsbmOVRII71sWvxfXn2oJKo8Fjhz0A8Ouh3IW8mLgTqDvaZA9j1lEb8vlJ+VuOTqA2KapDH9",
	"zTCoaY508zKf3EB8+CZ4vSqAMj+UqjSFmNRqNKE5cswGS5Bvo1IcVS+oP5bsemoi55Fd82MwZEJMBuiS",
	"hDQVPMQxusTsFn0wO7VnxycSyZALIlEmzbt8c73B9EySLMZDJiQMFpsI6ZXuk4/lyJ6PNp6jhLLdBD9A",
	"WhplCLvl0LP1L/eYIabfkE0wjfkdEQPAR6l+FaKTvFDC511pWYRpXK64N2QWUv/XDdoo8QpesjaHtXGt",
	"22SjatDDEI48UFPWaAzIVGgOo3eNYWE95igVZEIfFvnIb4keB1q93GKwb/vVRb2XN+m+1xpRbthPiqTY",
	"klorkXOm8APC0gmW4stebumt4W28sPZRPY8S/vgyxka3ExM2NRNZK2OkQbU5FxERJKpn0aCtcQmf5VUi",
	"pibPKfd8bxBQZJ0Vd7hE1Xz95TB91gfrWR9pZ12YnPXxZH4nS/mBsuiS/JoRqeor+tpByTpKyqtEJ2+r",
	"IB2JCVd1Bnv9/oZquCuRwEIRpX/Zu02+a/OMVI2ybVCnb0HZujKwWk6kNknUTWNqXZehajb5yhXDfXrj",
	"VUJ+izCeftnENnfxwPIu90GqLxFtgpeNJjxj0VrHtQVWVDQho0S+Fr/+/Q6a9blpXXYpDFcyp7SUmPFU",
	"1myqQ59L5CKayIY0IRvW9RugKxt3Mm3GczTjKQohBX5rLAiO1Kw3oUI6+7mLKIBwOOtFbsN4XgoOkJ6z",
	"Kcex0tYDQLqKHWfEb0klOJvqtxdQE8MZpmzbzbJhVJtjILOkPmLM781wUiHBMwWBD2cVFahVENslWbtG",
	"tK2SN9AUqJ/ZiQJmWm2FmhcIUirob6SaRF8lkG/XQJfqEkGKiG7bsjIlW7JItZxQJRKuRzVFBNNKC2Rf",
	"NgNVFWGWwJxOC8mf9UDli1Ul/U2zKv5bK5JYviK6D9oaZv3+AdlD3/mCpp4xhmB5tzuvonI8m/xjDdON",
	"5wAtQSe7U6t00hQyawTz3BxhVstMeg3CtKjZx3mhouLOfUIKWb5s/go263oHT54I1JA3YEECIenIoR6W",
	"Mpjr9W5Gui10Cq+YCFRl/RTSqGKKgcomISqq5CKsTInmqLOJ8LqFjExFE5XmpV8ysrvmAjfL3EOQq0bS",
	"Go/f4rUFmrdE7zzaHuj5W4JAaQ4sEnh652EMtQ5GCK+j9BPrCVkiwc0fNy/PKVyH9iJjTQ7XeoQpFRl4",
	"wStFRdpQihBnxnGMfs1wTNU8GLIfSJxK563kmUIxv+8JEpM7yNBx/SlDl4cfUUpTEoMnejx3S8CmQ2ZG",
	"neJUIgBzu6OmlNo64XnqBjKRjWqi4sMIBhhNcTpKiQgbi6SvzDAqEyU3/71DFJ7i1ONn69Mfct/uiHeV",
	"k4eQkEga1rJvwVMfDQRnnSWPwGxK0FaCHxCoTNvBkL2Hr5Vo2CHxmN/LYUcTxbSPqGa9cWa+WZApFlFs",
	"ARhMCxnimARD9oELZOM6XXTQD/pIKn3CGYQ7+AaZYibRQf+f3cwKc6oEhg76mz6i8VjyOFPELEhTTbeI",
	"cn0aJubB0wLkclNB63ahDRLze0P0OxxnZMiwIIg8QL5RVCEWh+LTnIeVZi9Z+ep+0N/b9Hcb/oN91JQw",
	"RFKDVydqH4iMCvcd8lyMdlBlxOq694N36JaQVPrxdGNQ8RWKCZYKzXA8yTnTbZ9gyFzU0FXXQUjJdq/R",
	"6d0myWT9GyMIUxtoiedB68411fS35qWWM6wQTlOChd5APujtwqRbEAz1QdghwywqV0qaKwUmWQwCj7JQ",
	"ECwN2hsJKRBkrJdKTxekE54KAjkYOb4+nUAxqHIF1ThGCVEzHpWhhV8AfaeiUUTuRn5XtLBTkZMoQ2dI",
	"KswivbsK0tPtHYISgq2wqTLTXtCvMFMTc+ruPbS3I1UUkTuDsOAoKF3+B471CRBTIvLjVa+RzVqQRFW3",
	"4t4mWawpMHzFhaogmpd9kEIhb7w59G6jaULFaACIidp6IDI0mEldi4f4HcLupwawQ/vuD81Qml6dlXoC",
	"BlLb3F7h5hJ0mjLDnt8w5S9aZ/otKKDXM0saU7WpuPmG8bwOQFj1apoRm7Jurl14t61qwRPMZcBovaAS",
	"Gl43fdggpOT/Xqte5mV5vT5vFcCrt+gExRyXPdMr636NCbKV2yVe6VqJZkvmivyaQR09n5hYaku6aimv",
	"GTzH9cTixTN9nVzb4vwLIPwv+4BXzIyuho9rIF+NLlIcczaFM8NWCrzSNRaG08wWXSO8kUuOLG6sANI/",
	"N1XPNkiLxiLQBVcy/EglVXmlvFHxuKkQ+H2Wghp2Hc/drS55ybfxFW1/ofLQRSdYa7mo1yTWAkRoDtUe",
	"dJcr4NwkilatoNOHjftts6lD7m54Pqtca/EFPL6rYHG/6nTW8L1UINAOmZoJntKwioW2hHNGS2Xf3+fj",
	"3RF0eOIuPBFo6yjGev+Y+8y2gyEbssOLEwh431GMbvQsbsn8xqpxXKCbw7PrHy7PL06ORocXJ6O/HP/1",
	"BhF2RwVnoBW44AKMtbNzbNR3dApvGOzsoBBe2ZOcMaJ6b3vvevv9/Xf9P+3/qQQbblrxNJO+zd5ef88/",
	"Oei9680wvc30o7d7/f1988L3PITXOATuiIcywI4QgMFNGPy6i8c8Uz0z3q4hwS6/I+KOkvtqVqxmeMVv",
	"CZOdwdv+n77pdqBDZ9Bp/x5zbACltSh0c+gYIDu9HpkA2/mPTzWfpaF7s0qdL6tdqwCdTAC1y91kA4p7",
	"LAEGWAuA2po1L1mTUlT88OcryU1L/UrLccTBaQkiU84kCRpBziwxi9HjhXRtsDOyODZ8jE7eO3dGTinz",
	"xGIv+ftkWl/xJn9aY8E322Wk9oUTrR+MxaVv2MZK8FgigVnEE0YkuEML2bRb/aDf2wv62wH6gU5nRBhP",
	"l0QJviXapE4zZZDlzRBB0/UBeVZTIbbVb0hyL4C9V+6t6d0iqQkAvhCHtxEg8MFIs+V9UrTiKfoLMkKv",
	"gBgks7EE9VgZtmnmDD2FtAm1IYxJJhsmUSTRoRbtzMg9rW3ntF+PLpmIm7fm58tPdd7Tu5SwCIQ92nLC",
	"v6tZMU/Vp2YH+1z+7dIMM0GfNZnNHmoymSvHyvckEjy8femh8tMVsiO0HCsg+i/MPyTCYajZWHF3aybw",
	"hadOF50ShbvoMMG/cdZFR3xGBOmiUyqV0FTCLDK+Wtl6pBTEe+te7N3tDfpduO0piGOc4IPeQe+P/XGP",
	"MqlEFirbAMM8AsbvcC8VHH5ddLLcy8B20UfL2BBmN8aKSLWbSSLMjQ/m23vS3GdGomCmkrglQLGOuH1W",
	"vFY51i2lF50VGbk0baticemOzRd4TRudcNeWAc1zz5PuI6Q+vMPmg2xjgveLStTNyMR15vxSKWM28guF",
	"jOncrrbyJNFyYRW99ej8h+PL45cqreaFPdFL40yWFFX3JP8T9/oHwOIL5EYIHwgyw+NZ7oYzrFZQPEtz",
	"KiubZvi1NU27DMuqmWUSL69jToRxk81Hmndi1TCbC/PAMIgmB/KdNrU1/36abnUh6wvBCqXGdlGKGm1F",
	"Ia2OVyN4KojUHLcKvV2fjUnCr4rw/3RF+KVHQ8OhgOPYln8vVwheHZHzaUzqkPErDfIjEYo8rDnIOSiX",
	"aw5yTURC1brfY27F38AglzxTRKw5UIvVseIorS6xFcdp1k6eftHDVIoe/Kn6susLLlz/6nbxA//y9Est",
	"Qx5lrZeg4kVml3+tdFeNFi6vhLBxmEnFE3ddna2RddcWyABduz/1wTJkhZsVXFEpi5C1Y+BY55lE44zG",
	"qkcZmpE4dcCbRqwodwc3xCkTzGiaxe5+Z60fuReiq7lUJBns7AxZD+3sXMHrdnYGqH67A9wF/cwle9tm",
	"mCMcziib6nHyT8OC5LdO4zieoxBDPqYhkaP5OCbo+vqT1/cG6B1KKMsUkW50zhR5UOXRBQkJSFrnlwpN",
	"K0OCFMMVb/bm8qlbMEOM7x0hfzCEBGoM2V6AdnZkKLLxDyqJd3ZQD1mUUcM1u1LN4cLrqQRau2s3w5hg",
	"BjddmFPoh+vTT0OGELq5ucnJBr88PvrxkTZOR/6WCtcB/t+9WKIbyPgIzQRM9scNvNw90FNyv+uZ2f6H",
	"USQRI/cmuc8kF41jbb4RA18i0VbaRRG966LZXm/2TRfFtIuICoNtPwWVCSZRGmNqPw8WDnQUcQe5XjjC",
	"YxpTNbd9ClkoQBXNQvdkjOxnOnwad00IcKgm/b4mPfkVaH5skxm1qp9iQaXdkiFnLmwvW8nrLnKUCqtM",
	"omEHh3oLw2WOh/Cnvbmx0v7ftVUz7IBnCMfQ/Mr8baybYq98lT7DDajoBsZ5eroxJJbV6aKYT2lo+xzB",
	"V+lFYXOk7rlTqUBTsZ+uSXKgSZKQiGKgykfC/kIVirgyQgXBI5dZcmeybCH5KuERjh3FWwllumci/o4m",
	"eEreY4U/X554uuSP1YzKANqMMhE3NBh2nIyw2jGIB+gR/C2dDjuNfeSB7mAddrvjLLwlynZKWVunCY3J",
	"YHd3N8Vqtqt4w0tgbeCvnZ0r5wcCj+GVPkKI2euwEDdaUAxuUA+Z5Avkky+0APl8eSKdf8a0hJft/i0l",
	"0381ZYrdIAhu3G650UQY7O7eoF3zt4R/9NBPZKzfb9O48lv43ZaAyK9Pz3Kj2S/VA3wCOAr9gwTZbYAq",
	"XUOgo252ddCDDaOoFqj+Il5zPgxswyrBtfm+7Ql26Cd3ZCd3Ye6koWya021n50RTQmpx/J7fM5MR09Um",
	"Gf2NRJBkwQiJSASWu7tzT/GcsH6ki/cfpBHrD8rJUwKuBFNxlupvEISZqn8sESyC764lre5+CYJIy+by",
	"OObcPeW/0TjGthV1G8zwCAkzoYWNM4bcd7ovM8dYKri9jHo89ysnXV+X14q2JNGmY1GZ8LdUbA+caLa3",
	"/c+4VOh+RhWJqVT24YWgd/qYPrkwsgTO4FSQOxDZV1eXHxBWCoe30jGemyjgvCCIO8vCWbrX759+X2ur",
	"aEJ4Vmp40PdDwvoWLvSuDbrff/tt+tA1t6XbdXdsdEXIwLthMFOTeB5QboKBJT3rD45+vV7ItVwasrdw",
	"DMA2vOacmeMA/ml4hzJ0fX5+ZpUetHWtLbneuaCE6bU5B1sInXEDzrXdKvzyV0ByUGAuo/Aip/kxMpVc",
	"p1jcEvGdSdqjLCJMfff2ua4RMQkB4rthZzhUjeLqpxlWiEr4wn+zXAhfSyXC5jAMVRfNsgSznnAcb0kR",
	"EUmnzF6MrpUfyLcGnztopUA+xdGnT6cygKFPvItJop2dg37vm/4/Wy+EIFEG0sg45fRxBfv3z1fnZ5pj",
	"oeyHMoUNQM+MTmd6YBhWtxdkZjkHh2EmcDgP/Ff+hczRBwJWcUEWH5mvc9qv2bc3AwPidEvmPTgkUYqp",
	"8BqOEHhu1wQlsChygG60DvTzHw5+GSBMu7ZgNYndgX2Nx1mMndYMo2sbgIvEUMhTzL3lPFVQJ2kI++nT",
	"qTb9pdO2My2YINEX8pKhx6mljDQrVVaSLBG+J4xMqJJFofqJ3xMBXsCQSyWt+hllIdBeLwtcwQipvxLF",
	"0FrPx/fwI33AUqt7zkVmhvpk4kPOn2YvG/N9TrVaFjo9G/XQB2o9Ozm4oE1tNpMxMsF/kUFCLJ6uxd1y",
	"g7bGnMfbA62Xoj9YWB/AMIRVhGpjiWJ6S9CNXr2bgrCBFD03qtlwN2iLMrU9QCfwTyNpZYpDvTB6oRiR",
	"cI6AQChJLj+S35I3UIVM2XR7gMyV+pKkGMwF45mzPANTLY7FOCMQYEQ3dlffuA4yP1Sdn9t4yxyBnA4J",
	"wF/6O5RJ/wNwZ45+NPnxV8C/0BBnasbFAP0ZM4Lec3MGNjM7PHLwL+bUQYgYZXSA9u0P+miVA/T2Xb8m",
	"idzV4qZIaLCz4+WQNqZcMLWwh3y6qjmqDaQaFBhZ9Ox8//vzsMArMPqVRR/BZpruBJlSNcvGoFIqzlnP",
	"vBX+tr0/cnRSAmVs7Izj9JbIW8p2p9x0LpnFdpWcKainXjJSbDZ4/p3+K4ascsJ870qz1IzIwv7pOnlr",
	"pbmVknfOHJoP9JsfH/8A/krfTZ8UPg358dGo49HT00C3za1J+L1gTeqnu3ok848fcUwLacUn7+UANbyq",
	"MP7j4x8yBnU8/x5jqZ6euujxcdf8BPffu8Et5xwV7J3cKVEnj7G5jCo7MrbM05P1Smj7uPzA211Q4SAQ",
	"IHLrdlCG6D5Uj2iFl/7J+gsGOTULD3uWiOaWSP8V/kX2c05zU8oaXMABoH82LPohw/H8N2JyjaERvL1i",
	"ZTkLasg+8DCTSPPq4+NE/z3CguDC+68qZzcoFo0EBbpcCA4mg35pQQfJJBEjqzqBprJf1mJMLh2kEsQE",
	"S4Jw8TtSM2jgJ7Wzc8SThDMwfI+wtPtFHyB6x2xduuKb3mE2TYxS9tGHE7a1qv7BSA1/72HlfEEhNZtY",
	"Wv9UcRPq/kfgbNGKv9fDwVfmyOW2LbEDGOT8o1irRE66FOZh5ZPFlbAyE2TamCh9ioalnmbMnDf0SC4/",
	"1rDGLs4iynf1PueA/2xcgKajtrLtm5V1lx0ZA6lJVxNFq8Z6rojURhkOFQ098aH+yDsXkQSIWgNxmMbk",
	"wXgfoPZI2yiUAXCw/SCkWUUPolc0jAkW3RzM+K5YWQI97T7SHYy/ECXU6JpW0Z0KHJJJFsdztKWKTk40",
	"7Nimt2T+3W9E8GHHFJ2aIK8e8lp/Xd4L1kQQExNTxhULtLFepDQ/MjOAVm6J6GprJY/oTlPVexvslUO5",
	"4FCmTaHcBYGVi4LTuh5NbAmrF2KJFl1jShLK9LvBUAaYXghv6D/ctPQfAGYiOt2OzX/pdEvpjoVoNMQ1",
	"OvqTw9tGzMelAjtLZhGYzq1ZBB/h67Zbg/7m63v7wbveJMZyVgz7F56lgvt/HwR9/e/mwD+mwRRmFETk",
	"btf2wCk1BqjJZWhICVoYobef6CL0TcHemJv9tHCAo5hnEXJNffZPJnshYUrg2KY9bjw/dOkoeXU1no2T",
	"F5a9MfuzOuCb8m+p4IVf7MJWk5waJtUQbOda1R/RaIkVsI3RyftXS2LafzZ0v/8Pl8S0XMpmYTM5b+Tr",
	"ZWE2B4qXlGym86JAoG3h/SgxuGq1VU6Zu5zWgDjQOxzOTZrlZBJTRuAUaBOKJncyOBj8sT/uol/vCdsP",
	"3g3+uD/WhzNJJSG3PbFnniYmh3Pwx3FX97vDg4O342bZaM4VMIdiOhZYzH8PyZFFcWIJ2ihKikTRQqNA",
	"Fv1PTxit0YjBwcG4KkeKA/yO971xzTZANVxfX3injvPgAmYFCTmLTATJEhCcQjiOZRn4+93bPtr6k4+u",
	"Blp3FaD3674xFlNXpgLQIjG/RzMsontsUlgWQDT9AwusAkm/gMBqTCdZVmBB50UCq1EDMwpxSfEyP/U0",
	"7bqIH3QRfwv/aJYrWl/X5AiMvgoCZg11y37GInVr3WRGvU/1hlhtu/b2XyGjcXndzBsuz8hQQ75mdcyM",
	"8Sb/E5ZV/9uucE358m/dcILjBpfg96Ow/d5EV76Tvozoak5iW0F8mQEW6lx5K693YZ/JpT/VZ0JoOQch",
	"G9u/FoOf4DiGvGptWxvAnecy3M8vjs8uzz9fH18uleUOYhaZW68pZ9Zj81kSdAOEvSljnJhNa3fr0Nr/",
	"u3YPDjv6N2/z77aXfAw72+XXyBsbaYGUscpXQ5jLE1WBP8xqAZQhLrQdnzFFY8QZQTILAXer7Tgpz7mL",
	"lplvFxmbfbdq6nWHLCEK9+AI3oX/9g6Cck1Ri67rPSYBtsY/Tqn+X69cC7ArCYt6+q+ecZjpdeoJA8K+",
	"fKFA+bPr3iXvvVmvWKCwUL5g4AgzhGPJ0ZggSRSwbp1Nv1ylwO/ocF25XKCEK1LckzQiTGkZI/xhWl7y",
	"N9sBOqaAd2Z6cOF2kbt4zZV0lE/YGufU3T8wTAMID2xpPqlNUTbu86C+zSE4YnvbrT5k9b2+/JeVN8zP",
	"9Y9bRhx0up0WebDCxXP/kArKJsowNq7HfJEaiOe0j5Zs/iVVD9t7kd7hmlCJDiGr6U0hI/v0kyuLNJZ0",
	"gx8IclqG7Pzs7D/Qpd5iCUEfc01dBqWMHEhkK7BAWXEZMrMRIypDfkfEPC9/sef9rk95lrs3NkuUi3mr",
	"EcgZexBmVrsfSaKP2R5MdcukNGfTKWXTDzgk22aIUg6PS1LMvxbmyzgiD8APMZxWEUkJiwgLbXSugRaQ",
	"BTuZ0JDqY+ro4vPux4vP+cXXutdhpngv/3In/mzN8+Lvh7eCUlxMltSHv41Zt9iqyyjbjkFW07a7f1+H",
	"myeTUz0TnBbqyItkfNT9nnZzYlYsxTYW+kd1tRXX+6uv7bXK2JrrxZYQ66WIjxkFlZ1jlvpbhCkiUkEl",
	"6U0FjogJVn6WRJo7HW24zmVFHQkCihbWfQ/fH20bEy5TM/1raO+FPWHo49FFUemWQ7ZlZnOZsS76+Jfj",
	"LuQ9ZoqgYzaljGzb9BGZS/oAffDnSUTuukhkbMhupiEMpF9ajOb3XG5WzKeU3QTo0pBcopPDUyR4TNCN",
	"/q/cxdQ77TJJxM0Xi8/CxF2INuTJrol697SS6Jem50y2mGDBim7Egi2Wh1w7hQhqp7vASGuIJBYDh51k",
	"3puGac/+VjbifHT+WQMuzBlk1Iy4CBeBKO51Bhya+1YgwfaWzCHbP0BXREn08fz846fj0eHFxaeTo8Pr",
	"k/Oz0dHl8fvjs+uTw09XzVZdVQ07fH9k0iI561W5colwtvNAlslc/qTSdisgR+Q7T8vJppB3F70hmSZg",
	"755IBXZUk0Vr6XD06fzz+9Gnc0OKssgtDfv7AlpaObCe0629Bn3dwHhbUPx5+l9cnv/5+Oh6eZ/C/zgL",
	"6Gsh+lonONwYT9m0WFM8iedH+mfSWJK+qOw3vZ2OYjrGk/q4MKLNPu/Ua3ybzT1znpopITdkxdyzCZAm",
	"jUlkTOYNjQYcz31G/CwvuALgUZtd3x0y3ULrjh69HGGWG0VOhXSQOtoEBMAqm8M3oQ8k6kn6GxkyYBb6",
	"GxE9c/eDn40ztUJTg4u0WTQjOLJH+mdpsznvZ8T5ny8zZgD5wcPVgzlHJI353JaGynssEpA84Ej+K89Q",
	"xNkbBYVd+RXEuzAJ/2YcCi4N1K503e4xU+aCARxrWZKlLi/RFkSYGXrrmklFcNQ0WXDpm7mGcSYV+PMB",
	"pcO9H+pWiHTlEGYCMGNth/RwGJIYxHiBek63KMw2JUJSCaml0Gw3v3IZCphlk1cYWkpzrWQZkHASz0Fr",
	"eABDQ69OjFN/Cun2vt6gM+hokvh7Bgut+k9PbVtrwaZaHuehNqpdkfLgywAALLX1m0AA8tuu/WUEyyN1",
	"1zd6fu87DAdbY2JWFI4XuOA5GLKfZt7tp9AWuSPMXLOdqvl217W/p3EMp6Hivsh/EE7UAMlsMqGmYN9c",
	"eRD5wd9IZPnCgtfbl+GxfpcfO5MEDcLSSFhY9OJM2tIje2OCZ8XyvQar32m0AuBCG8PloAvdDtDFb4Ln",
	"IIX9gX8/I+BXNnLEJKpLvwGh6MwK1gAB6UzZXREaytAQ50BWZgESknBhM640IXPCQVuzjnZQ4Cdzab8b",
	"jkUtPV4OdbwxZIr6gVURR9bagdOjbMTkucGL5NELhM/iXOjajBvSoBOT0pzP0IrOtvzl5QTW5lWMmtha",
	"xz/oDSJbPQ6KyYxLNfi2/22/zRQ6PLv+8Omvo+vjy9OT6+ORfkebIp4bC41vWMY9WTdmHGMtWOiS0eKi",
	"R2+g4xtzSYnRcIDHKhpNFwGbmyHAJgKd2nokQ7O+3h9Z/ko3tZflNCypPrqVbNEc80ABRtYchQpS8Co6",
	"kx+uzfHu/rIyZzQdRbVgNKpNoBVSUiSJ89OCD91FA6xj1tZrbEma0BjDZpvxe5fIds/FrXQJ+Ufuxd7j",
	"o1UhoOIAXVW10Hye47mNl7mLYm0kpKs1UZiTozcokIdsbu+CgsnDaYqVNkzghgaoSV+0yEUPPkzbkMUF",
	"H/YG6NTIe1DQDBX3e8b3iq6vP0Gr/QG6yFW7CzIex6agRLOfbmECvpMYIMvz6wdoDkASZgJuGTKhVm1E",
	"2ESBmk7opULrxqtqjWuL7dXUyPx4qyhqx/CArBhB86Ewa1XlOnNpc4BXVZtA5iUROjm7/rb3a4aZgj2C",
	"47h3Shn9dNr79E3vbr/I3+OMRTGJvPk1ZNb2GlOGxTxAZ4V4k91nXZcm0fVRaxQ5FATHosVcHYC6rU5i",
	"6+DbtzkeguxCeK6n9YrmaNj/IoJXju7//s//MjsPLuWzR8KYP+jmZxwxovRTB+TrZqafXmSCoI+8EFwD",
	"dww//fQfZZarmx1tcdOGtbfIYS9b/CJc8aKF1+0K3lGz5YtHFxfeUy0X4IQCrCe8qEfYNKZy1rt762GF",
	"FVWY9cxjWKi7/deDF25WvVqmWN7VeR2XQ+LtZLJHsFS9vU7NqzzGKpyNtBRefBuEPiegrQEEmRSNBi+t",
	"tNDlFtoAqZng2XSWZmrjwMYtdHjTRW8WLVYN/b2VnBsGNS46qM1CVKeSr1DDy/Vf6YiR+xHgbj1vCP1k",
	"7R+wcwRNESP3yGB2eT8iZWmmTEKALXz069l0UdhKbroGQWBA+14mByxqaosIeFXw4ApvHAR9byV20V5/",
	"H+S33O7ahqBixZRNMxxD61VhhGGY8uaHhRo5pgA0hpG/diw/3+szbYQVXg9EuMlseClycPG7imZA/RMr",
	"+XMWZt/ARgDOFZ9YdtYcwz22SsGrUbAI6+PbX9wVxOXabPgB/IJ63r8sZ8o0LsZS0MA5k7cHaBpHr8dG",
	"RMZCrCrUPT57X5vKD/welHlTeg2UlCjmbKpFyAwbbSjBDw6jBUr9iyQ9Oz877nQ7V9eHl9edLrzjl/US",
	"wBskSF12vMQh2TCwiVdVhl/GJdkwlomvbWYsY1htaCzITtrcWCbdczPjNeuILxys8Zx54VjW5N7MYI1W",
	"UJO/OkdbbLjTkoQxFtbMN/fCg5SwyqOEUDyc6Q7FYsvgR3QRAEh0ESBIdNHF+w9yuztkzi+tvBuASvYG",
	"kpLq6YimgVZ1pBJzNCcKzk1wdt4okZGbrrPTlCBYycKwWBZhJDGLjLUuCYusoZVjS1bnDPChDnTV+/pc",
	"TIdPHDSfQcN9UAG6LjR8I42OQCWSSr/TRtmpxTkD4yg1nWfEE05bVkDhSYyn6G8ZYEjEsUvTHDLGVa5g",
	"UUOKM64sSKEpFzGpQDgWBEfzPMpvCehwIHPCeL656Q7ZjQ3E+x97+71UkDtK7m+66CaMadrbcX+FMU5v",
	"KngIYDbe3Nz8TXI2ZI9DhtDQqwTDzgANbfrJsNM1D2HC5onkCelNMm1/9vIJ9mwL194/0J00CwyZAZtp",
	"vGt2lfDAghNg87DMrE25dK9shWTOcUUUt/jM2viZ8fsCBA0WZMhKmJXNencZwBk14jcP2XMAzv/vYDN7",
	"4CkscwyZr1DMrwTF/EXxlAFjakOgyl9Rj7+iHn9FPf6KevwV9fgr6vFX1OOvqMdfUY+/oh5/RT3+YqjH",
	"Hma4hIZaR5y9NsuntVTTJIAFBaRirMpPIqzgwTWeFiCH84546mGHLcRwDlr8+FiwyexSlZBfnTuJs/ok",
	"Lwxr6XdCDomeXO5nGJTsv4IDYqRtQd34QtCQDNA/PT6m+q9maOAcE3jhBDx5ahZIw7QKk3kRvHLhZdoQ",
	"M1vo6el7gE12//KmV26thViRKRdzcD2RhGYJWGz//X/+N7ow/3YKcqHzmEfzwix3do4LUaUfbVTJpUXc",
	"fDw+PTk7ySN8PRewKlbsHZ5A2/OL47PD1rbGTV5s+P3hFaTCOdMGzJ+8adFMOLw4kabrp0+Hp4ejH86v",
	"rnU3myAFJrWA/tYUqqXw7O29PXhrcz9OEm1v6d1/IQi8JtNS+Ni7xezu+ivPwDdFoT0iD1RCr0KeqSm2",
	"NhPOb2kGv9fcu7u2tTZOAXQYzl81I0lekkAZmvNMFA4we/nYjKCbgq/OBl4DBIUO4zlcmAWibshyF1uh",
	"BEcqkhp3sKCKSJuQLPM3W7cvJEFbz9aVIqn5/L0AHQmiZY5vY40d45ybEYTTVPBUUN3Ia+HgyvhJv7EK",
	"FF38mAF6RMOOccPA2Gc4sa6YYWeAfg6CwDz0XczDIAh+QU83z/tiYU8Zd+vpHDk56b2rzu0ADbwUBQ93",
	"EPhWhQnrlo/mSBp2kvnIENPkvcOM+8FeF/WDff2fgy7SE9XNn5zXNq+cKMJwn9KpML5BYCTMTM6dzR13",
	"qW6Gfg38ZzCDKjyZZ1WP54X0KjDKoUfO/2mR/xu42MzGxwXKL/4eclZSb3oX5+AwM60flrIpkTbk25B8",
	"A2kkuS/+oCcTHMeNgM9Pz0cxF2c2173Rm0V49qjOq6ZHLxs+XQ3l+fDEIzq/NMujegaslOVRC7T0+3uF",
	"PI+D/h/3TZ7HS8Chc5LVUzkh8aKjJatu39P/7Ha8lOoM9JtrdcalaZb5z7LE0zo41M1lmiXyLp/kUfiW",
	"QhaC+az6THIviU2KyJnBCputP37zbRftvTv4BrY+rIwgIU8SrSxH282pZpuD0Xal71G5CrmLXHWGUTlg",
	"GTRFgyVz31uWdnHKyDK5Ii0DbwrpGm21fHjXJ5uWKdWMRP5ChOf87V1T4OjMKWouO5c2VSja3jA+4bLZ",
	"GqtBQreIPuOzLpxbi7CfgWIgJDMRlxAGi0opYXd637YKRMYTGhbSJ2HfuVS35GGMLUf1DODIVjETDscx",
	"QH7GiU9wbhOcBeRoY3D/W/id/87mU7g6s8r56w7Alhx5ULDr4nEDMNLVeb3pojc1QlWzPhs+pn1rOFHR",
	"8lHd1eGGmyH+cj55SfmPm8wrb7amdKbV4IxfqGdU7ccWPePKJeQ0m4nVHdq6EZuVzmIO6ruDb9zOqzW2",
	"u/M5/aUVaBkC/stoMPK2FwRBIRt1FWV5HRTnVpTKw3WUlQYYj3MDBpFrKI6dcj7agiPo1PoH8pY+AgDq",
	"g9dVBmj/3Tdd9G5v32QSV9SapTFAWkm9Mp5zeWu3jruciALFOKUFnnpWRDXACpeAWEyDNxIUK1j5+qI7",
	"f82Ssqtxlq8vuxrTJ1fHM26RYStiGVfUSFsjENEJOJdVjnO8eRzjVpzfZ+Tedre1Ici87pCVoT5L+q+5",
	"+2JX/+eg8OTb8UqYv5Wk/efkIxcVEbnwS1uRfn9/uL7rSk06Qb72CQpAXc7o9tIi8DlSLiTMc0C8zaMC",
	"1n07i1U1vedmuGEZ05y5vCJqaYt0WR2xtGC6GK9xXn2pZUoxeN7oI26pXkZbFo3hXwrYKi4FthFIFPBa",
	"TFV404tM0a/DeCjU/FYTF03dbxHRpVL2azqvX/zbLCPHUwJf0SOsd7cXvCtZZ61Vpkb7O7UpyYIgk2tU",
	"x3glLufVlUkXkV5XKUfeL0i76pybK5GfNoqS+rooB/uroRy0u3gL5fdVnNTaUrTCpDbQd8MypbG05eWI",
	"mTWt43UAMzcGVfm8c7iLGhL5XQFG8QLP7U1gWOYrtDslqlc+WWq4ATWfcjvM5bPO5pWALV8PxnJdMMov",
	"4ZrWE2oi5L+ivf1ve3tv+99WUo19q6U82f9ACJobcom3ypdXc45/MbTLpeX3AsyhQy2ESsBDdZXdIkta",
	"33kIiWW6m0dpCWpY5g42JLJyf5Q0DWwaIdcI4LRoHFOHfj0m6p4QVnxbMUOs37Il7imL+P3id/8Ebdpf",
	"DcBugEdjRqt8cSmzt99vnsnTakuxeBUuiHCXxTTUK/mVQIdx7O5IBnA3F4zpod+I4Ls8oUqbVRbWNJMW",
	"a4cIFyqR9dWEb3+uRGslJnsqw9I8D5FrF78IkZuSPPukBdzUgti8cNrX5EFVZ61mgsgZj6MWRScC4BTf",
	"Ki/6q6Jp5jCqTVCpS9xLscrEl9rTpkr02S3dBmt81gBnbPv4jRxyJuGGhTvLdjKAgizpM55dlqzD+DSA",
	"fWOesQguW7cYuABXOJ7XIKOIkM2sUMAsql2/4/NRjWA1sGFpTJWpfrMH4XDIhkP2xqaACzwVOJ3J7ZUm",
	"VKjFLwMm1ewBeFyHiE4dhuFy8uYJUBUmvOFKH2acpxcnngdKNijIF4NB67x+BnVS5pXA77+HWVAFR+cJ",
	"5FqVtH2TiWI0qk4/6AcAN2O5tDPoHAT94EAzGlYz2RmwLI6f/m8AAAD//+ZPh6tsFQEA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../../lib/ai/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../../lib/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../../lib/embeddings/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
