//go:build go1.22

// Package embeddings provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package embeddings

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CohereEmbedderConfigInputType.
const (
	CohereEmbedderConfigInputTypeClassification CohereEmbedderConfigInputType = "classification"
	CohereEmbedderConfigInputTypeClustering     CohereEmbedderConfigInputType = "clustering"
	CohereEmbedderConfigInputTypeSearchDocument CohereEmbedderConfigInputType = "search_document"
	CohereEmbedderConfigInputTypeSearchQuery    CohereEmbedderConfigInputType = "search_query"
)

// Defines values for CohereEmbedderConfigTruncate.
const (
	CohereEmbedderConfigTruncateEND   CohereEmbedderConfigTruncate = "END"
	CohereEmbedderConfigTruncateNONE  CohereEmbedderConfigTruncate = "NONE"
	CohereEmbedderConfigTruncateSTART CohereEmbedderConfigTruncate = "START"
)

// Defines values for EmbedderProvider.
const (
	EmbedderProviderAntfly     EmbedderProvider = "antfly"
	EmbedderProviderBedrock    EmbedderProvider = "bedrock"
	EmbedderProviderCohere     EmbedderProvider = "cohere"
	EmbedderProviderGemini     EmbedderProvider = "gemini"
	EmbedderProviderMock       EmbedderProvider = "mock"
	EmbedderProviderOllama     EmbedderProvider = "ollama"
	EmbedderProviderOpenai     EmbedderProvider = "openai"
	EmbedderProviderOpenrouter EmbedderProvider = "openrouter"
	EmbedderProviderTermite    EmbedderProvider = "termite"
	EmbedderProviderVertex     EmbedderProvider = "vertex"
)

// AntflyEmbedderConfig Configuration for the built-in Antfly embedding provider.
//
// Uses an embedded INT8-quantized all-MiniLM-L6-v2 ONNX model bundled directly
// in the binary. No external service, API key, or model download required.
//
// **Model:** all-MiniLM-L6-v2 (384 dimensions, text-only)
//
// **Features:**
// - Zero configuration — works out of the box
// - No network access required
// - Pure Go inference via GoMLX
type AntflyEmbedderConfig = map[string]interface{}

// BedrockEmbedderConfig Configuration for the AWS Bedrock embedding provider.
//
// Uses AWS credentials from environment or IAM roles.
//
// **Example Models:** cohere.embed-english-v4, amazon.titan-embed-text-v2:0
//
// **Docs:** https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html
type BedrockEmbedderConfig struct {
	// BatchSize The batch size for embedding requests to optimize throughput.
	BatchSize *int `json:"batch_size,omitempty"`

	// Model The Bedrock model ID to use (e.g., 'cohere.embed-english-v4', 'amazon.titan-embed-text-v2:0').
	Model string `json:"model"`

	// Region The AWS region for the Bedrock service (e.g., 'us-east-1').
	Region *string `json:"region,omitempty"`

	// StripNewLines Whether to strip new lines from the input text before embedding.
	StripNewLines *bool `json:"strip_new_lines,omitempty"`
}

// CohereEmbedderConfig Configuration for the Cohere embedding provider.
//
// API key via `api_key` field or `COHERE_API_KEY` environment variable.
//
// **Example Models:** embed-english-v3.0 (default, 1024 dims), embed-multilingual-v3.0
//
// **Docs:** https://docs.cohere.com/reference/embed
type CohereEmbedderConfig struct {
	// ApiKey The Cohere API key. Can also be set via COHERE_API_KEY environment variable.
	ApiKey *string `json:"api_key,omitempty"`

	// InputType Specifies the type of input for optimized embeddings.
	InputType *CohereEmbedderConfigInputType `json:"input_type,omitempty"`

	// Model The name of the Cohere embedding model to use.
	Model string `json:"model"`

	// Truncate How to handle inputs longer than the max token length.
	Truncate *CohereEmbedderConfigTruncate `json:"truncate,omitempty"`
}

// CohereEmbedderConfigInputType Specifies the type of input for optimized embeddings.
type CohereEmbedderConfigInputType string

// CohereEmbedderConfigTruncate How to handle inputs longer than the max token length.
type CohereEmbedderConfigTruncate string

// EmbedderConfig defines model for EmbedderConfig.
type EmbedderConfig struct {
	// Multimodal Declare that this model supports non-text content (images, audio, video, PDFs),
	// even if the model isn't in Antfly's built-in model registry yet.
	//
	// When `true`, Antfly treats the model as multimodal and will send binary content
	// (images, audio, etc.) to the provider instead of extracting text. The provider's
	// API is still responsible for accepting the content — this flag just tells Antfly
	// not to strip it.
	//
	// Not needed for models already in the registry (e.g., `multimodalembedding`,
	// `gemini-embedding-2-preview`, `clip-*`, `clipclap`).
	//
	// **Example:**
	// ```json
	// {
	//   "provider": "vertex",
	//   "model": "some-future-multimodal-model",
	//   "multimodal": true
	// }
	// ```
	Multimodal *bool `json:"multimodal,omitempty"`

	// Provider The embedding provider to use.
	Provider EmbedderProvider `json:"provider"`
	union    json.RawMessage
}

// EmbedderProvider The embedding provider to use.
type EmbedderProvider string

// GoogleEmbedderConfig Configuration for the Google AI (Gemini) embedding provider.
//
// API key via `api_key` field or `GEMINI_API_KEY` environment variable.
//
// **Example Models:** gemini-embedding-001 (default, 3072 dims)
//
// **Docs:** https://ai.google.dev/gemini-api/docs/embeddings
type GoogleEmbedderConfig struct {
	// ApiKey The Google API key. Can also be set via GEMINI_API_KEY environment variable.
	ApiKey *string `json:"api_key,omitempty"`

	// Dimension The dimension of the embedding vector (768, 1536, or 3072 recommended).
	Dimension *int `json:"dimension,omitempty"`

	// Location The Google Cloud location (e.g., 'us-central1'). Required for Vertex AI, optional for Gemini API.
	Location *string `json:"location,omitempty"`

	// Model The name of the embedding model to use.
	Model string `json:"model"`

	// ProjectId The Google Cloud project ID (optional for Gemini API, required for Vertex AI).
	ProjectId *string `json:"project_id,omitempty"`

	// Url The URL of the Google API endpoint (optional, uses default if not specified).
	Url *string `json:"url,omitempty"`
}

// OllamaEmbedderConfig Configuration for the Ollama embedding provider.
//
// Local embeddings for privacy and offline use. URL via `url` field or `OLLAMA_HOST` env var.
//
// **Example Models:** nomic-embed-text (768 dims), mxbai-embed-large (1024 dims), all-minilm (384 dims)
//
// **Docs:** https://ollama.com/search?c=embedding
type OllamaEmbedderConfig struct {
	// Model The name of the Ollama model to use (e.g., 'nomic-embed-text', 'mxbai-embed-large').
	Model string `json:"model"`

	// Url The URL of the Ollama API endpoint. Can also be set via OLLAMA_HOST environment variable.
	Url *string `json:"url,omitempty"`
}

// OpenAIEmbedderConfig Configuration for the OpenAI embedding provider.
//
// API key via `api_key` field or `OPENAI_API_KEY` environment variable.
// Supports OpenAI-compatible APIs via `url` field.
//
// **Example Models:** text-embedding-3-small (default, 1536 dims), text-embedding-3-large (3072 dims)
//
// **Docs:** https://platform.openai.com/docs/guides/embeddings
type OpenAIEmbedderConfig struct {
	// ApiKey The OpenAI API key. Can also be set via OPENAI_API_KEY environment variable.
	ApiKey *string `json:"api_key,omitempty"`

	// Dimensions Output dimension for the embedding (uses MRL for dimension reduction). Recommended: 256, 512, 1024, 1536, or 3072.
	Dimensions *int `json:"dimensions,omitempty"`

	// Model The name of the OpenAI model to use.
	Model string `json:"model"`

	// Url The URL of the OpenAI API endpoint. Defaults to OpenAI's API. Can be set via OPENAI_BASE_URL environment variable.
	Url *string `json:"url,omitempty"`
}

// OpenRouterEmbedderConfig Configuration for the OpenRouter embedding provider.
//
// OpenRouter provides a unified API for multiple embedding models from different providers.
// API key via `api_key` field or `OPENROUTER_API_KEY` environment variable.
//
// **Example Models:** openai/text-embedding-3-small (default), openai/text-embedding-3-large,
// google/gemini-embedding-001, qwen/qwen3-embedding-8b
//
// **Docs:** https://openrouter.ai/docs/api/reference/embeddings
type OpenRouterEmbedderConfig struct {
	// ApiKey The OpenRouter API key. Can also be set via OPENROUTER_API_KEY environment variable.
	ApiKey *string `json:"api_key,omitempty"`

	// Dimensions Output dimension for the embedding (if supported by the model).
	Dimensions *int `json:"dimensions,omitempty"`

	// Model The OpenRouter model identifier (e.g., 'openai/text-embedding-3-small', 'google/gemini-embedding-001').
	Model string `json:"model"`
}

// TermiteEmbedderConfig Configuration for the Termite embedding provider.
//
// Termite is Antfly's built-in ML service for local embeddings using ONNX models.
// It provides embedding generation with multi-tier caching (memory + persistent).
//
// **Features:**
// - Local ONNX-based embedding generation
// - L1 memory cache with configurable TTL
// - L2 persistent Pebble database cache
// - Singleflight deduplication for concurrent identical requests
//
// **Example Models:** bge-base-en-v1.5 (768 dims), all-MiniLM-L6-v2 (384 dims)
//
// Models are loaded from the `models/embedders/{name}/` directory.
type TermiteEmbedderConfig struct {
	// ApiUrl The URL of the Termite API endpoint. Can also be set via ANTFLY_TERMITE_URL environment variable.
	ApiUrl *string `json:"api_url,omitempty"`

	// Model The embedding model name (maps to models/embedders/{name}/ directory).
	Model string `json:"model"`
}

// VertexEmbedderConfig Configuration for Google Cloud Vertex AI embedding models (enterprise-grade).
//
// Uses Application Default Credentials (ADC) for authentication. Requires IAM role `roles/aiplatform.user`.
//
// **Example Models:** gemini-embedding-001 (default, 3072 dims), multimodalembedding (images/audio/video)
//
// **Docs:** https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-text-embeddings
type VertexEmbedderConfig struct {
	// CredentialsPath Path to service account JSON key file. Alternative to ADC for non-GCP environments.
	CredentialsPath *string `json:"credentials_path,omitempty"`

	// Dimension The dimension of the embedding vector (768, 1536, or 3072 for gemini-embedding-001; 128-1408 for multimodalembedding).
	Dimension *int `json:"dimension,omitempty"`

	// Location Google Cloud region for Vertex AI API (e.g., 'us-central1', 'europe-west1'). Can also be set via GOOGLE_CLOUD_LOCATION. Defaults to 'us-central1'.
	Location *string `json:"location,omitempty"`

	// Model The name of the Vertex AI embedding model to use.
	Model string `json:"model"`

	// ProjectId Google Cloud project ID. Can also be set via GOOGLE_CLOUD_PROJECT environment variable.
	ProjectId *string `json:"project_id,omitempty"`
}

// AsGoogleEmbedderConfig returns the union data inside the EmbedderConfig as a GoogleEmbedderConfig
func (t EmbedderConfig) AsGoogleEmbedderConfig() (GoogleEmbedderConfig, error) {
	var body GoogleEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGoogleEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided GoogleEmbedderConfig
func (t *EmbedderConfig) FromGoogleEmbedderConfig(v GoogleEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGoogleEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided GoogleEmbedderConfig
func (t *EmbedderConfig) MergeGoogleEmbedderConfig(v GoogleEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVertexEmbedderConfig returns the union data inside the EmbedderConfig as a VertexEmbedderConfig
func (t EmbedderConfig) AsVertexEmbedderConfig() (VertexEmbedderConfig, error) {
	var body VertexEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVertexEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided VertexEmbedderConfig
func (t *EmbedderConfig) FromVertexEmbedderConfig(v VertexEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVertexEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided VertexEmbedderConfig
func (t *EmbedderConfig) MergeVertexEmbedderConfig(v VertexEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOllamaEmbedderConfig returns the union data inside the EmbedderConfig as a OllamaEmbedderConfig
func (t EmbedderConfig) AsOllamaEmbedderConfig() (OllamaEmbedderConfig, error) {
	var body OllamaEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOllamaEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided OllamaEmbedderConfig
func (t *EmbedderConfig) FromOllamaEmbedderConfig(v OllamaEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOllamaEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided OllamaEmbedderConfig
func (t *EmbedderConfig) MergeOllamaEmbedderConfig(v OllamaEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOpenAIEmbedderConfig returns the union data inside the EmbedderConfig as a OpenAIEmbedderConfig
func (t EmbedderConfig) AsOpenAIEmbedderConfig() (OpenAIEmbedderConfig, error) {
	var body OpenAIEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOpenAIEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided OpenAIEmbedderConfig
func (t *EmbedderConfig) FromOpenAIEmbedderConfig(v OpenAIEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOpenAIEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided OpenAIEmbedderConfig
func (t *EmbedderConfig) MergeOpenAIEmbedderConfig(v OpenAIEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOpenRouterEmbedderConfig returns the union data inside the EmbedderConfig as a OpenRouterEmbedderConfig
func (t EmbedderConfig) AsOpenRouterEmbedderConfig() (OpenRouterEmbedderConfig, error) {
	var body OpenRouterEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOpenRouterEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided OpenRouterEmbedderConfig
func (t *EmbedderConfig) FromOpenRouterEmbedderConfig(v OpenRouterEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOpenRouterEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided OpenRouterEmbedderConfig
func (t *EmbedderConfig) MergeOpenRouterEmbedderConfig(v OpenRouterEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBedrockEmbedderConfig returns the union data inside the EmbedderConfig as a BedrockEmbedderConfig
func (t EmbedderConfig) AsBedrockEmbedderConfig() (BedrockEmbedderConfig, error) {
	var body BedrockEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBedrockEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided BedrockEmbedderConfig
func (t *EmbedderConfig) FromBedrockEmbedderConfig(v BedrockEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBedrockEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided BedrockEmbedderConfig
func (t *EmbedderConfig) MergeBedrockEmbedderConfig(v BedrockEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCohereEmbedderConfig returns the union data inside the EmbedderConfig as a CohereEmbedderConfig
func (t EmbedderConfig) AsCohereEmbedderConfig() (CohereEmbedderConfig, error) {
	var body CohereEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCohereEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided CohereEmbedderConfig
func (t *EmbedderConfig) FromCohereEmbedderConfig(v CohereEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCohereEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided CohereEmbedderConfig
func (t *EmbedderConfig) MergeCohereEmbedderConfig(v CohereEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTermiteEmbedderConfig returns the union data inside the EmbedderConfig as a TermiteEmbedderConfig
func (t EmbedderConfig) AsTermiteEmbedderConfig() (TermiteEmbedderConfig, error) {
	var body TermiteEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTermiteEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided TermiteEmbedderConfig
func (t *EmbedderConfig) FromTermiteEmbedderConfig(v TermiteEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTermiteEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided TermiteEmbedderConfig
func (t *EmbedderConfig) MergeTermiteEmbedderConfig(v TermiteEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAntflyEmbedderConfig returns the union data inside the EmbedderConfig as a AntflyEmbedderConfig
func (t EmbedderConfig) AsAntflyEmbedderConfig() (AntflyEmbedderConfig, error) {
	var body AntflyEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAntflyEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided AntflyEmbedderConfig
func (t *EmbedderConfig) FromAntflyEmbedderConfig(v AntflyEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAntflyEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided AntflyEmbedderConfig
func (t *EmbedderConfig) MergeAntflyEmbedderConfig(v AntflyEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedderConfig) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Multimodal != nil {
		object["multimodal"], err = json.Marshal(t.Multimodal)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'multimodal': %w", err)
		}
	}

	object["provider"], err = json.Marshal(t.Provider)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'provider': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *EmbedderConfig) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["multimodal"]; found {
		err = json.Unmarshal(raw, &t.Multimodal)
		if err != nil {
			return fmt.Errorf("error reading 'multimodal': %w", err)
		}
	}

	if raw, found := object["provider"]; found {
		err = json.Unmarshal(raw, &t.Provider)
		if err != nil {
			return fmt.Errorf("error reading 'provider': %w", err)
		}
	}

	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8Rba3LbSJK+SgZ6NixpQVKy3B4HJzpmZUnt1oxeIcnTM9t0iEUgSVYbqIKrCrLYCkXs",
	"EfbHXmMvNSfZyKzCgyQoy96Z3T82BdQjKx9fPirxECU6L7RC5Ww0fIhsMsdc8M8D5abZ4jifYJqiOdRq",
	"Kmf0PEWbGFk4qVU0jPzz0gj6G6bagJsjTEqZuZ5U4BcB5FWkmkFh9J1M0fRHaqTeW7QgVHiNKZyc37zp",
	"fSqFcvI3TEFkWe9MKnl61jt93bt7CRfn53+FXKeYwaRUaYYppNJg4rLFSEnl95ZKmEUfzjXgvUOjRAYW",
	"zZ1MMIaDyxP4iIsYtAnrpPqzyrRIweCnUhpMmbKdnTN6O9zZWSdia//NK0hljspKrWwMDu9dT6tsse2n",
	"/ojClQbtcGdnpHrw72g0JEt8+vt//Bd81uajBV060FNPuL6n4ecaFDp6CyJJ0NqaMnp7WRqEdxqkmqJB",
	"lSDcSQHv9NnpX6M4wnuRFxmSmCpGR8NIsBCixzhyiwKjYaQnv2Li6MFbTI1OPn6blA9+voawwJMSpnGJ",
	"wRSVkyKzMDU6B1R30miVo3IkjJODMzA6QxvYf+xPAiwG4iQkeo4G+7xRD9Usk3beu3sVg8jFb1r1nXRC",
	"9fxrlsjdy+GuX+xIJ7zE3LnCDgeDVCe2Lz7bfpia6Hww8QcZZMKhdYPSopmVMsUBq4nt2bIotHGY9ucu",
	"z5Z5zUOiYbSBxChuSyNsFMWRwZlnb2l7KKzr7ZFICqMLNE4iW+FEuGR+a+Vv6KUyFWXmouFevCKhG1Ig",
	"Ggs0lkXUiIQUCK2z4DTowsmchri50eVsXpSuH9WaIZXDGRqiIxzqoWOjSujegk6OaN3SImxhf9aP4cUG",
	"PryI4cVTwnqx3W/z9Ql2BmqtM1LNiNiKlV3Ukvr597XmVgcIuFATXgtilZRGQh2b06/iVuHn20wqL7Za",
	"UFORWVwV1s9zdHM0xDaeCwo/A8/1tkEkSlWUjqEFJjjVBht5tuQ10TpDoaJH5oGHiWj4SxDehw6LP2Sm",
	"fpvB+7mbbD1gKwPSWBTy9iMuxjCVmKVk4ePDi5+Or45vDy5Pbv98/LfxEgLcCSPFJMON1r+iBPv9XdgK",
	"TI5hb/clI7LdjsPAvMyczKSalSLj0U8AQVAzAgGDAVUHvMyylbNEbivpozDJ/DbVSUkHiGp7idYpXbZ/",
	"v926pQeOdetw4HxgcR8OhQKRWQ0TBIuOeb7M3272dqlv+1wtze044jJd1wUmcirRsm7QfPJkXm9JYyqk",
	"SRuFsWxVqsxJR9fXD08+lWgWURwlmbBWTmXCWsgPSuuQ6f7QcZAWYlVn6BTGOnuVyLFyw2tK7lHOQ9wy",
	"KnSuvkaWM6VKhFvh7vH50RopP+nPtM9cUGjjOWkh02pGWDEXPr7JxT04/REVZKhmbt5m6fnF+XEUR9c3",
	"B1c3Ucx7rDPq2VCxDhIiyy6m0fCXh0grDL9+Z3AaDaPvBk0kOQhh5OCd1rNsFWwe46cn/QWNw/uvnHSR",
	"ZSIXXzupQHVw8g2TrnTp0HzlxO5Y60uzOvH6S5Nu0OTSfe2szoj/8QNNW4YqRtdcp6IjPjjCJBOGwgvh",
	"wM2lDfYT4icLSit2+RQSOwKnLZmLGdoYRJlKHQMBpY7h8uhHux2PFN6hAult0y8lrXrhoM4uXtgm3/AD",
	"yNtbZxawQMce5ec5Khg7U+I4rnISZ1A421pWWGgOBkKl8FlmlDuoNCQVFckjtUozuqS/TbZLy1VgD1JZ",
	"hyIlZMF7Z0TiCE/o8H24aQ18Yb33lBasoz0N2kIrKyeZD+UoESj85DnWjKMsgjk8zcQMfi0txQtZZsMJ",
	"R0pp18QY0rPiXDtQiJRtTaskyILIDIp0ASGHqhkYAqNxw5gaF8fxSI1nmEsle/XD3steYfBO4udxDOMk",
	"k0Vvp/qVZKIYby97eE6RxuPxr1arkXoYKYBR7SxH0RBG0R3DwSiK/Usm2L+xOsfetKRcq9cQ2AsjqvH1",
	"C5pEKjBSj7xnRxTVdtRP20plJZfV+FVYrRf68PhhFecPoFTkOdOVtJBFrTbFV9WWFhKhyPFXk5E01c3B",
	"YV5w+kJCT0rrNAf6c/0ZKidrQRgcqUQrZmvKKtsZY8JNvRqF9j+xT5oIY8EulBP3ZCAjFayaAwxdtgxx",
	"jlmBpsrmqrXgemEd5iEx3tm55qV2dobt9cMx6PxbVaA2r1//ajlS87nZtl/mUCRzqWa0TkM1gZAonc6F",
	"k4nIsgUkIplXvKoZTyZ2c3NaR5ND+B5yqUqHtlqdzO3eLa9uMEF5h2wt0zLLag4TjCR+hj/724olP3mW",
	"8OFHaq8POzs2MeXkJ5dnOzvQgyvM9R2C15SBdYsMwYmZZSwKAAIJaaqXGecKP92cnZKmw3g8brjETx4e",
	"6vWBktbbAByPj9UE/r/a2MJ4VO7u7ieeAP6NY968ekEkVc+JsjD/IE0t5TA+hRFThwYmGZcFMvRqt1XE",
	"kMq7GOZ7vfnrGDIZQLMmwZVGWSgyIcPxWE6FQUrSMAUCKDGRmXQL4t9L4h9+YsYdfyoFPQcyVGGkDbaU",
	"aJVKsiyR2Y08+k5OYQs/gXXClRZGEcH0HY6i7cfHA/5JBmAeHgZyGjjXTPo3SnhGkaVQmBBm+/Hx2v/2",
	"iU97FvN7pPaJ8BxTKZj2d6j+LB2k2hVG54UDfhXKWrQ5o3Tjl2oXtOE4fnppsh/YRR0JJ95fndSEN6/J",
	"c/R5zG1pso4Bo6iyvhDxsuHxjP6vxWwUdc6x+zRBpYWWyg0mZfIRXZhUqE2TpjLD4WAwKISbD5zu2CQw",
	"D4BQoyrFwPurU7gmRA7FNlalcSqcGI6hB2+FxdevAFWiyd/Rc3h/dWJrt8YjebPBrwXO/jDhCXG/3x9X",
	"ijkmJgwHgzEM/G/Lf/TgZ5zQ/tbraY00tXfmhChFR2LUqlotnJQWONUJq0mGllER6PSVSY2ZjzTser/H",
	"au04GrBOGzFD2Jpqkws3DANXGU6p93bNsIOauMNA3KXRCVor1azh287OCQc1BHRHoSqKaUzBCGdxW3Ia",
	"IoftGJY8SM3YeiUK3jxg3rsKupDLAFNprIOCzmBQpUjeS1hgIdTTCdRo+hXbPMHg8jolUQ5n+jeZZSKM",
	"qpHB6wgmpSFIoBMbndX6UZ3MO4jCaBIQpjCpozuw1VyLjtyQhS2LlBi2ffVVVSrYHlYomGX6M6Yw19bB",
	"57l0mEnrwstLI+/IAZ5cemRk70ahEqPj9fXVjyCcE8lHWyleRagv6GUylwSjtZfa2909e7s21skcdbk0",
	"cH+3XpLl25Su1xd9ufvqTXEfszb3gtwrNbpGHNaFE19S7kvNJZTBUhjzXcW/Xi/RhEsj9YrBms3wRmvl",
	"QZv/9LojFdxcXJyDV2rYuqH8tndhJCqSzQWnpHCuHW+wvRH8mi04MO4zBtsacrpfhzz6TJiPaH7ggh1I",
	"laJyP7z60tQUmYdofhhFo5HrhKufKROSlk/4x6CFfFppQXiXlbgY5mUuVM9UGh9YkaKVMxWC9UKwyVJA",
	"XyaOAz9mn9NwenpGwRYAnLgqbLSws7O/23u9+y+hYGAwLRmNuJxOrtLb75+uL85JYzOEXEjlhFS0zVzO",
	"5rQwL0vjDc6D5ogkKY1IFv36lH/GBSxdfLDGHfrTVTGjt9vxcMzH+YiL3p3ISoRCSFMHE8aIRZAJ5CwU",
	"O4QxhRu/fLf/YQhCxr5QFOdZFcHciEmZCVNxjVanEFub3HOo5li1y0VdnKKxp6dnUAjD1FG8UxIwWScU",
	"hcJhxlngjPWSWo1HmAlvUeFUOtsG1VP9GQ1X7hJtnQ2RXlomzHsSS2nJLHMUykLGo4meeka90o/CUmQV",
	"kkP0S52itX4dDvsLD+z1nDOK6pMqgoUe/Cgd5PSwSQnIgVHQ5YtKjAn1iS44Z2l717a1jGGLcqftIYWA",
	"8B1Fa1N5T3QIlmKiS9ogkx8RxiS9cQtsKBervaw3uDFsSeW2h3DCf3qktYVISDAkKIWW/QgDwhJy1SvV",
	"JjmGLV/y2h7Cj1yFtlgII5w2vqIddIZJba+ltMKYs55xsOpxNcE2TrWqUevSFaWrGFQF1U66DOkczuhg",
	"dMSWv2BC21+z/vJAUbq5NkP4k1AIR9r7wG5l51c5OsFhC/8FgD7CHcLL8IBcqx3Cq+9315DoyJ+Q4Pbq",
	"4N1wZ6fGIUpjwvnbNlQnNd5VkxT8XPhUopHhto7Xrv1hS1d49VAm9kXcxoPMpJuXEw4pndaq53fl32H2",
	"Ow0nxOG80oTOySIrPqL9KNVgpv3kpYQzSKnKuo6qA3HQ1uLlije58eKjKNUP6bNACd2PhFt+kwrHL27E",
	"zNKL71Akzdp9kuXj48MDuY3HxxgeHgY0gGaM1MNDKycLoqLgp45FqrqRVutEXnrVoj2VyD1xTZ1huJT/",
	"tQoQt5QL0uBLIxMcwu8eHgr61SLhrMk3mFEcnT1JQM2etQykg6wWMa1ND5tsLeggBV/ruy5tRomYN6HH",
	"x7cLWrz6q069mmwtEQ5n2iy4xoS5LHPO2P7+3/8Jl/7vKkBuTZ7odNGicmfnuHWx8pdwsVLd9Y/fHZ+d",
	"nJ80l1y96s6G7cnXw+HghMdeXB6fH2wc64vT7YFvD66Pb99fnVapDac/zdB2mnBwScE4TT09PTg7uP3p",
	"4vqGpvkyOd97ouH5IRUKWU5GOQkFsMO9vVf7r0JDw0lO+RZZ/6VB3qYkFD6ur3WCdf1Nl1ybkjwe8F5a",
	"ntXc/8AWFy08wXG4a+FuDKEWdblrm6JxqZKs9P7XzTGvGz0IgRa6NC0H5sMKwrDxbbNXuHvsw81cWpgs",
	"KHryl1Uj1ZTYZqgwhPTWYeHrvkY6tHDHYG2bnUN9l3zVfahsXTss/PH3+nBokDCnHhOSHV+cmyOIojC6",
	"MJIG1VE4lzJ+ph1XXPLSYYbwAKPIl2F47XORh1LMKBrCL/1+37+sp/iX/X7/AzyOv1x0ZZvyddWzBVQ4",
	"WZdRq7IDD6hRlEvZ/X49qkUwjXzwLmkU5Ytbz8xbpp0p3u3vxbDbf0n/7MdAhNLwx6o860l+bxEOha0N",
	"7EzOjK8NsiIJpfkm3a/OsR7l8J5/HfpHS7y3KzoZVMAngU3PECflPKPR/6Kt/x1a7KmpLwCWN37L/RlF",
	"nXq3adDTaSYVVnVYqWZow61nR6MJt0w0Rff9ns1Fli3fM+sClZBcl14rVnfeMa+XnduXnuGG0Rf8oziU",
	"5aM40gwp9MNv6H8YviGL4la7S7j4jqPc/+38JVUUVw1KXXe6nTeIz2xXqNEWtt4x2dvf2rqwiupf1bqw",
	"dkeyu7vXal7Y3/39S9+80N2jIGR/xgfpp3g3CIuJQvrMu1GhZU2puwkiwkoa36M/46jGnWhIOzd9C11k",
	"LmtUkP3XdS5UQniqc2GZvc/vXGidpXW17o+1TklT9wg3/Y0yBPjY+v3rNzHsfb//mo2ZJWMw0XlO4W+6",
	"3d0oRT7Tbew+Cuc/zHSZQjW03XCUoHJGZHsvtvtwFS6QWIX9PTgQwuiiiYvA6zJxtJMpHV0QG0T7dB/E",
	"cxogNiy8RlNhNCVstzJ9BpPCYDg5gq0NB4/rnshlTm13cqQ0G/rYKP4Jp22paVVLbXbnZNDWCZKcgtIO",
	"bOh/8XrhI9ZoGJVGRt/ec9HZx/BMvAvB3QaM8+XmlsvhipKRdyJZcNRTuSCSMrOG0bA0WRsJl+JJVHdk",
	"oBuRT+lcJq0uPzawqlErv5+IoDq9TJgZwla7j0tkWY/EneV1w+0mhPQeiLNBnyv/MfmhPme3A12lbMV1",
	"Vi6NNSfqjo3XcfCJjsm2YQUxta2qxoNVul7E8GKNUavNiR2H2WwDFSZsOFT8tJkE2ttm0g3pLT3ZiOfN",
	"CTYS84+yqq5Gn+daFc/91shhNcfbEDlcV90x3ancqilutLjuwLDdKvn9/uvKxNYGBzP8UkRSZMKRYPo+",
	"4mPD42CEL+WfE5PYj71+v99qmvyagParwo8gvSfDj2UZfUP4Ydf3vuCqYCvmqNSp0aMtdipnIYdvRtZV",
	"eg4I6uhjCC+/fx3D93svfcPrSqDyxSbuyvA3svoLqOUZuTkW2Lju87CIQ91CtnTqi1jUiLbBolDi5Fq4",
	"H/DCcqjEkl8XelVTeSZIdVL5DwSpzsbCrwAqP38TWLVG1FdEou5FIkbWzQYEKysRYGhOT+WUK731NRN3",
	"+TwHB68u3t8cX31jFuU5PvgCwG3HGwcyuMUj5ZOpQVfoGsOnz6gG9M9+682byYa4o85z+yKkY5SXrTSR",
	"fwkItVnBwidPug6JIdP+elgMmvBFaFwW2/8dPMop1B/dwGTRdGpuPxvrvsTKJxkTmk35s6WpRFMHaU+u",
	"ShHbEyq2Grt9icJvBZPuDuBnIkmYvAlGqtfSdnTgnp3WX9XQctlq1uFrtc2HfAQe7Svrzsqsv60hXOo5",
	"kkTiG/5gK8dcmwX8KxRorLQOlas6TFe+wvPpD+3bmwjb/iihtREP3IOwKvcLdrcL8sCXrV3hEif0rq5A",
	"8mQadi3VLMNpJmdzBymmZZGFy7CqRy0pDeOpVzUis/pgaxMYTmbIp+ih6t3t9b9fSqw2frDo47mz0PFr",
	"EHyHT/PN0dhLJOAWGjvwF0uDcaiBa7Por0PZhizpze6bly1YW6V5GcmqYmAnjD0nga+U8supycH5zY+n",
	"f7u9Ob46O7n5Guffdbqnff+TX9GtFlg42trKRcHByyZRNJJYQZIO/n4reHR+gfEM7Fgq49RFmfU4YguV",
	"Q1MYabE3MyLF7dbHokVjH9V99WHr49Gtg6PDbd8pXbq5NxgaXBfPbP0tKYz5i9KBkHXGUlo04/99pTaG",
	"job46kOGAX8TMODPGDZkUAlxqCrrUvrkq+k9IQcVGN1hT6zVeAczdL1lX2FHK3cEawXepj4ZtcqN0XMq",
	"v3XRLsoXvVlS9MKzZdsNVwFrptv65ve2EG6+rkKXws35C4XgMUTCHSO+IYkvQmWGfTjI+E6G22GdhoOj",
	"Q98MolXv3eFl23rt/1udmAjqYuQfYO/lm97eq903K5289ahnlZWriGZZgsvEL5lf64vXxhIJHLtKzzG8",
	"wJJk1/uM1nEpurNOf3Hx7vT49vD04v3R7enF4cHNycX5cs61tOw/tT69EV/+aZXqDVXqZ/Dq8uriT8eH",
	"N8+NnZ8J1I/88eZUr1N6oHzye3lSVamXIw7GbWJYk8ytx3q2+cTq6C1TKR3zsrn3h+pGcbk51l8PeoOL",
	"dvu7ff6wnUPdQkbDaL+/298nDBFubqOhKrPs8X8CAAD//6qfCzuKQgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
