//go:build go1.22

// Package usermgr provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package usermgr

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BasicAuthScopes  = "BasicAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for PermissionType.
const (
	PermissionTypeAdmin PermissionType = "admin"
	PermissionTypeRead  PermissionType = "read"
	PermissionTypeWrite PermissionType = "write"
)

// Defines values for ResourceType.
const (
	ResourceTypeAsterisk ResourceType = "*"
	ResourceTypeTable    ResourceType = "table"
	ResourceTypeUser     ResourceType = "user"
)

// ApiKey Public metadata for an API key (secrets are never returned after creation).
type ApiKey struct {
	// CreatedAt When the API key was created.
	CreatedAt time.Time `json:"created_at"`

	// ExpiresAt When the API key expires. Null means never.
	ExpiresAt *time.Time `json:"expires_at"`

	// KeyId Unique identifier for the API key.
	KeyId string `json:"key_id"`

	// Name Human-readable name for the API key.
	Name string `json:"name"`

	// Permissions Optional permission scoping. If empty, inherits owner's full permissions.
	Permissions *[]Permission `json:"permissions"`

	// RowFilter Per-table row filter. Keys are table names (or '*' for all tables). Values are bleve query JSON objects. Documents must match this query to be visible through this API key.
	RowFilter *map[string]interface{} `json:"row_filter"`

	// Username Owner of the API key.
	Username string `json:"username"`
}

// ApiKeyWithSecret defines model for ApiKeyWithSecret.
type ApiKeyWithSecret struct {
	// CreatedAt When the API key was created.
	CreatedAt time.Time `json:"created_at"`

	// Encoded Pre-encoded credential ready for the Authorization header: base64(key_id:key_secret).
	Encoded string `json:"encoded"`

	// ExpiresAt When the API key expires. Null means never.
	ExpiresAt *time.Time `json:"expires_at"`

	// KeyId Unique identifier for the API key.
	KeyId string `json:"key_id"`

	// KeySecret Cleartext secret for the API key. Store securely — it cannot be retrieved again.
	KeySecret string `json:"key_secret"`

	// Name Human-readable name for the API key.
	Name string `json:"name"`

	// Permissions Optional permission scoping. If empty, inherits owner's full permissions.
	Permissions *[]Permission `json:"permissions"`

	// RowFilter Per-table row filter. Keys are table names (or '*' for all tables). Values are bleve query JSON objects. Documents must match this query to be visible through this API key.
	RowFilter *map[string]interface{} `json:"row_filter"`

	// Username Owner of the API key.
	Username string `json:"username"`
}

// CreateApiKeyRequest Request to create a new API key.
type CreateApiKeyRequest struct {
	// ExpiresIn Duration until expiration (e.g., '720h' for 30 days). Empty means never.
	ExpiresIn *string `json:"expires_in,omitempty"`

	// Name Human-readable name for the API key.
	Name string `json:"name"`

	// Permissions Optional permission scoping. Each permission must be a subset of the creator's permissions.
	Permissions *[]Permission `json:"permissions"`

	// RowFilter Per-table row filter. Keys are table names (or '*' for all tables). Values are bleve query JSON objects. Documents must match this query to be visible through this API key.
	RowFilter *map[string]interface{} `json:"row_filter"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	// InitialPolicies Optional list of initial permissions for the user.
	InitialPolicies *[]Permission `json:"initial_policies"`
	Password        string        `json:"password"`

	// Username Username for the new user. If provided in the path, this field can be omitted or must match the path parameter.
	Username *string `json:"username,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Permission defines model for Permission.
type Permission struct {
	// Resource Resource name (e.g., table name, target username, or '*' for global).
	Resource string `json:"resource"`

	// ResourceType Type of the resource, e.g., table, user, or global ('*').
	ResourceType ResourceType `json:"resource_type"`

	// Type Type of permission.
	Type PermissionType `json:"type"`
}

// PermissionType Type of permission.
type PermissionType string

// ResourceType Type of the resource, e.g., table, user, or global ('*').
type ResourceType string

// RowFilterEntry A row filter policy for a user on a specific table.
type RowFilterEntry struct {
	// Filter Bleve query JSON that documents must match to be visible.
	Filter map[string]interface{} `json:"filter"`

	// Table Table name (or '*' for all tables).
	Table string `json:"table"`
}

// SuccessMessage defines model for SuccessMessage.
type SuccessMessage struct {
	Message *string `json:"message,omitempty"`
}

// UpdatePasswordRequest defines model for UpdatePasswordRequest.
type UpdatePasswordRequest struct {
	NewPassword string `json:"new_password"`
}

// User defines model for User.
type User struct {
	// PasswordHash Base64 encoded password hash. Exposing this is a security risk.
	PasswordHash []byte `json:"password_hash"`
	Username     string `json:"username"`
}

// KeyIdPathParameter defines model for KeyIdPathParameter.
type KeyIdPathParameter = string

// UserNamePathParameter defines model for UserNamePathParameter.
type UserNamePathParameter = string

// RemovePermissionFromUserParams defines parameters for RemovePermissionFromUser.
type RemovePermissionFromUserParams struct {
	// Resource The name of the resource for the permission to be removed.
	Resource string `form:"resource" json:"resource"`

	// ResourceType The type of the resource for the permission to be removed.
	ResourceType ResourceType `form:"resourceType" json:"resourceType"`
}

// SetRowFilterJSONBody defines parameters for SetRowFilter.
type SetRowFilterJSONBody map[string]interface{}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// UpdateUserPasswordJSONRequestBody defines body for UpdateUserPassword for application/json ContentType.
type UpdateUserPasswordJSONRequestBody = UpdatePasswordRequest

// AddPermissionToUserJSONRequestBody defines body for AddPermissionToUser for application/json ContentType.
type AddPermissionToUserJSONRequestBody = Permission

// SetRowFilterJSONRequestBody defines body for SetRowFilter for application/json ContentType.
type SetRowFilterJSONRequestBody SetRowFilterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all users
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// Get current authenticated user
	// (GET /users/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Delete a user
	// (DELETE /users/{userName})
	DeleteUser(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// Get user details
	// (GET /users/{userName})
	GetUserByName(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// Create a new user
	// (POST /users/{userName})
	CreateUser(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// List API keys for a user
	// (GET /users/{userName}/api-keys)
	ListApiKeys(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// Create a new API key
	// (POST /users/{userName}/api-keys)
	CreateApiKey(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// Delete an API key
	// (DELETE /users/{userName}/api-keys/{keyId})
	DeleteApiKey(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter, keyId KeyIdPathParameter)
	// Update user password
	// (PUT /users/{userName}/password)
	UpdateUserPassword(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// Remove permission from user
	// (DELETE /users/{userName}/permissions)
	RemovePermissionFromUser(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter, params RemovePermissionFromUserParams)
	// Get user permissions
	// (GET /users/{userName}/permissions)
	GetUserPermissions(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// Add permission to user
	// (POST /users/{userName}/permissions)
	AddPermissionToUser(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// List row filters for a user
	// (GET /users/{userName}/row-filters)
	ListRowFilters(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// Remove row filter for a user on a table
	// (DELETE /users/{userName}/row-filters/{table})
	RemoveRowFilter(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter, table string)
	// Get row filter for a user on a table
	// (GET /users/{userName}/row-filters/{table})
	GetRowFilter(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter, table string)
	// Set row filter for a user on a table
	// (PUT /users/{userName}/row-filters/{table})
	SetRowFilter(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter, table string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserByName operation middleware
func (siw *ServerInterfaceWrapper) GetUserByName(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserByName(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListApiKeys operation middleware
func (siw *ServerInterfaceWrapper) ListApiKeys(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApiKeys(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApiKey operation middleware
func (siw *ServerInterfaceWrapper) CreateApiKey(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApiKey(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiKey(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	// ------------- Path parameter "keyId" -------------
	var keyId KeyIdPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", r.PathValue("keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiKey(w, r, userName, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUserPassword operation middleware
func (siw *ServerInterfaceWrapper) UpdateUserPassword(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUserPassword(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemovePermissionFromUser operation middleware
func (siw *ServerInterfaceWrapper) RemovePermissionFromUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params RemovePermissionFromUserParams

	// ------------- Required query parameter "resource" -------------

	if paramValue := r.URL.Query().Get("resource"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "resource"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "resource", r.URL.Query(), &params.Resource)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resource", Err: err})
		return
	}

	// ------------- Required query parameter "resourceType" -------------

	if paramValue := r.URL.Query().Get("resourceType"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "resourceType"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "resourceType", r.URL.Query(), &params.ResourceType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceType", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemovePermissionFromUser(w, r, userName, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserPermissions operation middleware
func (siw *ServerInterfaceWrapper) GetUserPermissions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserPermissions(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddPermissionToUser operation middleware
func (siw *ServerInterfaceWrapper) AddPermissionToUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddPermissionToUser(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRowFilters operation middleware
func (siw *ServerInterfaceWrapper) ListRowFilters(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRowFilters(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveRowFilter operation middleware
func (siw *ServerInterfaceWrapper) RemoveRowFilter(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", r.PathValue("table"), &table, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveRowFilter(w, r, userName, table)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRowFilter operation middleware
func (siw *ServerInterfaceWrapper) GetRowFilter(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", r.PathValue("table"), &table, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRowFilter(w, r, userName, table)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetRowFilter operation middleware
func (siw *ServerInterfaceWrapper) SetRowFilter(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", r.PathValue("table"), &table, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetRowFilter(w, r, userName, table)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/users", wrapper.ListUsers)
	m.HandleFunc("GET "+options.BaseURL+"/users/me", wrapper.GetCurrentUser)
	m.HandleFunc("DELETE "+options.BaseURL+"/users/{userName}", wrapper.DeleteUser)
	m.HandleFunc("GET "+options.BaseURL+"/users/{userName}", wrapper.GetUserByName)
	m.HandleFunc("POST "+options.BaseURL+"/users/{userName}", wrapper.CreateUser)
	m.HandleFunc("GET "+options.BaseURL+"/users/{userName}/api-keys", wrapper.ListApiKeys)
	m.HandleFunc("POST "+options.BaseURL+"/users/{userName}/api-keys", wrapper.CreateApiKey)
	m.HandleFunc("DELETE "+options.BaseURL+"/users/{userName}/api-keys/{keyId}", wrapper.DeleteApiKey)
	m.HandleFunc("PUT "+options.BaseURL+"/users/{userName}/password", wrapper.UpdateUserPassword)
	m.HandleFunc("DELETE "+options.BaseURL+"/users/{userName}/permissions", wrapper.RemovePermissionFromUser)
	m.HandleFunc("GET "+options.BaseURL+"/users/{userName}/permissions", wrapper.GetUserPermissions)
	m.HandleFunc("POST "+options.BaseURL+"/users/{userName}/permissions", wrapper.AddPermissionToUser)
	m.HandleFunc("GET "+options.BaseURL+"/users/{userName}/row-filters", wrapper.ListRowFilters)
	m.HandleFunc("DELETE "+options.BaseURL+"/users/{userName}/row-filters/{table}", wrapper.RemoveRowFilter)
	m.HandleFunc("GET "+options.BaseURL+"/users/{userName}/row-filters/{table}", wrapper.GetRowFilter)
	m.HandleFunc("PUT "+options.BaseURL+"/users/{userName}/row-filters/{table}", wrapper.SetRowFilter)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc/W4bNxJ/FWLvgMSFLDlx2kMNFDjbsR2njaNYcYs2ZxjU7kjLeJfckFzLqiHgHuKe",
	"8J7kMCT3e/Vhx3YVnP8oquySyyHnN99D33i+iBPBgWvl7dx4CZU0Bg3S/OtnmB4HfarDfvYYnwagfMkS",
	"zQT3dryPIZDd/jG5hCk5ft31Oh7DxwnVodfxOI3B2/Eu8UNex5PwJWUSAm9HyxQ6nvJDiCl+FK5pnEQ4",
	"lu75r+Fw/Ia9vfwlPhH9L6fqo9fx9DTBt0pLxsfebNbxzhTIExrDCgSmCiSSMoe81H1pRQo/i5AHAlqI",
	"mmUTzPHtJuxnmDYp6qfDiPkkBk0DqikZCUkoz0/xuQJfglaESiAcrkASCTqVHAJCRxok8SVQ/NYG7ieR",
	"IgGpGZg1zSsILqhurvtbCJzoEr8mVBE3Ab80EjLGeV5ANWxqFrdssePBdcIkqNVWcIO75CSNIhID5cpu",
	"ae56PI0iOsRztgxorH8J0wsWNNc+4+xLCoQFwDUbMZDmXEvE4JK3hVkGkfpib9KY8k0JNEBaCQ5avNz+",
	"MUlYAhHjgC/bVkpAxkwpJrhqLvje/KARKUYR5YuE8XGXHI8IxImedgjjIUimFRETDvKZIiM899KXjQRo",
	"iM0Sf5cw8na8v/UKJdBz+O318znmFNq5QqWkU3wvxeRixCIngDQImCW3XwbnrFMXBJCb2hygFBNi53fJ",
	"zzC12Nf52SryXEjy7LtnVlaiyL5TG13yK41SsOOHEVwB+ZKCnJK3g/cnRAw/g69Vl7wWfhrj9kicKk1i",
	"qv2Q6JApN1oLMgRyxRTDFXUoRTp2AzJu/ovPB6ddB88hUzQtDESGEDGaD5H5aqWslj5lAuCgWVqzU5b+",
	"8xbqrEL6jelwYFSM4VUUvR95O58Wo8GpslnnpqZvgPsigBZx7EvYdC9RxxippBFBkZkWopLqUEj2p9Fm",
	"JAQagNwhQ6rgh1fP7T538H9WI25Uz+v3s7efT49+PfpjK0wGsX43PPv+6uzN4cB/8eGHPw4C4R+dfP+B",
	"732Gs7dicBa+Hx5e/jmIry8/fPjpJ2+OYlH5uVR3sx8BlRquNbEjGsJOBlpIwLephGhK/vvv/xCmiU85",
	"FxrBJUFLBleow8eU8epWgqMw8ad7+F94/OYk+n37bRTsroQER3En50ST8ed1ucu0c2ZHiASVCK6AMO5H",
	"acD42GzOr+/6uQrFhBPBfdjo4pntG8BZdJzClxRUy+G5FyhlFqCEEg6TshTUQOVMDJrq+sdep9LSnHLN",
	"Imtg7IPn0B13O+TZP15uhVZRbG+RgE5RSxygeqzbn+L8ccq3qvwPqB+WXxgNN8QzVulQgc50jjl6gTbh",
	"yRw8jjmoSasBU5tatkKE7mxJhKoSwThD9XmRiIj57tkcjERMGZ67KWVu5yhFk/FArE+oUhMhg6rLrLZ9",
	"ua37/1Rq8l4GZd8vH98iFPOt6Zl7k+8I9YnZFTpDiRRXDA0Ps94oevsdy78RgyhAtYwcFjHTGgIiZBUI",
	"dgbJg6G72el8Z208P5BSyCafIXtcLLfLiXlKYlCKjpeva7/RtmiJk42VJSiRSh/a1Ld9YxWd07KFMOJv",
	"OQadB1kdUhLOcSSGNKpZbiEDkOrCfKON7xktF/bNYnhm5H3EsbPsa6tC2s6qnWB+FnVS3NcXn+1HR0At",
	"DJ0mgGJZiKM5E57GdkWKEjCRTOMqNIgZx2WKM3MjGmdV2f7cVRHT2VY6pMTCjmGbYZllFXn+7LtnG2Xa",
	"MjbhQK/jfVelay4TT8Xk0KjwA65lSxS8W9LyxOg16xdSQxERHC1YAj4bMd/S2nQUbm9j9upGQYdUk6DV",
	"IJStQAXAN54GGdstJVRqnOrteMDHjAPkQtnAiD2rJpMKN2KeXWsRn6V6IOOMO6Q20A5S3wel3jnN0lAK",
	"cfGiWP59As7jQsmKADWosh/CaHPaSlhj6bMEo/6+05FzDR+HyUW7SeEwGdzBqtSNcvn7bUeElqZJVjbl",
	"IqQqbHJ0z0QwJIt/stEER3fJwXUilPWxmSJMIdAxbmB6SiRTl1Vuvz06nP7x8sf0XdztVrImw6mGZVbz",
	"9larFE1WN3ne5t9kdA9QsUIp64WRnXVcvB3PBnZFvq0S9hUU0SzIxPNjfvYJo7Tx/RCfFsNDrRMzGKgE",
	"2RxtHteHI9GMj4TJlQmuqW9AlxHG9cgAOJWRm6J2er0x02E67Poi7lEzIhi6H96sLbZC6Y0pp2NkMh6o",
	"Qu8DmMyRoDqE8qDuiUfMB66gTFBC/RDIy+5Wg6jJZNKl5nVXyHHPzVW9X473D04GB5svu1vdUMeRUTxM",
	"GxAgmMk7pAxQZ6E363W8K5DWJ/CuXtAoCekLnCMS4DRh3o633d3qbhs86NCwuGf2hL/G0Brv2VAXgZ15",
	"o6jMzKzMJ1NTpSHuklOLPUWMzauZR5GpmuPA2/F+YUqfKav6sojVUPFyayvjp9HENx5Nkoj5Zmrvs7L+",
	"TpHKzd3eqlDfXnCaGr7iDc8a6BjkepLke8N5r7Ze3GoHi5wb61q2LH7GqRM8COyi2w+/6KGQQxYEwMkm",
	"kfN4jdR8f0sm3omaY66RxxEZgLwCSbKBHU+lcUzRTzEwK/CKfKdjharRmIJzHGwFoGehskQGAtCURUXs",
	"5adSAtfRlCA3gGvcIgR5TFbF/BHofTvhzLpfXwX8mhGr5hzuEAzWg7+vlqA1l5i1wegR6AxILTBahNmb",
	"rNg1s6BF/60ly2aeq7IL3o5PO7Adm6/a43ZiF605jYalj3C6ezQgWULSxbIZatEVy1yhDUvQq0fAGB4J",
	"F5qMRMrXC2WWuS4ia4KqcxvVtxRJR2BU3N40r8R+haJbdCSG+ltpmidYrp3yS60iMfhqQ2a5kWFObasY",
	"0mtvJZidd7xEtFU0bMZWuTqGoWXCtE0djtkV8IJ5xs13Xn+X5HlLdH8ozqCXoEgiwYcAuA9NuSiyw649",
	"AZTeE8H03njRTD/Pg0NeLyoOvtovMWuI7YsHF9uCsjUyKYxf0YgFhPEk1YUo9/JMQMyUyTI5gf7x4anc",
	"F3wUMb+iXgiNbEEWrpnSamOtxHy/XCtc3a3p0YRtXsJ0YXyaSq6Mj+/qObZhIiDDqQ1OranKvHIyaHTk",
	"2EKp7ZtpRqk2B3J/cepKpflvLfj8/zZiJsrM0Vckvksgd5x9bHOWdQdkAWtdGD62dQYYH8U1qQkeTW2a",
	"xzy1AjDPsLlNPqRpq7YntPCr0Q/xV9i3RnPOMkLX1dxt/AW5JUeHwxBUMqsErn2wXUjNBognh7puaR3G",
	"2vTQQnPbuzFdvgvTCn2QMeU2+xW4FENVxRT9VOlQITe5zriqSFpUTUz7Kosi21r1GXzdZottAFtSMcvy",
	"E5mAzU9RPAJSMiLWOynAFyHlnixWZ+nElhb12XkrTstVxHszp2mLNbWVTeX6SJy/v1IKxM7E5fpF/fIh",
	"7GJ78bUFECcwKfawulW8P6jWKtQtJGa7IKnZ1PoYRV4+O9efnacFnhI6JZVi4Wgj0nLlfoVgr9E32W54",
	"TiEWV9V8dqllUqYRkJEUcdZ8MqTK+LF5zwzJczkYZDUl136/KI4cShG7lE1N1zQvp5hP13p0cue7RKXt",
	"R5FmpSC/yWJaWYrSeqV1aflVlsWdWKh/m/Tqlp6ir6b3o22vmk/z6i1gqJiXW/p+if2WxLVRHIYuPnZd",
	"SgV+Cj+7fGprpFSIkORURFB6kuHCZkVzdK6T9rGyW0auUQW1YLxU+Fyh8kGjZuPtqhWQfkmlPUYCaVFJ",
	"96lK8u1XSZIKnubg+WETTLtBkGWXqgZiqUzsBkGps1Y8YBmkLAaztrsJGdlZVRPJD4JHzRGt4A0XdNIg",
	"WP+KyJPMlmV2NwhqArLICrU6xFJMNm3H72oFkHoTNgM1L/PbWurI27wfx1jVusq/ymA9FSBK3J9Tg8jP",
	"+x6txDLc9m5MPDJbJaAzQUjrPYImgG38lt0kaAvgit2uEkKcFuvODyEeC2RCls9hPSHnPO0SnfULH3kg",
	"2gq/hcrsvpBwBHoBDO7vJOuabB0117cAKvRz74yo+8pS3+VCT8sfIsmIXT1105K0mZeXHoBWhqOQRNS/",
	"u+40BWDngZOhCKYYeuGM+oXbpmwN6rJ1Nzd+/mWvpe3EjftfuF17AIyPi4tgj5rkXq4KSqZGgV47p96R",
	"hgf65MdbnN9VJ5VvVRmdVLoL9ekcdU35gpV9Ur4B9ekcFYAytLVlnN9RZit3dkh+rahHE9a7emGCeEdX",
	"84q5k2VFJESm1uIiFFWoMBehX28GTCURtd287nFTU7Z/spqxcB8uhT7Nz1dyWKstklVZ4/w6VOmCWlYx",
	"rq+Dk7I/hLLKIujVosaJiht+ozxacouVNWJ9PZR793J2PvtfAAAA//+90WtarksAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
