// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package common

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/antflydb/antfly/lib/ai"
	externalRef1 "github.com/antflydb/antfly/lib/audio"
	externalRef2 "github.com/antflydb/antfly/lib/chunking"
	externalRef3 "github.com/antflydb/antfly/lib/embeddings"
	externalRef4 "github.com/antflydb/antfly/lib/middleware"
	externalRef5 "github.com/antflydb/antfly/lib/reranking"
	externalRef6 "github.com/antflydb/antfly/pkg/generating"
	externalRef7 "github.com/antflydb/antfly/pkg/libaf/logging"
	externalRef8 "github.com/antflydb/antfly/pkg/libaf/scraping"
	externalRef9 "github.com/antflydb/termite/pkg/termite"
	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for StorageBackend.
const (
	StorageBackendLocal StorageBackend = "local"
	StorageBackendS3    StorageBackend = "s3"
)

// Config defines model for Config.
type Config struct {
	// Chains Named chain configurations for fallback/retry logic.
	//
	// Chains are ordered lists of generators with retry and fallback logic.
	// Each link references a generator by name from the `generators` map.
	// The first chain defined becomes the default when no chain name is specified.
	//
	// **Chain Conditions:**
	// - `on_error`: Try next generator on any error (default)
	// - `on_rate_limit`: Try next only on rate limit (429) errors
	// - `on_timeout`: Try next only on timeout errors
	// - `always`: Always try the next generator
	//
	// **Example:**
	// ```yaml
	// chains:
	//   default:
	//     - generator: gemini-flash  # Reference by name
	//       retry:
	//         max_attempts: 3
	//       condition: on_rate_limit
	//     - generator: ollama-local  # Reference by name
	//   with-inline:
	//     - generator: gemini-flash
	//     - generator_config:  # Inline config
	//         provider: anthropic
	//         model: claude-sonnet-4-5-20250929
	// ```
	//
	// Then in API calls: `chain: "default"` or `chain: "with-inline"`
	Chains map[string][]NamedChainLink `json:"chains,omitempty,omitzero"`

	// Chunkers Named chunker configurations for text chunking.
	//
	// Define named chunkers that can be referenced by indexes and API calls.
	// The first chunker defined becomes the default when no chunker name is specified.
	//
	// **Example:**
	// ```yaml
	// chunkers:
	//   fixed-500:
	//     provider: termite
	//     model: fixed
	//     target_tokens: 500
	//     overlap_tokens: 50
	//   semantic:
	//     provider: termite
	//     model: semantic-chunker
	//     api_url: "http://localhost:8080"
	// ```
	Chunkers map[string]externalRef2.ChunkerConfig `json:"chunkers,omitempty,omitzero"`
	Cors     externalRef4.CORSConfig               `json:"cors,omitempty,omitzero"`

	// DefaultShardsPerTable Default number of shards to create for a new table.
	DefaultShardsPerTable uint64 `json:"default_shards_per_table"`

	// DisableShardAlloc Disables automatic shard reallocation (splitting/merging).
	DisableShardAlloc bool `json:"disable_shard_alloc,omitempty,omitzero"`

	// Embedders Named embedder configurations for embedding operations.
	//
	// Define named embedders that can be referenced by indexes, templates, and API calls.
	// The first embedder defined becomes the default when no embedder name is specified.
	//
	// **API Key Configuration:**
	//
	// API keys can be provided via the encrypted keystore (recommended) or environment variables:
	//
	// 1. **Keystore** (recommended for production):
	//    ```bash
	//    antfly keystore create
	//    antfly keystore add openai.api_key
	//    ```
	//    Then reference in config: `api_key: ${secret:openai.api_key}`
	//
	// 2. **Environment variable** (simpler for development):
	//    Omit `api_key` from config and set the appropriate env var:
	//    - OpenAI: `OPENAI_API_KEY`
	//    - Gemini: `GEMINI_API_KEY`
	//    - Anthropic: `ANTHROPIC_API_KEY`
	//    - Cohere: `COHERE_API_KEY`
	//
	// See [Secrets Management](/docs/secrets) for complete documentation.
	//
	// **Example:**
	// ```yaml
	// embedders:
	//   openai-small:
	//     provider: openai
	//     model: text-embedding-3-small
	//   termite-local:
	//     provider: termite
	//     model: bge-base-en-v1.5
	//     api_url: "http://localhost:8082"
	// ```
	Embedders map[string]externalRef3.EmbedderConfig `json:"embedders,omitempty,omitzero"`

	// EnableAuth Enables authentication and authorization (RBAC) for the API.
	EnableAuth bool `json:"enable_auth,omitempty,omitzero"`

	// Generators Named generator configurations for AI operations.
	//
	// Define named generators that can be referenced by chains, templates, and API calls.
	// The first generator defined becomes the default when no generator name is specified.
	//
	// **API Key Configuration:**
	//
	// API keys can be provided via the encrypted keystore (recommended) or environment variables:
	//
	// 1. **Keystore** (recommended for production):
	//    ```bash
	//    antfly keystore create
	//    antfly keystore add gemini.api_key
	//    ```
	//    Then reference in config: `api_key: ${secret:gemini.api_key}`
	//
	// 2. **Environment variable** (simpler for development):
	//    Omit `api_key` from config and set the appropriate env var:
	//    - Gemini: `GEMINI_API_KEY`
	//    - OpenAI: `OPENAI_API_KEY`
	//    - Anthropic: `ANTHROPIC_API_KEY`
	//
	// See [Secrets Management](/docs/secrets) for complete documentation.
	//
	// **Example:**
	// ```yaml
	// generators:
	//   gemini-flash:
	//     provider: gemini
	//     model: gemini-2.5-flash
	//   ollama-local:
	//     provider: ollama
	//     model: llama3
	//   openai-gpt4:
	//     provider: openai
	//     model: gpt-4.1
	// ```
	Generators map[string]externalRef6.GeneratorConfig `json:"generators,omitempty,omitzero"`

	// HealthPort Port for the health/metrics server. Defaults to 4200.
	HealthPort int `json:"health_port,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef7.Config `json:"log,omitempty,omitzero"`

	// MaxShardSizeBytes Maximum size of a shard in bytes. Used to determine when to split shards.
	MaxShardSizeBytes uint64 `json:"max_shard_size_bytes"`

	// MaxShardsPerTable Maximum number of shards that can be created for a single table.
	MaxShardsPerTable uint64       `json:"max_shards_per_table"`
	Metadata          MetadataInfo `json:"metadata"`

	// MinShardSizeBytes Minimum size of a shard in bytes before it becomes eligible for automatic merge consideration. If unset, defaults to one quarter of max_shard_size_bytes.
	MinShardSizeBytes uint64 `json:"min_shard_size_bytes,omitempty,omitzero"`

	// MinShardsPerTable Minimum number of shards to keep for a table. Automatic merges will not reduce a table below this count.
	MinShardsPerTable uint64 `json:"min_shards_per_table,omitempty,omitzero"`

	// RegistryUrl URL of the model registry for the Antfarm dashboard. Defaults to https://registry.antfly.io/v1
	RegistryUrl string `json:"registry_url,omitempty,omitzero"`

	// RemoteContent Configuration for remote content fetching (remotePDF, remoteMedia, remoteText templates).
	// Consolidates S3 credentials and security settings separate from backup storage.
	//
	// **Credential Resolution Order:**
	// 1. Explicit `credentials="name"` parameter in template
	// 2. First credential where `buckets` glob pattern matches URL's bucket
	// 3. `default_s3` credential
	// 4. Legacy fallback: `storage.s3` credentials (backward compatibility)
	RemoteContent externalRef8.RemoteContentConfig `json:"remote_content,omitempty,omitzero"`

	// ReplicationFactor How many replicas of each shard should be maintained.
	ReplicationFactor uint64 `json:"replication_factor"`

	// Rerankers Named reranker configurations for search result reranking.
	//
	// Define named rerankers that can be referenced by indexes, search queries, and API calls.
	// The first reranker defined becomes the default when no reranker name is specified.
	//
	// **Example:**
	// ```yaml
	// rerankers:
	//   cohere-english:
	//     provider: cohere
	//     model: rerank-english-v3.0
	//   termite-local:
	//     provider: termite
	//     model: mxbai-rerank-base-v1
	//     url: "http://localhost:8080"
	// ```
	Rerankers map[string]externalRef5.RerankerConfig `json:"rerankers,omitempty,omitzero"`

	// ShardCooldownPeriod Cooldown period after shard operations (start/stop/split). Format: duration string like '1m', '30s'. Default: '1m' (one minute).
	ShardCooldownPeriod time.Duration `json:"shard_cooldown_period,omitempty,omitzero"`

	// SpeechToText Named speech-to-text provider configurations.
	//
	// Define named STT providers that can be referenced by templates and API calls.
	// The first provider defined becomes the default when no provider name is specified.
	//
	// **Example:**
	// ```yaml
	// speech_to_text:
	//   whisper-local:
	//     provider: termite
	//     api_url: "http://localhost:8080"
	//     model: openai/whisper-base
	//   openai-whisper:
	//     provider: openai
	//     model: whisper-1
	// ```
	//
	// Then in templates: `{{transcribeAudio url="..." provider="whisper-local"}}`
	SpeechToText map[string]externalRef1.STTConfig `json:"speech_to_text,omitempty,omitzero"`

	// SplitFinalizeGracePeriod Minimum continuous readiness duration required before finalizing a split. Format: duration string like '15s', '1m'. Default: '15s'.
	SplitFinalizeGracePeriod time.Duration `json:"split_finalize_grace_period,omitempty,omitzero"`

	// SplitTimeout Maximum duration for a shard split operation before triggering rollback. Format: duration string like '5m', '30s'. Default: '5m' (five minutes).
	SplitTimeout time.Duration `json:"split_timeout,omitempty,omitzero"`
	Storage      StorageConfig `json:"storage"`

	// SwarmMode Bypasses Raft consensus for shards, using direct writes instead. Useful for development and testing with a single node.
	SwarmMode bool                `json:"swarm_mode,omitempty,omitzero"`
	Termite   externalRef9.Config `json:"termite,omitempty,omitzero"`
	Tls       TLSInfo             `json:"tls,omitempty,omitzero"`

	// Version Internal version of antfly
	Version string `json:"version,omitempty,omitzero"`
}

// LocalStorageConfig defines model for LocalStorageConfig.
type LocalStorageConfig struct {
	// BaseDir Root directory for all antfly data storage. Defaults to 'antflydb'.
	BaseDir string `json:"base_dir"`
}

// MetadataInfo defines model for MetadataInfo.
type MetadataInfo struct {
	// OrchestrationUrls Mapping from Metadata Node ID (hex string) to its URL used by store nodes for enrolling into the cluster
	OrchestrationUrls map[string]string `json:"orchestration_urls"`
}

// NamedChainLink A link in a chain that can reference a generator by name OR provide an inline config.
//
// Use `generator` (string) to reference a named generator from the `generators` map.
// Use `generator_config` (object) to provide an inline generator configuration.
// Only one of `generator` or `generator_config` should be specified.
type NamedChainLink struct {
	// Condition Condition for trying the next generator in chain:
	// - always: Always try next regardless of outcome
	// - on_error: Try next on any error (default)
	// - on_timeout: Try next only on timeout errors
	// - on_rate_limit: Try next only on rate limit errors
	Condition externalRef6.ChainCondition `json:"condition,omitempty,omitzero"`

	// Generator Name of the generator from the generators map
	Generator string `json:"generator,omitempty,omitzero"`

	// GeneratorConfig A unified configuration for a generative AI provider.
	GeneratorConfig externalRef6.GeneratorConfig `json:"generator_config,omitempty,omitzero"`

	// Retry Retry configuration for generator calls
	Retry externalRef6.RetryConfig `json:"retry,omitempty,omitzero"`
}

// S3Info defines model for S3Info.
type S3Info struct {
	// AccessKeyId AWS access key ID. Supports keystore syntax for secret lookup. Falls back to AWS_ACCESS_KEY_ID environment variable if not set.
	AccessKeyId string `json:"access_key_id,omitempty,omitzero"`

	// Bucket S3 bucket name where SST files will be stored
	Bucket string `json:"bucket"`

	// Endpoint S3-compatible endpoint (e.g., 's3.amazonaws.com' or 'localhost:9000' for MinIO)
	Endpoint string `json:"endpoint"`

	// Prefix Optional path prefix within the bucket (e.g., 'antfly/production/')
	Prefix string `json:"prefix,omitempty,omitzero"`

	// SecretAccessKey AWS secret access key. Supports keystore syntax for secret lookup. Falls back to AWS_SECRET_ACCESS_KEY environment variable if not set.
	SecretAccessKey string `json:"secret_access_key,omitempty,omitzero"`

	// SessionToken Optional AWS session token for temporary credentials. Supports keystore syntax for secret lookup.
	SessionToken string `json:"session_token,omitempty,omitzero"`

	// UseSsl Enable SSL/TLS for S3 connections (default: true for AWS, false for local MinIO)
	UseSsl bool `json:"use_ssl,omitempty,omitzero"`
}

// StorageBackend Storage backend type
type StorageBackend string

// StorageConfig defines model for StorageConfig.
type StorageConfig struct {
	// Data Storage backend type
	Data  StorageBackend     `json:"data,omitempty,omitzero"`
	Local LocalStorageConfig `json:"local"`

	// Metadata Storage backend type
	Metadata StorageBackend `json:"metadata,omitempty,omitzero"`
	S3       S3Info         `json:"s3,omitempty,omitzero"`
}

// TLSInfo defines model for TLSInfo.
type TLSInfo struct {
	// Cert Path to TLS certificate file
	Cert string `json:"cert,omitempty,omitzero"`

	// Key Path to TLS key file
	Key string `json:"key,omitempty,omitzero"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y963IjN9Io+CqImm9DUh8WSd3abZ5wnKNWy7a+kVpaST3tWdNBglUgiVEVUAZQkugO",
	"bewj7I99jX2p70k2kLjUlTe1+vu8cyYmYqxm4ZJIIK/ITHwJIp5mnBGmZDD4EshoTlIMf55yNqUz/Vcm",
	"eEaEogR+j+aYMvgLxzFVlDOcXFdaUEVS+OPfBJkGg+AvvWKSnp2h9xGnJD7VY11Qdh88dwK1yEgwCLAQ",
	"eKH/HRMZCZrpGYJBAO0RTI4iAC0XWH+TaMoFmuIkmeDovieIEguU8BmNukM2ZDCFRFgQxEVMBIlRQqWS",
	"iE/RjDAisOJCokeq5sj0xSz2w/mBznA0Rwll90iQKRGERUQiXIyAJgvEcErQVPAUqTlB42L0MUpx1h2y",
	"uzlBUyqksuuIyZQyEqMJiXhKJHSLyRTniUKPc8IQ47YlDE0lkhmJ6JSSGNb25g2sDp1yZnZCDt68GbIQ",
	"jTkbESG4GA/QnVggRp5UCVbOEGYLBC3Qrp1xz3UUWJFRQlOqyr05Sxa6o/6K4CvaPTr4fs+MIl1nRVPC",
	"89ae9lO5A04e8UKOB+gE/kAa/RoJVXjNUs+ecJolBFY4Ho8XOE2GzBzGwZAhhzj4G6Gw6D5AM5JSRsNp",
	"guUcob+gG7eFbtdMH2QOwMD9C6EUP42wUiTNlBygQ/chcvgeoAq+WqbmSYJTHCY8wsnSqfXhCylLKCPr",
	"wG98HhliGOjBz2EISx7FKjLBH2hMxABhpuaCZzQqLZHHJBmgKMF5TELJGSMqPAqPw4P+wXH/+4PvAdt6",
	"C+70iaQMnVyfowgniRygMeB/gIaBxf4wGCMuSr+XljYMxkMWdAJiNlIzCNsrGPyqGZFFajAIKlgNOoFf",
	"bTAIytgIOgFsmR6rvFfB4PD5ufOl0q+8E8Hzb50yaADA0kkqI1l8w4wadcEgWI67oBM45GvO5rAfPD//",
	"VjA8PvkHiZTmeNE8Z/dErGSuq3hqQicjGIOy2YhnhOGMjk7NoJadL+Wr0KiNsypNi25UYDsfgG3B6fU9",
	"NfPCCkWYoQkpeGSsjzllMXnS7JLFxeGpsUMz/WYM0bRdxhKX8AkDJZDXlD6RODzu9y2xFfShiEipsuzA",
	"Uga0Nr8oLGZEjRS/J0wO0HG/b37nD0QkOCt90L9LkmKmaLTRLK5xaCE1H/X+5SLRhDRXKhv0enB851yq",
	"wbv+u/4wsNRZJSu/wPIphR+DTlAFNhgc9yuH1AIXdILKanW7/nMncHDCETXQBYN24IKOn7u+uqB1yudW",
	"muBio3Of0jhOyCMWpDj5Vze35WMP52gk51jEcpQRMVJ44vhQmSQ+2BPH8nRChFYUTB+kOIoE0QJQEwZG",
	"jDwiGKNbxv9RJ9DMI83TYLDvV0SZIjNY+VM446H9NadMvT0C8KjUIxnwRjhJeFThkFOcSFIn3g+mk0Q4",
	"VzzFikYGVCQIjABkjHZlllClKJv1UiJmlM32NMAWhAnnCcFMw0DSCYnjr2RAZhDKZtJvxJkddzUPcrO3",
	"MSE/KNKgmA9NXuThX8+MOkhLigQr/edyxuRh2oQz+cbLWJOe469kgU7LCwRGNWT62z1ZSAe1pY8YPVAM",
	"sxEWiUWmSAzNFBcE7QoNTUpYTOI9LXcJe6CCs5QwhR6woHA4Bnr4/S568+avtuObN5WugOFM8DiPNEB7",
	"hmGNx+OJUzgwU9NkUUxsqKD1E45jBPtOu3rr78nCjQb/BSXC7wjyyvwAjW3zAfq3L5JEgqhBdZxn0EIO",
	"9ELOWtapFyWpJkEBC4rJA0l4ptvYFV1ppdVNMzaaupkdToAkChCNM23wCKrpnLAHPYHpH6KrjLCT8wEa",
	"X12ffTw5H51cn4/+evb3sf38E2gNAzT+6ezy/GPj84mT/wM0Pvl49/PN1fX5ab3RKZ8TQQZofHr189nN",
	"WenzkN0Sgn69BdxIdIkZnhG9vN92ezGPZM9gTe7B8jV1JkQRFPMo163gsK2SkZ56YLUG96FMcZI0JJj5",
	"WBFgWk0IPZmGh6anbmLZu9G8NhKGkxkJJ1iSkLDwYb97vJEwPFgiDMsLKcvDdoCrksn0BeO0vIj1wu+g",
	"JPzqq9lC+BEGMgHnar5eGJwxLwvmREtbw/310dY/cUH/sPLg5v3JqTkl+ryfXJ+3i4PCgH2pPMjuZyM7",
	"Slkl/ckNvFogFAZri0Q4OV8pCkqm/XJZYKzHDUVBAc0msqBo/b+6MDCm1NcLg+o4fwJhsIbbr5EV64TB",
	"t+b2BYHAesoGb4NHm48VFm3bH3SPC79E2cJuigz4WBkDfjksCZtZpo42kTWzTIVH3f1Wdl+x3Evsvg5w",
	"lQubr5oRVdwEpf4G2Jp4gB+hV7GAyqQG0Hah0sbw5wQnaj7KuFAVhn900O/XmeQ1F8ozcdOxlxIlaCSR",
	"JOKBiC6ypgyYLnqMqqECg9bsk+dOkPDZJow9oRM8HSV8Nqu4GzxLT/GTtWYk/YOMJgtlBEZ1FZf4SZtK",
	"SLfRpha2FgxlCHp00SdJYg1/TEBWMmKYrOII7BprnFVWtt//7vC7o/13B0cAhrHFjt7uf9d/9/27g4Pv",
	"YOGFkdY/enf83duNTTW/sJVWpFtY04osySPDO2NrT0rKZglpMSn3q/BuDilROMYKr9vOS9vunE059KNs",
	"k60zAC3dOjQhUy0FqPKikiR0RieJNaC90arNUvBbSk0jhneh8ynKmSSq44QrnGLOCPo9x0IZnLYdsgrq",
	"Dt6+Ozo8Pjp++zIEOkSs3mqLiDaHwT0hmd1es6/opLpsiR5pkiDGFRIkziPiWqIJSfgjUnMqUcRzpqpH",
	"4kXrEWRGpRILo7rW1/Hp5kIDr/kJcDDkmhe6IlNTLFIUYzmfcCziKovRqrAc9HquX9coBF3Kew/7ZeiD",
	"dS2nXKRYadgFLZRTqQRlM7OQlCsyijhThKnN2ZWMBM7K/OoGBjo14xTMS5AssRr0aIoj8ArX0fUzf0Qp",
	"ZgtkG8OdEsHR3NKBnPM80WoiSjFlCmulsbKHhyXudPzC/RT4q13GZpAqUsywq/VzN3mbei4JFtEcCSK1",
	"VuxnaCrqfgWb+GzsqL/nRNDV2rqHbRNl3TfeyqfsIQeVJQK7PSRsltAWFcp8rmgxpr/rET4cdvsvM5fT",
	"pwmmoR0OLM2HfdPgBb7j6jrKykwLvFXFxnRttZbdGG2gBkv8z6tcy63Kk5EDEedJzB+ZZtiUx02yPbUN",
	"kGmA8FTLEkOyhUmJdqXCQvWk4lkPFI29LvoRuNIAxfasI8OQUELvCdrZT3c6aOewL3c8VxzAr2hXS62U",
	"slyRvQoHCPbTBner0rqiKel+sPPBKjNCovlI8ZEiT+pr6B7nMeWe5m/v7laTu5k4VDyEKyG3ZzXqb1L4",
	"7d2db7yKyr0VvoKs/aSbkLVvvBVZV/ELBPg4pzIjYhOS3OTGpkS6xhbouQk0RZTsIfvzJiaRG2G/cV3r",
	"0TpA4y9flMBMb+2EnOjd1xzih2HQ7XaHgZ/gh2FQWfEweH5e5lazDcs07kFZ5kurDL7dRVILvrZwpwEZ",
	"j6aU4UQrizOBI7KUTTilTqsYlOU8l0gQHFNGpCwYgCC/51TAQQRd1w6umQI29slarnEsNdvYT6tc41ju",
	"1DjFsdyeVej12riL5RaKh8taIUZ5AdvK80O3PiXobEYAfMFNjMy6BR63ssVjzRan9MHxRVljjMfbM0bF",
	"BZ6RdZzv1jQreJ18xCId6RO23sf6fpFhKYlEN3iqwGAhTOZW5QGdv4NybcahmAoSKfQoqOZolElFcAzG",
	"7DRP6j4p4HiKSKV7QiiSNwYZj0m7e9Yd9TXrtc1GWgd2fzeNdZWsFRl3F7fOPnwgQgJC6kfqnCkiGE6Q",
	"bQFmIWj2lc3td/vgFamp9aDQGnoKBr8W1muxt62K+RJXwxJDfcVN8G8tPONCs6LqmWmExGk2NIqpqJyf",
	"wKw7ngT1Q3TDubLng1vbCieJc57qFSO73qp1teNGrHGG0kQpZReEzdS8bEQsQa+Hum3ZFY9AY8FcRHMi",
	"laE9zbpX2h/rbLk6V8q0gWY8sg4M9JHHBJ1/QLtz8mTZy57GCVUSabM1l0aJMH5nTTT24phpNqXHo0xx",
	"UBOiJJcKbKqSONtvEz7H/b4+pQdLvh0EneBwybfDoCmAavhvQWLbTtQCJRskd2LCEilD2AYLehWrcK23",
	"RSpe3TiJj7DWFEqxY6AffZLlIMaxVog92ssj1y5cVkZAVse0sVRjtGuWC0M3YVpyD9QdsisTWgjepzKo",
	"XLTNUtjjZUXQ6A/lANciEO1Ft1uwVz4ks3KR1tw9vbvO59KCwtI1VoqzNuJpC0x7nSs5H1n3guFudF83",
	"VJsqdnvoOAtOkqspBOBt6ME5LDAtSEyYojiREKRX48p5dE9a1J7bQ2Q+GTJ41EYrur29Q1OaOG+cPiOa",
	"k8QVRpsuQsNrQzs2iBjHcN8eVvjvYctmZYJM6VMTpKvM8E2UYTVHphXoAUDNxMG7S7qzbsfJgV5xS9fb",
	"2asAWvqyVsoSFmecMr0Yu6omF2rjS1YmvsfRPWFxVfQZzb7O2W0PNDFdEAzZCQjLUw2I6yQPNQTFYtzv",
	"DWyukcqbOL5ri4DLD2uUrOrWohRs4W1vTioP1/Yx9FLfPANt2/Y4ba0Zv09EC1Fc64OnOLq7uEW6BZ1q",
	"JYsATVSOVk8f0Z7iPd2qm5G0bWfuyWL1FPdksWLoe7JoH7mNkzQ9GebmtfBntHiASmIE1ATTBVwVu5+N",
	"cbnn7eFu6UoebuBL18aUJDGIm9otb+vtu3U7XILJ/uZN2WjXv9/mWcaFIrE1qKRuk2aHHfSIHzrokUzS",
	"DuKzWQdNExyh3RQ/oYPjy/d7pvsHHkEP51rXVr9Wvbo2jCriqbk5nuU0JrJX9edU1aGmLf9cF5MWB23M",
	"DHBpEdZFP+IkkUD0evereGpHU9uRAm219dZCT6S/aj1wyWzvT27PRlpNXDbdOhXV4qPM48pujipA9gDZ",
	"OxTFtXLafelhrhzjQlZyRjaQmutpQ4vN7Ub4GxGKPH3NCHfGCi0N8VtTehc+nRc4Mq9d5zq/9KP+pmVa",
	"7faLgUpYVTKNdcYqTsyuic5ItH2vpbP3M+rtBFPeDVF8C63KGSFJIBRXdutE74AukniAbsc+lgS5g7Xr",
	"z55J2nmALdENf+J8lhB0mvA8RreewO/Ik0K7ZufQybnpZZ0BuhvIM2T3BYIHaEQ8J+ygz/jh4G8kOuig",
	"n/P3Zzd3eyv8py2O0U2coqscouPxuMqevpHDcPVZajCeuzmpnIsSqTudxjo9wWOiyFNQeG1+a+EyG5DK",
	"BrLMbWNZmLVsYfU4f5JEoqT1GIBvq+r7p8yaf41DDLINxFAN84qyRadteztoiiMy4fy+94gfDh5IdGC3",
	"falM/Hzyt2q4WwddXh920I8XJ6cddHl00js5Oa0KxVtC/MIqMVKvebBaZWSrzHKgaNnVIrZOPt79ePH3",
	"0d3ZzeX53atJrgoA/h7AySkwhpyF0bJ5O3sQkkHSTC06+pxLd+HyYtlWFyUbHO5VDM7TYYnTFYf7JPOO",
	"Q+dVQyUDEu2efLBBsdUAWnvEfyRY5YKYw6QEwSlls44mDAzXzBS7+NpOKbAly1mkcvi5XUmL9EK6M1gV",
	"aGhVSgOFrXpEi5hgM8eoNEcwUCInnSDBbJbjGRlF4NUOCAs/3Rq+p3djRGNjzc6iLLS/NQ9vVCBnpDXz",
	"5Rq94xQ4gjgV9O+3Vx+9it+qza1eREnNMutpC3Rux3K7q7yGj7Ia51DTngLkOiLd0VMH9NnRf8jw7HZn",
	"r3WJLv2mOl0uw4gwJXDS1BsrZ9t1725B1Dck4jMGbidL1A5iuABUo4SzmYZbkYRkc84W+h8piWmEk1FM",
	"I8MSlyyofHi+rALdNkTnH+p87aerq58uzkanF1efPoyub67+/ez0bnMTIJdkRNgcs4jE669qPkmCXGuD",
	"DeMRnhCliNBnNRc4WqDdiEslUcoFaU2LWsbKGomWJ+CVqaZbvsC/1Z7AaTxEMmiqrU0eqXVSI8oNSD57",
	"syry7+ZUFjxT5EwWDc3tRLIoO6HsnQQ413W/iEjZGTLdgufK3oTCxSdD5MneA9WUiS46V0Z2mOhsm4sp",
	"6R9kyCDTkP5hpWlcQAM3YoyjCEdzyAF7IGJOsLvG1zsNUXKPc8Ks8nyTM6abmlu0EGCOSZbwhT5nEu3C",
	"rR+cC9CG/85zFHO2oxAjPpOMslkPgPAz40hwKc39guv2iJlCELuFE63d55kNx36ialFA6DBhrwLbgE3z",
	"RFEDq72kkNY96eY3EYISwZl1AADEVx8//hLiKCIJERBS6rFnzn4F2owISaXSFAfNekV+nZ5Jr63mD8BP",
	"5mA2E0b99Z4LR2lLMJUkwy63WqOkPb30eRlprSCqzQ3hxqh2R+oJ0i8YqY3024zaaZ4kEFYygpC25Zdm",
	"bWKvSeh6OKeQx+QJSGNqdlQiytD7hDxoFf3znDCUCSL1hu+SB8IQtZrcXse1r/q9Dc0NoqkaIJlPp/QJ",
	"DFsTiRf7wXcksufCuMLcZHii5/Jj55KgQVQZCQpysGRhbu70ah7gPrQgPWkuZ6rMtxQDEMp7moXcus5D",
	"cGLrE6lx99zZyoGw7MAVfgRzBU08EayTPqecKcEToF81J8JgwlzuarZrCRAC2/1lL6AOhiuqcngcaoTZ",
	"mxazASlJuS1XAogsEAdtzT7aQeE8oQlXcz8ci5f0aMrATZG+hbPlBOXL3S0tAqvdPely2tvz11fwoxcw",
	"n9V+gAbELc6AlEf3JQ9Ax7HOZa6AzRjW66sYDba13Iydg9fVXWCWrVp3reRV0FaDWhuVp5ghnEgOzIco",
	"8LBvYQBXY8rbTPYXOHfdwVqx0RXvLjqjQOU70HHH+EyMhgNnrKbRdBAc85LhDTe+RlL3XLGK3hf96blX",
	"XaUDbU3sDKyp9SZvE/XR7eQSzdGpMlLTqjFn6B8kRj/f3V17axDCEGw/WVPmjKajqGaMRrWxYZ4llKQ4",
	"g7AXrdnY34ugGd1CQo4fTTAQ25w/oitIyEKPXNzLPV8iyU7sXVNaFQIsDtBtXQst4JwszNaZ3Au0O8lp",
	"okLKOloTBZgcvkGBPGELxOEMmFtlLU1tORoNXcJxvHKTi7VZsA1aLLgX+wN0afg9KGgGiwehiZ1Dd3cX",
	"0OpggK4L1e6aTLSdrGWOcaiF6BbU4WlCZ3OFYhLnhU/EpBGyKBdCd6axcYEksEwC6ubWvrKa1vjVbHs7",
	"NbKlEoVR1Gr1KDZwO5lLeHMAnFVV6MxNT6o2gcwkMTr/ePcu/D3HTAGN4CQJLymjF5fhxdvw4aB8vic5",
	"ixMSe/NryFwAAGVYLLroIy9MK0tnHXfTBkzF0gl/ZHDi3BGt3zw2gNg9fHeEYpoSJrUQ6Jh8fq1X7DX8",
	"X/og/R9E8Jro/o//6/8xlIe0OWhFwoQ/6eYfOWJE6a/a8CZSesj01+tcEPQTL9zKIAN+4pcXv1SPXNPs",
	"WGadt+z9exILHt2/bPNPPt8iO8DKjdftSo4zQ/Jl0cUFOj+5RIInRFbD0Eu+c5NJ0YWJioSLow7CKf6D",
	"s66iCjNTvAD0//DhYNBvdzDGPJJd/Ci7tmvE097ELKRnvEK9XBIBd8I9w5tC6Zzu3blKk3bVawmIVaq2",
	"EwUm8QzQm8uQYKnabpQnWEVziOCsCOP9NjEMbU3mYbU+jONWkCuYKZrqJmoueD6bZ3nZV13KeF3mJJ8T",
	"v+mGsM4/WInv1ZoleNjpoJ1Vm7VTC3dejs6W1LdZa+ztnT2m5rs/uW4B/lbPAu43og5KsUMtk+u/shEj",
	"j6OEMrKBIfTZ2j9g5wiaQdEk6FtEuVGW5coUGrNh5n4/l3jkNlF1ljICU2LlZXzA9F3GAtYFidRquqwK",
	"EmkyhdrZOOz2vZXYQfv9A+Dfcq9jG4KKlVA2y3Fik8uW8gd7+jRv8JGdxidUJX7YqJE7FJCMN3K3aaW7",
	"sSakyxLFNgwpuSsw78NK2syGKn439yyX11U2A5pLrEW02ThSk38E1/98ao+zPjGOAZVN7bJF2Bzf/vJ7",
	"TsQi6ARRgqU0sVjmrtL6BTXcv21myrRuRhO9rBSI2jjk9UiWglm0jt4AS4mcRVjVsHv28UMDlJ/5Iyjz",
	"WCtCBpMSJZzNNAuZY6MNpfjJ6uYJBFuWUfrx6uNZ0Alu705u7oIOzPHbS42lpRykyTte4pBsGdjcozTq",
	"pb1oLHMJ+jpjGcPqlcaCYJbXG+uG54qI1xmvXUd84WCtcuaFY1mT+3UGa7WC2vzVIENSHuOkrUpilGBh",
	"zXy4fjFcwiqPEjHOjHPaJumjXZriGaRt5zHlHaTFAe+g6w8/yr3OkDm/dFF+gEq2o5C3uHZkYYPV6hMs",
	"iAK5Cc7OsRI5GXecnaYEwUqWhsUSFQsDRyhY65Kw2BpaDuQhq8NMVNSFNIVK4Je70+FTbZ4JHEEil158",
	"F92VGu5IoyNQiaTScwoiM85kURIjikhmOs+JR5y2rADD0wTP0D9yqZWlJJF2hUPGuCoULGpQ8ZGbuyzr",
	"Xbc3oDgRBMcLZO1Kj0CrFY4LxPhzM+4M2diWzynqpR2EmSAPlDyOO2gcJTQL37i/ogRn4732HNt/SM6G",
	"7MuQITT0KsEwGKChDZEaBh3zEQA2XyRPSTjNtf0ZFgCGtoVr7z/oTvoIDNmzix1rhgRscz2wQgK8KNJw",
	"pfObLVMuz3x1S1c8xkUZ2tuaIoFacRTlUnEwfub80Yc8gaN/yCLOANtw/dCud6M7P5o2d34GgTzBQiK5",
	"YArDJc6QWWIH7YrnJfqckyQjwlm4bix0u5CKpNaH8ObNLQz15s2gPL5dhl7/rtNS5/7zPySoqcZe3TPD",
	"WF+ZHqeAWvMmHyKCk8R6ziyuPOI15d3dXXhVeoCOfUaqHV1T4ZOqji5IROgDASKa5kniMay5S2R6mLW/",
	"dyj52aDElniDGmwyEvnkZ5Umb96gEN2QlD8QZE5KT6oF1AKa2bsaw1dQpA+w2TOwn36+u7xwRdUKLMEv",
	"X7748ZE25F21lOfnShU2N7FE42He7x9GBgD4m4xhcvdBg+R+15C5WmZxLLVdZ8w6U09hkoCrJCH2vj3r",
	"oJg+dNB8P5y/7aCEWl7qQVC5YBJlCWSw6eXBPsGtpXiAQiE4xhOa2Et1KP1GfgfEnf2eY/073LtjQWXh",
	"znSXq3Ipjv5Cp2iX/I6kwiqXaBho7v1AhsHe8/MJ/KkJQHz50qNTi7mi0//U1t4wgOBezXj2np9vzd/G",
	"6iv3snn5hxrwlMQUA+w/EfZXqlDMVSZ4mikEn6wHUE8OzLsQV14yLVmO6Z6L5AeQXB+wwp9uzj3gxWct",
	"ULrQZpSLpKXB0Bfpseo+EB706P4jmw2D1j7yUHewlz89k1FkO2VsWacpTcig1/MJIM1JLPIQQuWY0E83",
	"F+hWM2rrl4SjNI6xwoMxCtF7LMnbI0RYxLUYhMvXTzfn0ks7aAmT9f6Rkdl/n0CHTrfbHbuDObbO7THq",
	"mb8l/CNEn8lEz2+fjiiC0ZzQBmswJopEJvrPjGZXWgRdQ9IZcEVI/nIkNQY86ma3hyEcawVKggvC2Z3a",
	"nPtxK8LvyWK85xFWVJyydY7QtQnfcRcMMOWbN+eg62hG98E6kEnc0ToKmLC7dGoVir0OqkgQj1g/ktbp",
	"DMN8Uo51EfCB2Doeeg2CMPMgB5YINsF310xNd78BmtdssDqOSbG/5H/QJMG2lecM5oyQKBeaJbiLeLdO",
	"tzIjIDLB9QbZcqAWOdL1daH6aFcSUi3UWTzksOfqQZ4kCX8kMZpzqdDjnCqSUKnsx2tBH7QAPL82nBGk",
	"m9aggDve3t78iLBSOLqX7uA5QI2TE15CkCUptd/vQ+ZPta2t9VBueNj3Q8L+Fl7+5qAH/aN32ZMJYA3t",
	"vrtjdEvIwHuNimpdkFFUUWP+4vAXhhE89DFkR8CsgQzvOGeGacM/bUQEQ3dXVx+ROdRo9w7uTK8EJUzv",
	"zRXY4+gjN/GJe0uZXzEF6Mtd4MHSs5z2z9aJcInFPRE/mPALymLC1A9H67rGBHAINVOGQ9XKrj5rA4lK",
	"WOH/sKcQVmuuTzVtR6qD5nmKWSjcibeoiImkM+bKsmIgWa3n55ECxQ/Qpzi6uLjUyhZC6Lx06frmzWE/",
	"fNv/36y3BKLHNAbhikGLSkO/EK/7OKdJUalMTzOns7keGIbV7QWZ25Pjoie7fpV/JQtUuSOy1axhdU5n",
	"NHQ7HoxhOfdkET7gJCcow1R4ZUIIvLB7glLYFDlAY61u/PqXw98GCNOO8ZJ10sRpMHd4kidYOKzp0bWK",
	"zaFUHdRTsBiTvjqr88zpthcXlyjDQproxRjlmjFJhZlWhW2PS4sZaXaqro8AEt4TRqZUyTJTveCPRJhy",
	"RlwqaTW9OI8A93pbcqnJMiWYSZRAaw2P7+FH+hFLrVlZm5GYoS6IlGYcabPnNWP3fS6hQq/TYFGIfqQK",
	"Yl1LJoGL8TQeNeAJfkU2KKQkXcvUMka72qTaG2gVEP3FZS4rjuAVJ3N1Lk0dmLHevXGJ2WgTzUtZQ3Bj",
	"tEuZ2hugc/inLSaT4QgKQnCBGIGgKeOgq3AuP5InyaJiwQD9CC54f31s3Pn2zACo5bEYZwQyHNDYUvXY",
	"dZCFUHUOep6rLFcOQU6pVlQlRK9D+VRsjZa/mRi3Wzi/pmQylOYeoH/HjKAP3MjA9sMOn1ySsXuliLiX",
	"iA7sD1q0ygE6Mo+QVDiRi2qnDN2c/DR488bzoXL5rBINeaPGiGpTRkP3dSX4Cvr38rB0VmB06yM3HuxC",
	"gsyomucTUCkV5yw0s8Lfrr4yR+cawz5Vp7UzTrJ7Iu8p68246VwxOO0uOavrg1uQiUIpcFmTJndm+7SW",
	"app0YUM1d/+AVfVLjBV8uMMzqT/8BUpAFh3xTD4/f/mixcbzcwd9+dLTDXSPIfvypWST2a3Syo/XRZw7",
	"ibMmkNfmaOk5IYZEA1f4GQYV+6/kgBhpW1A3vhY0IgP0b1++ZPqvEgiXhb0BiALtbCUAHj0NC6QFrBIw",
	"pUlPC2vNnkGtfDVnrUymDTFDQs/P7xd6cPcvb3oV1lqEFZlxsQDXE0lpnoLF9h//7/+Nrs2/nYJc6jzh",
	"8aIEZbXe+N98XXWbs1mrBa7lmb0TLGUvnZxD23rKeLWtcZOXG7osZmfagPlTNC2bCSfX5+aFtauLi5PL",
	"k9HPV7d3kEhqAqRMeWjob02hRgjP/v7R4ZGN/ThPtb2lqf9aEJgm11z4zLvFLHX9nefgm6LQHpEnaipa",
	"leJMd8FpYQDu2IsmEw3HFt7dtWeKfkZJbuSvmpO0SEmgDC14LkoCzKgVUHKm5KuzF69dBIkOE1e5S82J",
	"e+tC93LFS6BqGcmMO9gU7TIBybKY2bp9IQjaZT4qkpnl73fRqXkcyLexxo5xztWKyXstHFwZn0U5MdHa",
	"lOXFDNAXNAyMGwbG/ohT64oZBgP0a7fbNR99F/Ox2+3+hp7H632xQFPG3Xq5QI5Peu+qcztAA89FwcPd",
	"7fpWJYB1yy9GJA2DdDEyyDRx7wBxv7vfQf3ugf6/ww7SgOrmz85rW2ROnGLpCeySzkypGeP9wszE3NnY",
	"cRfqZvDXcv70EJ9k7UwWUdWTRSm8Coxy6FGc/6x8/ltOsYHG3wtUJ34PMSuZN73LMPDpFGoduZLZbEZk",
	"Mz31JW+XrL/FXB3Z3PRGt4Q22/r5pTxnWxu/U6RA6z8E3NUFnVJkkA0G6GwdHr3p9emGkR2eN6Nd87LD",
	"3kujPOoyYKsoj8ZFS7+/X4rzOOx/d2DiPNrDOTB1yaQxeejZwXBGjZ1eoKwZygmBF4HmrLp9qP/ZCTyX",
	"CgZ65k79OYUKmMueVNgiyMNtwqogjyp6Nw/yKK2lFIVgltWEpPCS2KCI4jBYZrP73dt3HbR/fPgWSB92",
	"ppyU3h5qVk0LXbL+agpoOWTLJY/u7HXRjas9qo+wT3nuIJedYVQO2IbaIz8rA0aWbO3qkJFNYkWWDLxV",
	"omkDSUWyKdpdsvBOUaW1gqn2NNdNEh1Kx7TIc3CzV5PjEZ1CbX9fcm5vfdb+14antEZrbMgGrYa4hPUZ",
	"n3VJbpnXgugDjmwmkpVjkBShMQZMMhdJpVZSWSm1r+osZYiMpzQqhU8C3blQN1NP3HxMsJgRtFuOhMNJ",
	"EupTkKQ+wHkZ4zTyyqTgg8H9P6If/DrbpXAdstbHYZbWMQcFu8keV4SilunNblOZ2DybqMMFSd51RNWj",
	"PlsWs5w0HKtYsqjOauqxsJepp53Tl87JS9J/HDDfmNjawpk2JTZT1+eFesaGJcduXUBOu5lYp9ClhNiu",
	"dJZjUI8P3zrKazS21LlOf1lXtGy9BiPvw263W4pG3e6hvy2UlXqhs9Yj/MJyZ0UqRkuBNfA4ljQUd5yK",
	"c7QLIujS+geKlv4GANQHr6sM0MHx2w463j8wkcQ1tWZt0LzjB0tRvYaZGUQu1xyWjrsZiwLFOKOlM7WW",
	"RRVbW7Coci1m02BHgmIFO9/c9LVV55rP4TSg/Pa8qzV8cgv+Zfov42GlFv5WCvvwJ41fH9+guU1NjbQ5",
	"AjGdgnO5KPEju5uxx5urT3dnNy80xWwRpDV8b6+ztCHwvM6QGYus16b/dtDvj4T19P8dlr68myzRUrwN",
	"3cXWptPGXS1ofx1/5KLGIleutMkprRW/Pbe0J2Etx6xu238e16RT5HOfIAHUxYzubcwC16FyJWJs2Ctk",
	"j00pEfV6XO2jav1uxRGra3rrIHxlHtMeubwhg3GZxku4SykRuRkifHlRKWGX1E0X4zUusi81Tylfnrf6",
	"iJdkL6NdW43hv5Vqq+x1W1MnjQ0F9VpMVnjbRCbp19V4KOX81gMXTd5vuaJLLe3XdP765N92Hll/3Lhi",
	"nS3NMjXa36UNSRYEmVijUul4myXt36R2adLjIk+6u0068gseZO68YhWEb1zl4OArCgG2OG9MKUCXf79s",
	"K4qdqDGYFvy+Mk9pTW3Ztnqg9wM1tY5dwhQRmaCShDOBY/IadQSdv076BGA0hjTgHqbe7MklEeOvdw53",
	"UEsgv0vA6EEuQw/SL/Y2LEto/Pohpj3Hox5IiBtu5d6MqLAqWRp1Axo+5cIlWiuPt97ZvLSaYYWk7aXE",
	"N6twiE4SuDSCeF3F0cmHUxOtwln40+l1majlf5lrWgPUhsj/jvYP3oX7R/13tVBj32ojT/bWBQ5LacoF",
	"JWqe2ebt7qAdkuu9Cx+JVPvLysZU6gteXJ2e3J1ffaw9olMe9pu6xJfyl2/mHF9ahXEtrrasxbgV/05p",
	"HCfkEYvSu1NXN7fLnm3AScIfRyXSXJ9jfs5ieK2gVG2rzJAjzu/Nc6G5mqM5wVqK7ZkEEROz20UfuSID",
	"dD61lbLs7yMu6IwyyLhhXGn0/brzZue39iqjrpOdoQL3r4GNLAnvzKsXJxCmYkvGBp3gl/DGqFokDj9T",
	"NddNIBks6ARXAEXQyCP62UxUeVMRyqlRhjSKvfZWPmlrIPmtE1BFUoC+mcdrfoCIufKKU6LmPK6v+Kez",
	"u6ATXF/dwn8+6f//cHZxdneml3StSfNWfzi5O/25ZW13d9fIjuu2A5jFioUtn/BFq7Kb36SzCyqhwIkD",
	"y52SBnjw3ps5MhAUqdvDW1+2R5U1mXauMp/J+oFStzGE6Im8yjJ+bcvPCDolX1LWLX/ZCgd24rW1eBt1",
	"7mD9VDrIWwmFPGVc1gml7WDbhsi/3EWJ1qXtI3p0agKBtNAQNn/IpL05InfJqVBfSx/6GDIYpHnCCsc1",
	"fP4S3nGFk/BUy/jt8JXip5F9fLCQ32+bj/b/zB8hnR3tUoYkiTiL5Z5NxZRwEOAh9Uw4O80eJZ/zBzls",
	"lUek31Yeh2950X9ZjZzmu8/GiK69/vzC8kh+9O3KI0GB1dCE24teKsMUi4h7MzKslUwasnrNJPSNSiZt",
	"BNju2zDBCyKQ+bna6f+flZSap8TEO73slNjSEksOxzetn9LyfnXZiWs/f3XZFDNO+43xFk9o/0kqoxQl",
	"3OCdzJhHy9+RZXk6IaJUgjYjpRBy44Njs+IXCOqt1vhZ7VttR99GtUyKA7dcBW8fvsn6eTZqCd/56Fef",
	"cniAPiEPmKlSUCcIHS2m4CGFSlBIxwswXMoltnGgMuKCyDYsbaWHNwnZXMS/jJDtJX4LIQevGNKgZ/NT",
	"vDhcpy3g4HXv1pq4bWK1KBFTKwqt2VtzDSZlBRCkuE//Nvdh/nysx882dQ6Wr6JcCNmVGWhR2xpJ/MQc",
	"ehaXOYFJXl8D+dJyCs0d2KbmzoY6zyaFVTakp5cNZZ3IrzJWq7x+2VDGp1Efauv6zu1coyQwLU24sPOS",
	"LzAmbBZh3vvf4cbUQRL2u2/fD37cf9sag/W8QQFrcCyspebVodLNZbWESvt6+T5ArIh49rHQ1mO5LPR5",
	"0/Oy5S3bKzLzury1Tr2KPly6bXh5KGbrbcu3Zu6tZLBdnHnhHbyxiDq5Pt/2loELbSInNKKq4vLKsJpb",
	"PfhaEFippMqbHPYBnQ9URvyBiAU6YzPKAIcDNJ6B89/ZSs6SR7FrTaCxvRzAGYWCLGM97k9CKzzudmPg",
	"rjfqPXGcUgapnlGSx0Sicb2FxbdBoIR/jrU2mVIpTQK4N81AK5ck1fZjFFpuYFXG/2kKnJa1/HrLKZYq",
	"7PePNrwGqVx+hDjLQm32aoMQLkIs3DZr6uTya8Yy1l0YGQdLuz2xet1/gisScz3S+gjQyfX1xbnx0I9O",
	"b84+nH28Oz+5uN3CNGkaCGvx0cKz15oFawf9872UtMREaRpqgkRcxP+lpsmSF8RPmJoLntGo/jL5pgWb",
	"XX9U0JnmtiV/Q7CVlV0M6AztZfayq0W+Hv1F3r7LQSsKs5kk/41t4yjBeUxCyRkjKjwKj8OD/sFx//uD",
	"71uPPdSs8jWNrSwtlricGlbO0zyIJM30unJBWjfO+I4FZjFPGZHwak0p2ma33+2H+91+NWdimnBs3143",
	"Ps/9Vv+nQbMjh/uWXeVZeI+kXhnoPFjglCij9DRxrgfJ2sz+KCG5bBnmtaDfRAuqHs5voActoVJbL/Ol",
	"NFoqqr45lX4tib1WCfAqXWC3A93lFBI+7A/6r1/Su/svymsO81KYv5YiTueYFqUMarGhbESE4CJouUUz",
	"7c0Wi4XLZ2fkSblt4ULvUaTHH2htGyePeCEH6AT+q3uZ5oLMsIgTvad8iniuIp5C/J+bfoDuXFvOIPEe",
	"fi7UZNvYFpOqNE8Wuo/9YvpJ21zT1ghqr7T0ANkGH32nsk0MS9A2cYGhAgDzj2L4VrN42XaARf1C/mR9",
	"x6+kQNTc9G1EO4XbPhYtRhr8RLWMdG0+GBihYo/v9FpE+1+nw/A0xSwORZgludzUtb9CV6mP16KpE0lY",
	"RLbBt+vzajzyXzrSV0L/tTy7hT1sW8992chg7dXHX+d7XTKYcRm90mDGV/1Kg1kn3GuBBrlVrziYya54",
	"pQGXqLwvHG2pmfvC8drlXVtt900vhtbRzOtXwF4pcGuP0jo5ddA/elcKGM5UeNTdb83xrDHcfve75w04",
	"w2rHfzvAr1snxRsY5XuC4uoAqqdsoRi1c6btfNhLlu3qp2ytIdWqf6x/Vf1rymd8C+/NxpqOjfY96B6H",
	"0wTL+Vpdp4TqtTHE5VFfq7jGN7MxD9bK/oN/OhvzxUVGvr1Dp10t2C4m5E/sylkTb1IlJ/h+2D0cfNef",
	"/ImPvzWSm9EYd3fX3gbzJnsRdmpKBxahMRFOEnDl++n2l1HKPyO5fdsgoa1U3e2qh7ySe6JWzeJbuCf0",
	"adeUtt2hDw++gY9ic0ntVcmvrGFRDPTKXohXxOqfR6D/2ZhDSz2Q/xTm0G66bl+e4xWZRK2Iwz85o9ja",
	"mVl5HxIy7htlHfxz8eZD8TpXmktIMrP7E7cWbljBSMwwTThMTX0ITa5CYpSAKU4SCDzQZic8/rQpfHB+",
	"Ns+S+Rej+zpG92ru0k1Z0A1RYrGM6cDHFgdOcV8FKmXQfOc5uufT6chW/aHOq2JFbiPn+dK3M289PxkX",
	"FcUJskOtRMZxq0Zb7AJlVI818mBV8xj3+80srnPTxU2PYpJgSDxKaZJQq19XNOl+v5Vt4KcRVvowquqk",
	"h50NQnc09n3v8u731+nwet4lyz3st6zXzb5uvZtknm3nQt4ygnU7Mfft4ks7/7WmbUGB0KEmRhh7EjnT",
	"BmHvJ5KmODwMrz5+/OWf1cQt7+A/rY37tbpm+93Sy0uq1P2Vso0GX6v+xnpH8atVp/hzBf1t7UYu1vLt",
	"vMj/8iD/ae++EzrBU5PPWbmEzGPKT/Wv9rmnlup55oMLC46gnIHuhtxozVQR/kBEgrNRbPmFVzUqA5tG",
	"yDWqaxVoQtQjIaw8W/mxpv6S6jSPlMX8cfXcn6HN8qnBNqJPJA7NaLUVVx7Z6/fbIXnebitW78I1EaEv",
	"CNBgxX4n0Eli3x811dV8XfQQ/UEE7/GUKkViBI+vmfd9oS8Rrmq5bO4mrH2Ty+KND1klvXiLtOIy5yyn",
	"GC+hS/KkvgLsO/Kk6lCruSByztuyNkFAxmCv+lbF+9u24F9xgFZygA3Ntk0B34imzYPta0l6mbT72CLl",
	"bB9PyJEWcVEOuoHZ0S68jSz944PuwTqEIV/MtEITnrMYw6tj6IolC1PqZrKwJArPZNpjLNuPgn//rcVT",
	"45+GM8IJ9kxmCVXmIWp7hTwcsuGQ7djXGAWeCZzN5d5WAJWkHxYzopYi8w4+NzUHfeZh3O35TcJns2q4",
	"SLued2HatTAZp0279LDGEUnIg1FTNiO4OkQX0F1vllqYMI+XjXML3bdEx4WDvVCxKJvyhlrl0PNAxIRL",
	"qhbIrLoI9IjJJJ8FHdf9EQsIXoHY1t/K2pZt0Bq2sWpltbrbIqUMJ0sBNY8Uuqf9ALVdtOO67dj6nwkX",
	"pgYLZ5InpIN2/iG5Pe2lN0e18t1BOwmfTVO1U7jqQjKd0ogSprRq/kPpaU94lIBndiSaWGbtkFUCX08Y",
	"aO1djx10At2tirBS4xVIk4fFGa+WEqtJNciyG92TRasue/L51pVZ0dbG+Ycu8uX078lCKi6Ie9wU1kYi",
	"QRRKOL/Ps3pO18nn29HJ6enZ7e3or2d/H51/aE3o8g+GEFXVy83TPCYr8J4sQhq3ocD5KFpYXOUh6eLd",
	"Esva5GEXp/gPzvAjZHTuIC70Jrsyo9/3+32zgZeUnV/tVXPkap2NhX0BT4WWbewCToOpUYH/duRbhBZ7",
	"8LUbcHt2enN2V9qHF2yCmaS0F0HrAiFX1XD3ZcIXJ8isEtq6ixBNUCTNuMBiUc7r3WrtbWDDLKGBqC3f",
	"WpKRlMnaol82f/j29qJ3d3ELc98eaq7BzGPnsvbKK7Q4+XzbQeZ15aIcsz9K9SJhq/m2jATOanJMEabc",
	"q98rawuSeKQPdJs94B7tLhd30221CS1759fGJEgou/f1oiRkTELFNigbCO1lubgg2iVPEcmUeScH3gCX",
	"+nzBO+Aj++OIZtJVedurlSWrlneLYtat/rL//UG33z3o7r+szB08O78hMnRb+8ovcfYRPGgP1ergKXp4",
	"FL+OFJijWnHxx1JnbYHgieRJrlV6aGvZUu+TJEL2Yqxwb890MrPoLvaxe/vqsO2RLkL7e57BBvXq+CyP",
	"qRlVo8N2eGzs41r6ea97+CKB5tlm/zy8wGxGJNrdP/iu29f/673roP1+6e/vDrr7b+Ff8F7H9/qf78y/",
	"33bQ/tvvuwfHR/bfe60F+NzhdRk2I+fCr94ENLxJ1sE6hVSkmD7QOMel0mk8s44ZWfLBVmrVbXQz4aHT",
	"GvRoslCkfiNz9O74u7fLrylA8+ZTD5hRaaA4OmXIDFiCqjTeijJ6pRoi5te3Rw5gKKs8ai/iawKT2+GE",
	"fuiRxmremxMo90cZyugT1KA2xZrRI00SNAHnIDzHX4bcRj2vxGguiRjhGWlTCTQhhCczKMYFFRNha8Gr",
	"XuJvlfK5plzOh/e9/W5/pywm0S1PiX1Z1pPvZ3pPMxJTvIcEAUegP/WPVM31YcKogKIqtMpTtUZXbCMh",
	"9KIKTXCZ3QNLLyRuvYw3ib3e1OIh0cZ9+52Sf63XPZA+p7I8Dc6yhBKN4E2ulkplM3Hsnky+roDSrDDd",
	"XKavkcntW7tkhX5h93MY/NsXo2YMQIt4HgZlr1exE9JK4s0NuA1l+rb7fkNSrogda/NrDQHdPNuYEmXf",
	"eTAfrj/82LFtLvXxdv+4I0/K176Se1141VryhMZQnlhrSaUyLSAz7fI0DSl4l8J6KYip9aV11zxDejPw",
	"zBU3LA4yuiEgNjXcVyImwr1FfObqwoxLM/4wDLQqMwzGJTc0ZR5ieIv4R3i0uHQ6HyHNbmyEpByjWcIn",
	"WkorIhhKsYrmROrTDY9v6DZDdthFY8sCR/JwXBptyI666ILMcLTwcScDNHbrqzaWaFd/f8RCc3Bju9CE",
	"qsVey21SMV9zg10JncoGmJuRxzlhiHELen1dVY6UCZpi0aruz5XKVlHkC4mglW016PkjTkmMasxLruNe",
	"pVQaKILFcBLijFZZWVCpeOnauVLDBSeqVpEeBO8JFkSgGrsInlvp12zZK6Pu9nBTxNXIcgX9d+tVVM15",
	"aDoSCj6pLeJ7sngOyrZ5m8HcYhFXRzF/PoNQZ0rkUpkCzUuntvqsm94SsFaBtVIQ2s/hG01K+SShUfgG",
	"fC0vB9PN6ECtCoKlyp3TwJacjj+LLGk5UZVU0Q2Ba3dNNTP0/H41blhLDNgcV8u8wE5taBdQZ5XILvqs",
	"WR0GRcSxbezG6TS6UamZBw8lSUikSL1YduMIpVoQmhO0ufH0n7m3jSzEqjSAgkb+qqwqDmqymj8QIWhc",
	"qXxUnCCblDfSMLu/mw73tlcPvNK91oT8bMutqzlBMZbzCdcyUs55nsB/HutlrW0uvOwOWVmf9+4ZqTCL",
	"ccIZ6clHLFLo30W3ROlmxm9DtVhkeEbiIYtJlvCFKQVllcO/5hMiGNGKjrEEudizykNaPPVkR/BFuZOF",
	"CQ1peU9hWYhWS3iWfzej5y/X7A3F2seT+huo3FoLISzWVj53x7X00gFn7EkbiAkOOsGMN18zeG/6I9cf",
	"ceGsLbNPeo800NVDGBOIenG1uODZwx8B1AEaW5jGUBnb/mNgeowt2m3/uLThY03T48rraUpQKPNn/kuZ",
	"BU6feHhGFOrng1KIHzBNwPdn5/tvZoYhi3g6oczoz1B0XzpLwr+hZ3VXiwr55g3ajUmmscIZVI+PkcIz",
	"uQfFTcYzPkZt9cx3Ta2QApQOOr3+BHVGOkgm/JFIU8BkrDdFjwHF4m9MwJvW3+0jTKGe7Ich7F3n6uZu",
	"GHTQFEvl+z8lWHeH4unol4uTlr5PCe78cnGiu95df+qdfvpw0ju9/uQeVQLcyDdvzIoA8ShEJ5qpxkRp",
	"a3hCKlitVGAZR3kMEHz82/mH8xOkR0c/XX8y37ggaQLDZVlC0CkX5PIC7aY4urq12HDXkRoBZkSV5WZJ",
	"EKFzd/0JHoqFRr9cnNhZTZsfuYiIR22lprpf0a8Ge3r5gAvzx4wPg9/0EHdi4c6JLRenUVAcSmW8xeWh",
	"BnrNfryBynLzD/PN/cvPcA1l1zVSwLWceE//qUWTHxbQVettcAWAWfRppSbxL/BV5Z0HzxC6hg0K0xjA",
	"7I/mL8MBNheCVsscfTth2AnuCclGOKEPtavD4+ZbuP6NCsWR7ua4t3WlaSlgniXEU20/Jlgq8/64SaEr",
	"3TJpA7j0yp/e/hTDw4LJAuXON2eGAfXDh+LwKaIMR4o+UKUFxCcJfCAu2ejABYfBcToM0O4xSinLtc2t",
	"t3h/rn/bR3OeC/ihr/9N8EyDazjtXk0QuoES/MfCt0EJvXeZgV4WmtGgJrcxsZOFq5FamWHIDBPGrtJe",
	"5alDuIbFQuUZMFpGHojwKKmVOjCb1BLiOHv5/XhxMiAGx7/9OPJP65SPSX99PHr5+UjPrb23z7n9h+zE",
	"W3llX6Dxcf6ek5zEKM/g3UH8NIIfwFToDpnFfx/EZs6gFhSJC6ZZw9rRMv+ywfGonCyzbpmKK5zU6MAG",
	"p+jtFWRGpRILpCfU+pB7K9E9K6H/HDIfli07PjCkg4iKuntWOdfC0lTJohIJAo+9dMyvBEsVChIRppJF",
	"qNn2kNHYZxeBswizRQELlUhzWmXez0nxPUGC89Sf403xeLgMj4YLjNLJZji0TGOXMnT5fq9c4d8i1AcK",
	"W1RQWeACZ5ngFh2ACuRQYcRcicBKRLR2pehOz0LhRRocP1CpITSThghHKte7DnAPWS7xTIutDOQZZxbx",
	"+nAa8yDFC39vSzVTeIqIRr6eAoIh9NLgWRetZ88kjQlqnEd7qcbg4UnK7NWF4En9dPe/f7tsYwqq2ZaI",
	"y3dSMIpxjy1hEaVDWuyapWL9bZonSQcx8liMq3eNPhB03D9Etzao+xMrNCCQxpBYFJ6AWDAupuV7aSYr",
	"7ShEYpHpVCsXD2vgH+b9/iFB/Rpul2Xr6A0aSSWwIjNnty3xWbnQFpAIQSfQYiXoBBDDRuLWQi3NUM+q",
	"aWAnLluf6BJnslRGXdqXsqho9CokMePKBJxTiVKcARWCGWl9pH4eE6zIGSp0B9D7zqelXwwKi5d0rCDd",
	"G6CyJEW75oKQoZhoM7RjqdTKfs3H9hpD/wCSdlCVqnakQnx2KrITVG/r5zB4mWNZLGloNmQYlDFgFgVs",
	"pimcd7FEGRZwC54JYudw7atiu4PIA2HmyLVgKKOMlfUngBUYEEhHiVL6pFdo1qs5CqDQ8gWbIyBxSlDG",
	"G/zgS/D+5OS8N5kR85C3f3x34M9gSoWa96I5Z/eLMNUkr2zbyqNH+8HAHNc275gBZhRTseSWyz8KDHwL",
	"U1YU15b5xH2FIE5nf4KXyZWAl+WX/42Z8aWY9Ln0DLFW4c8aL/cWxk6lmxO30OvUuQjWdPKyG3rdVJ80",
	"WNUt4jNG/yg6wr9Bb13b9VFQ5Trekt8PbsnvyP1a713VYP/PXtd6m3qunXv96YFmROwVtb2J6pjKnP7R",
	"NghZLQKTacnAriujjXlaI/E4T5oSaL+zNF64VX3MaEYSyoiJeTVeBHSGo7n/AhQrhwyjiGcL5xWClh0k",
	"OZrT2ZyIcqR7ygVxusgkV/ZRRv3rkJWAKJ5wNE+D+gUhn7YKUFkm7ZQEyoyCYFQTPm0K+LqsaZM0ltEs",
	"f3myxvJt+wrfajXG7uZEkhZrhKbgvVUkWRj25cN89XCyg/ADp0Bn4AjySQgJVoRFXrhYiKwbEnzMSM25",
	"dR36c14i4uJiuZ19DQMNdptMLxgsMGLOwj+I4FUDDuas67O/LuOUrgZbL0poFj5QZV4xz/QyDg+2M+kt",
	"gkaV1EVnczdfLfN2BjXPPT1iqvxbOQbVisMVaEIU6dgLe71Cq6Xp9rrzSlP5sC+NC2Q/Nf8Fs5hxlznZ",
	"QSUT4MYpSUaNNRWJqfRZloUmd4R+woo84gWyAUJ1jnHYb+UR8rD+zO/XXaDUUqGc+7iZDPX8bAOz1wQC",
	"mKlN9KJ51DLWphWd5FrzvCeL0MQ4m0gJLbDt+9uSYBHNkX3NRK+dqlJIC6pOcwvTmKKAJn4o6Hf73X2N",
	"I7tQjcRuv3sYdAIbrsfyJHn+/wIAAP//JS9+ob8JAQA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/ai/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/audio/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/embeddings/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef4.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/middleware/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef5.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/reranking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef6.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../pkg/generating/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef7.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../pkg/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef8.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../pkg/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef9.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../termite/pkg/termite/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
