// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package common

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/antflydb/antfly/lib/ai"
	externalRef1 "github.com/antflydb/antfly/lib/audio"
	externalRef2 "github.com/antflydb/antfly/lib/chunking"
	externalRef3 "github.com/antflydb/antfly/lib/embeddings"
	externalRef4 "github.com/antflydb/antfly/lib/middleware"
	externalRef5 "github.com/antflydb/antfly/lib/reranking"
	externalRef6 "github.com/antflydb/antfly/pkg/generating"
	externalRef7 "github.com/antflydb/antfly/pkg/libaf/logging"
	externalRef8 "github.com/antflydb/antfly/pkg/libaf/scraping"
	externalRef9 "github.com/antflydb/termite/pkg/termite"
	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for StorageBackend.
const (
	StorageBackendLocal StorageBackend = "local"
	StorageBackendS3    StorageBackend = "s3"
)

// Config defines model for Config.
type Config struct {
	// Chains Named chain configurations for fallback/retry logic.
	//
	// Chains are ordered lists of generators with retry and fallback logic.
	// Each link references a generator by name from the `generators` map.
	// The first chain defined becomes the default when no chain name is specified.
	//
	// **Chain Conditions:**
	// - `on_error`: Try next generator on any error (default)
	// - `on_rate_limit`: Try next only on rate limit (429) errors
	// - `on_timeout`: Try next only on timeout errors
	// - `always`: Always try the next generator
	//
	// **Example:**
	// ```yaml
	// chains:
	//   default:
	//     - generator: gemini-flash  # Reference by name
	//       retry:
	//         max_attempts: 3
	//       condition: on_rate_limit
	//     - generator: ollama-local  # Reference by name
	//   with-inline:
	//     - generator: gemini-flash
	//     - generator_config:  # Inline config
	//         provider: anthropic
	//         model: claude-sonnet-4-5-20250929
	// ```
	//
	// Then in API calls: `chain: "default"` or `chain: "with-inline"`
	Chains map[string][]NamedChainLink `json:"chains,omitempty,omitzero"`

	// Chunkers Named chunker configurations for text chunking.
	//
	// Define named chunkers that can be referenced by indexes and API calls.
	// The first chunker defined becomes the default when no chunker name is specified.
	//
	// **Example:**
	// ```yaml
	// chunkers:
	//   fixed-500:
	//     provider: termite
	//     model: fixed
	//     target_tokens: 500
	//     overlap_tokens: 50
	//   semantic:
	//     provider: termite
	//     model: semantic-chunker
	//     api_url: "http://localhost:8080"
	// ```
	Chunkers map[string]externalRef2.ChunkerConfig `json:"chunkers,omitempty,omitzero"`
	Cors     externalRef4.CORSConfig               `json:"cors,omitempty,omitzero"`

	// DefaultShardsPerTable Default number of shards to create for a new table.
	DefaultShardsPerTable uint64 `json:"default_shards_per_table"`

	// DisableShardAlloc Disables automatic shard reallocation (splitting/merging).
	DisableShardAlloc bool `json:"disable_shard_alloc,omitempty,omitzero"`

	// Embedders Named embedder configurations for embedding operations.
	//
	// Define named embedders that can be referenced by indexes, templates, and API calls.
	// The first embedder defined becomes the default when no embedder name is specified.
	//
	// **API Key Configuration:**
	//
	// API keys can be provided via the encrypted keystore (recommended) or environment variables:
	//
	// 1. **Keystore** (recommended for production):
	//    ```bash
	//    antfly keystore create
	//    antfly keystore add openai.api_key
	//    ```
	//    Then reference in config: `api_key: ${secret:openai.api_key}`
	//
	// 2. **Environment variable** (simpler for development):
	//    Omit `api_key` from config and set the appropriate env var:
	//    - OpenAI: `OPENAI_API_KEY`
	//    - Gemini: `GEMINI_API_KEY`
	//    - Anthropic: `ANTHROPIC_API_KEY`
	//    - Cohere: `COHERE_API_KEY`
	//
	// See [Secrets Management](/docs/secrets) for complete documentation.
	//
	// **Example:**
	// ```yaml
	// embedders:
	//   openai-small:
	//     provider: openai
	//     model: text-embedding-3-small
	//   termite-local:
	//     provider: termite
	//     model: bge-base-en-v1.5
	//     api_url: "http://localhost:8082"
	// ```
	Embedders map[string]externalRef3.EmbedderConfig `json:"embedders,omitempty,omitzero"`

	// EnableAuth Enables authentication and authorization (RBAC) for the API.
	EnableAuth bool `json:"enable_auth,omitempty,omitzero"`

	// Generators Named generator configurations for AI operations.
	//
	// Define named generators that can be referenced by chains, templates, and API calls.
	// The first generator defined becomes the default when no generator name is specified.
	//
	// **API Key Configuration:**
	//
	// API keys can be provided via the encrypted keystore (recommended) or environment variables:
	//
	// 1. **Keystore** (recommended for production):
	//    ```bash
	//    antfly keystore create
	//    antfly keystore add gemini.api_key
	//    ```
	//    Then reference in config: `api_key: ${secret:gemini.api_key}`
	//
	// 2. **Environment variable** (simpler for development):
	//    Omit `api_key` from config and set the appropriate env var:
	//    - Gemini: `GEMINI_API_KEY`
	//    - OpenAI: `OPENAI_API_KEY`
	//    - Anthropic: `ANTHROPIC_API_KEY`
	//
	// See [Secrets Management](/docs/secrets) for complete documentation.
	//
	// **Example:**
	// ```yaml
	// generators:
	//   gemini-flash:
	//     provider: gemini
	//     model: gemini-2.5-flash
	//   ollama-local:
	//     provider: ollama
	//     model: llama3
	//   openai-gpt4:
	//     provider: openai
	//     model: gpt-4.1
	// ```
	Generators map[string]externalRef6.GeneratorConfig `json:"generators,omitempty,omitzero"`

	// HealthPort Port for the health/metrics server. Defaults to 4200.
	HealthPort int `json:"health_port,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef7.Config `json:"log,omitempty,omitzero"`

	// MaxShardSizeBytes Maximum size of a shard in bytes. Used to determine when to split shards.
	MaxShardSizeBytes uint64 `json:"max_shard_size_bytes"`

	// MinShardSizeBytes Minimum size of a shard in bytes before it becomes eligible for automatic merge consideration.
	MinShardSizeBytes uint64 `json:"min_shard_size_bytes,omitempty,omitzero"`

	// MinShardsPerTable Minimum number of shards to keep for a table.
	MinShardsPerTable uint64 `json:"min_shards_per_table,omitempty,omitzero"`

	// MaxShardsPerTable Maximum number of shards that can be created for a single table.
	MaxShardsPerTable uint64       `json:"max_shards_per_table"`
	Metadata          MetadataInfo `json:"metadata"`

	// RegistryUrl URL of the model registry for the Antfarm dashboard. Defaults to https://registry.antfly.io/v1
	RegistryUrl string `json:"registry_url,omitempty,omitzero"`

	// RemoteContent Configuration for remote content fetching (remotePDF, remoteMedia, remoteText templates).
	// Consolidates S3 credentials and security settings separate from backup storage.
	//
	// **Credential Resolution Order:**
	// 1. Explicit `credentials="name"` parameter in template
	// 2. First credential where `buckets` glob pattern matches URL's bucket
	// 3. `default_s3` credential
	// 4. Legacy fallback: `storage.s3` credentials (backward compatibility)
	RemoteContent externalRef8.RemoteContentConfig `json:"remote_content,omitempty,omitzero"`

	// ReplicationFactor How many replicas of each shard should be maintained.
	ReplicationFactor uint64 `json:"replication_factor"`

	// Rerankers Named reranker configurations for search result reranking.
	//
	// Define named rerankers that can be referenced by indexes, search queries, and API calls.
	// The first reranker defined becomes the default when no reranker name is specified.
	//
	// **Example:**
	// ```yaml
	// rerankers:
	//   cohere-english:
	//     provider: cohere
	//     model: rerank-english-v3.0
	//   termite-local:
	//     provider: termite
	//     model: mxbai-rerank-base-v1
	//     url: "http://localhost:8080"
	// ```
	Rerankers map[string]externalRef5.RerankerConfig `json:"rerankers,omitempty,omitzero"`

	// ShardCooldownPeriod Cooldown period after shard operations (start/stop/split). Format: duration string like '1m', '30s'. Default: '1m' (one minute).
	ShardCooldownPeriod time.Duration `json:"shard_cooldown_period,omitempty,omitzero"`

	// SpeechToText Named speech-to-text provider configurations.
	//
	// Define named STT providers that can be referenced by templates and API calls.
	// The first provider defined becomes the default when no provider name is specified.
	//
	// **Example:**
	// ```yaml
	// speech_to_text:
	//   whisper-local:
	//     provider: termite
	//     api_url: "http://localhost:8080"
	//     model: openai/whisper-base
	//   openai-whisper:
	//     provider: openai
	//     model: whisper-1
	// ```
	//
	// Then in templates: `{{transcribeAudio url="..." provider="whisper-local"}}`
	SpeechToText map[string]externalRef1.STTConfig `json:"speech_to_text,omitempty,omitzero"`

	// SplitTimeout Maximum duration for a shard split operation before triggering rollback. Format: duration string like '5m', '30s'. Default: '5m' (five minutes).
	SplitTimeout time.Duration `json:"split_timeout,omitempty,omitzero"`

	// SplitFinalizeGracePeriod Minimum continuous readiness duration required before finalizing a split. Format: duration string like '15s', '1m'. Default: '15s'.
	SplitFinalizeGracePeriod time.Duration `json:"split_finalize_grace_period,omitempty,omitzero"`

	// AutoRangeTransitionPerTableLimit Maximum number of new automatic split/merge transitions a single table may start in one reconciliation cycle.
	AutoRangeTransitionPerTableLimit int `json:"auto_range_transition_per_table_limit,omitempty,omitzero"`

	// AutoRangeTransitionClusterLimit Maximum number of in-flight automatic split/merge transitions allowed cluster-wide.
	AutoRangeTransitionClusterLimit int           `json:"auto_range_transition_cluster_limit,omitempty,omitzero"`
	Storage                         StorageConfig `json:"storage"`

	// SwarmMode Bypasses Raft consensus for shards, using direct writes instead. Useful for development and testing with a single node.
	SwarmMode bool                `json:"swarm_mode,omitempty,omitzero"`
	Termite   externalRef9.Config `json:"termite,omitempty,omitzero"`
	Tls       TLSInfo             `json:"tls,omitempty,omitzero"`

	// Version Internal version of antfly
	Version string `json:"version,omitempty,omitzero"`
}

// LocalStorageConfig defines model for LocalStorageConfig.
type LocalStorageConfig struct {
	// BaseDir Root directory for all antfly data storage. Defaults to 'antflydb'.
	BaseDir string `json:"base_dir"`
}

// MetadataInfo defines model for MetadataInfo.
type MetadataInfo struct {
	// OrchestrationUrls Mapping from Metadata Node ID (hex string) to its URL used by store nodes for enrolling into the cluster
	OrchestrationUrls map[string]string `json:"orchestration_urls"`
}

// NamedChainLink A link in a chain that can reference a generator by name OR provide an inline config.
//
// Use `generator` (string) to reference a named generator from the `generators` map.
// Use `generator_config` (object) to provide an inline generator configuration.
// Only one of `generator` or `generator_config` should be specified.
type NamedChainLink struct {
	// Condition Condition for trying the next generator in chain:
	// - always: Always try next regardless of outcome
	// - on_error: Try next on any error (default)
	// - on_timeout: Try next only on timeout errors
	// - on_rate_limit: Try next only on rate limit errors
	Condition externalRef6.ChainCondition `json:"condition,omitempty,omitzero"`

	// Generator Name of the generator from the generators map
	Generator string `json:"generator,omitempty,omitzero"`

	// GeneratorConfig A unified configuration for a generative AI provider.
	GeneratorConfig externalRef6.GeneratorConfig `json:"generator_config,omitempty,omitzero"`

	// Retry Retry configuration for generator calls
	Retry externalRef6.RetryConfig `json:"retry,omitempty,omitzero"`
}

// S3Info defines model for S3Info.
type S3Info struct {
	// AccessKeyId AWS access key ID. Supports keystore syntax for secret lookup. Falls back to AWS_ACCESS_KEY_ID environment variable if not set.
	AccessKeyId string `json:"access_key_id,omitempty,omitzero"`

	// Bucket S3 bucket name where SST files will be stored
	Bucket string `json:"bucket"`

	// Endpoint S3-compatible endpoint (e.g., 's3.amazonaws.com' or 'localhost:9000' for MinIO)
	Endpoint string `json:"endpoint"`

	// Prefix Optional path prefix within the bucket (e.g., 'antfly/production/')
	Prefix string `json:"prefix,omitempty,omitzero"`

	// SecretAccessKey AWS secret access key. Supports keystore syntax for secret lookup. Falls back to AWS_SECRET_ACCESS_KEY environment variable if not set.
	SecretAccessKey string `json:"secret_access_key,omitempty,omitzero"`

	// SessionToken Optional AWS session token for temporary credentials. Supports keystore syntax for secret lookup.
	SessionToken string `json:"session_token,omitempty,omitzero"`

	// UseSsl Enable SSL/TLS for S3 connections (default: true for AWS, false for local MinIO)
	UseSsl bool `json:"use_ssl,omitempty,omitzero"`
}

// StorageBackend Storage backend type
type StorageBackend string

// StorageConfig defines model for StorageConfig.
type StorageConfig struct {
	// Data Storage backend type
	Data  StorageBackend     `json:"data,omitempty,omitzero"`
	Local LocalStorageConfig `json:"local"`

	// Metadata Storage backend type
	Metadata StorageBackend `json:"metadata,omitempty,omitzero"`
	S3       S3Info         `json:"s3,omitempty,omitzero"`
}

// TLSInfo defines model for TLSInfo.
type TLSInfo struct {
	// Cert Path to TLS certificate file
	Cert string `json:"cert,omitempty,omitzero"`

	// Key Path to TLS key file
	Key string `json:"key,omitempty,omitzero"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y963IbOdIo+CqImm9Dkg+LpCTb7eaJjnNkWd2tbyRLK9Hjnm12kGAVSGJUBVQDKEls",
	"hzb2EfbHvsa+1PckG0hc6sqbLH9f75yJiZiWWbgkEsgrMhNfgoinGWeEKRkMvgQyWpAUw5+nnM3oXP+V",
	"CZ4RoSiB36MFpgz+wnFMFeUMJ9eVFlSRFP74N0FmwSD4S6+YpGdn6H3EKYlP9VgXlN0FT51ALTMSDAIs",
	"BF7qf8dERoJmeoZgEEB7BJOjCEDLBdbfJJpxgWY4SaY4uusJosQSJXxOo+6IjRhMIREWBHERE0FilFCp",
	"JOIzNCeMCKy4kOiBqgUyfTGL/XB+oDMcLVBC2R0SZEYEYRGRCBcjoOkSMZwSNBM8RWpB0KQYfYJSnHVH",
	"bLggaEaFVHYdMZlRRmI0JRFPiYRuMZnhPFHoYUEYYty2hKGpRDIjEZ1REsPaXr2C1aFTzsxOyMGrVyMW",
	"oglnYyIEF5MBGoolYuRRlWDlDGG2RNAC7dsZD1xHgRUZJzSlqtybs2SpO+qvCL6i/ddH3x+YUaTrrGhK",
	"eN7a034qd8DJA17KyQCdwB9Io18joQqvWerZI06zhMAKJ5PJEqfJiJnDOBgx5BAHfyMUFt0HaE5Symg4",
	"S7BcIPQXdOO20O2a6YPMARi4fyGU4scxVoqkmZIDdOw+RA7fA1TBV8vUPElwisOERzhZObU+fCFlCWVk",
	"E/iNz2NDDAM9+DkMYcmjWEUm+D2NiRggzNRC8IxGpSXymCQDFCU4j0koOWNEha/DN+FR/+hN//uj7wHb",
	"eguG+kRShk6uz1GEk0QO0ATwP0CjwGJ/FEwQF6XfS0sbBZMRCzoBMRupGYTtFQx+1YzIIjUYBBWsBp3A",
	"rzYYBGVsBJ0AtkyPVd6rYHD89NT5UulX3ong6bdOGTQAYOUklZEsvmFGjbpgEKzGXdAJHPI1Z3PYD56e",
	"fisYHp/+g0RKc7xokbM7ItYy13U8NaHTMYxB2XzMM8JwRsenZlDLzlfyVWjUxlmVpkU3KrCdD8C24PT6",
	"npp5YYUizNCUFDwy1secspg8anbJ4uLw1NihmX47hmjarmKJK/iEgRLIa0YfSRy+6fctsRX0oYhIqbLs",
	"wFIGtDa/KCzmRI0VvyNMDtCbft/8zu+JSHBW+qB/lyTFTNFoq1lc49BCaj7q/ctFoglpoVQ26PXg+C64",
	"VIN3/Xf9UWCps0pWfoHlUwo/Bp2gCmwweNOvHFILXNAJKqvV7fpPncDBCUfUQBcM2oELOn7u+uqC1imf",
	"WmmCi63OfUrjOCEPWJDi5F/d3JaPPZyjsVxgEctxRsRY4anjQ2WS+GBPHMvTKRFaUTB9kOIoEkQLQE0Y",
	"GDHygGCMbhn/rzuBZh5pngaDQ78iyhSZw8ofwzkP7a85ZertawCPSj2SAW+Mk4RHFQ45w4kkdeL9YDpJ",
	"hHPFU6xoZEBFgsAIQMZoX2YJVYqyeS8lYk7Z/EADbEGYcp4QzDQMJJ2SOP5KBmQGoWwu/Uac2XHX8yA3",
	"exsT8oMiDYr50ORFHv7NzKiDtKRIsNJ/rmZMHqZtOJNvvIo16Tn+SpbotLxAYFQjpr/dkaV0UFv6iNE9",
	"xTAbYZFYZorE0ExxQdC+0NCkhMUkPtByl7B7KjhLCVPoHgsKh2Oghz/solev/mo7vnpV6QoYzgSP80gD",
	"dGAY1mQymTqFAzM1S5bFxIYKWj/hOEaw77Srt/6OLN1o8F9QIvyOIK/MD9DENh+gf/siSSSIGlTHeQIt",
	"5Egv5KxlnXpRkmoSFLCgmNyThGe6jV3RlVZa3TQTo6mb2eEESKIA0TjTBo+gms4Ju9cTmP4husoIOzkf",
	"oMnV9dnHk/PxyfX5+K9nf5/Yzz+B1jBAk5/OLs8/Nj6fOPk/QJOTj8Ofb66uz0/rjU75gggyQJPTq5/P",
	"bs5Kn0fslhD06y3gRqJLzPCc6OX9tt+LeSR7BmvyAJavqTMhiqCYR7luBYdtnYz01AOrNbgPZYqTpCHB",
	"zMeKANNqQujJNDw2PXUTy96N5rWVMJzOSTjFkoSEhfeH3TdbCcOjFcKwvJCyPGwHuCqZTF8wTsuL2Cz8",
	"jkrCr76aHYQfYSATcK4Wm4XBGfOyYEG0tDXcXx9t/RMX9A8rD27en5yaU6LP+8n1ebs4KAzY58qD7G4+",
	"tqOUVdKf3MDrBUJhsLZIhJPztaKgZNqvlgXGetxSFBTQbCMLitb/qwsDY0p9vTCojvMnEAYbuP0GWbFJ",
	"GHxrbl8QCKynbPA2eLT5WGHRtv1R903hlyhb2E2RAR8rY8AvxyVhM8/U621kzTxT4evuYSu7r1juJXZf",
	"B7jKhc1XzYgqboJSfwNsTTzAj9CrWEBlUgNou1BpY/gLghO1GGdcqArDf33U79eZ5DUXyjNx07GXEiVo",
	"JJEk4p6ILrKmDJgueoyqoQKD1uyTp06Q8Pk2jD2hUzwbJ3w+r7gbPEtP8aO1ZiT9g4ynS2UERnUVl/hR",
	"m0pIt9GmFrYWDGUIenTRJ0liDX9MQFYyYpis4gjsGmucVVZ22P/u+LvXh++OXgMYxhZ7/fbwu/67798d",
	"HX0HCy+MtP7rd2++e7u1qeYXttaKdAtrWpEleWR4Z2ztSUnZPCEtJuVhFd7tISUKx1jhTdt5adudsxnX",
	"/QSZU6nE0mg49ZV9urnQy9HHDg46cs0LlYKpGRYpirFcTDkWcfUkao1JDno9169r5EaX8t79YXndwaaW",
	"My5SrPSaBS10GKkEZXOzkJQrMo44U4Sp7U+1jATOysf6BgY6NeMUZ1yQLLGK1niGI3Ae1tH1M39AKWZL",
	"ZBvD1QPB0cKedLngeaK1CZRiyhTWukVl949Lh/jNs86BIAJ/tWfRDFJFihl2vRrnJm/T4iTBIlogQaRW",
	"nvwMTX3Or2Ab096O+ntOBF2v1HnYttHpfOOdXI8ecpBsEZh3IWHzhLZIWvO5IuxMf9cjvD/u9p9nVaWP",
	"U0xDOxwYJPeHpsEzXIzVdZRlXgu8VflnurYaVW6MNlCDFW7KdR7IVhlrZFLEeRLzB6ZZOOVxk2xPbQNk",
	"GiA8U0RYki0sD7QvFRaqJxXPeiCPDrroR+BKAxTbs44MQ0IJvSNo7zDd66C9477c81xxAL+ifc4ISinL",
	"FTmocIDgMG1wtyqtK5qS7gc7H6wyIyRajBUfa0P3a+ge5zHlnuZvh8P15G4mDhUP4ebA7VmN+psUfjsc",
	"+sbrqNwba2vI2k+6DVn7xjuRdRW/QIAPCyozIrYhyW0c+yXSNSpjz02gKaKkNtuft9Gc3QiHjVs9j9YB",
	"mnz5ogRmemun5ETvvuYQP4yCbrc7CvwEP4yCyopHwdPTKu+LbVimcQ/KKpdLZfDd7hta8LWD1wXI2N1k",
	"r1bsPHVb5c0Ic1BJPX9AUzLThrASdD4nwAQEN6EFm9jEm1Y28UaziRm9d3xC1hjFm90ZheICz8kmTnBr",
	"mhW0Lx+wSMca45tdU++XGZaSSHSDZ0pzAkmYzK0KAFpxB+Va+0UxFSRS6EFQTeGUSUVwDDbALE/qpjxw",
	"AEWk0j0hgsPr0IzHpN2r5bZ+w3pts7HWCd3fTRtHJRtZ6PDi1qnV90RIQEj9SJ0zRQTDCbItwBACTbey",
	"uf1uH4zJmpoLCt7vORUkDga/Fkp/sbetiuoKC22FfbPmAu23Fhq60KRZPTONSCJNluOYisr5Ccy642lQ",
	"P0Q3nCt7Pri1NXCSOJ+TXjGy661aG3tuxL0qqZQmSim7IGyuFmWlegV6PdRty64YUo0FcxEtiFSG9jQr",
	"W6uPb7Jt6lwp0waLcWQ5MNBHHhN0/gHtL8ijZS8HGidUSaTNuFwaoWrcdZpo7H0b02xKj0eZ4iA2oySX",
	"CmyMEns/bGPGb/p9fUqPVnw7CjrB8Ypvx0GTIdfw34LEtp2oxZc1SO7ERHNRhrCNsfIqR+GRbAvwurpx",
	"EhBhLTlLITegL3yS5diviVYQPdrLI9f81GsDx6pj2hCUCdo3y4WhmzCtcJ93R+zKRGSBv6UMKhdtsxT2",
	"aVkxMvK0HBdYxO8861IA9spHslXuH5q7p3fX+SBaUFjy/qc4ayOetniel7nJ8AFJzxjuRvd1Q7WpJrfH",
	"jrPgJLmaQdzSlh6N4wLTgsSEKYoTCbFNNa6cR3ekRe25PUbmkyGDB23EodvbIZrRhEj0QJMEzojmJHGF",
	"0abL0PDa0I4NIsYx3LfHFf573LJZmSAz+tgE6SozfBNlWC2QaQV6AFAzcfDuk+6823FyoFdcbvT2DiqA",
	"lr5slLKExRmnTC/GrqrJhdr4kpWJ73F0R1hcFX1G061zdtsDTU0XBEN2AsLyVAPiOsljDUGxGPd7A5sb",
	"pPI2/sLaIsBnbJX0dd1alIIdnJTNSeXxxj6GXuqbZ6Bt2x6nrTXDnoloIYprffAUR8OLW6Rb0JlWsgjQ",
	"ROVo9fQR7Sne0626GUnbduaOLNdPcUeWa4a+I8v2kds4SdOyNxdWhX3f4hEpiRFQE0wXMN33Pxtj68Db",
	"h93STSZcXJZu2yhJYhA3tcux1ktLa4Zfggn76lXZiNW/3+ZZxoUisTWopG6TZscd9IDvO+iBTNMO4vN5",
	"B80SHKH9FD+iozeX7w9M9w88gh7O1aytYK16dW30ScRTc+E2z2lMZK/q36iqQ03b9qkuJi0O2pgZ4NIi",
	"rIt+xEkigej17lfx1I6mtiMF2mqrF19PpL9qPXDFbO9Pbs/GWk1cNd0mFdXio8zjymZ/FSB7gOydguJa",
	"Oe0+9zBXjnEhKzkjW0jNzbShxeZuI/yNCEUev2aEobFCS0P81pTehY/jGY69a9e5zi/9qL9pmVa7DWKg",
	"ElaVTGOdsYpTr2sutRNt32vp7P1uejvBlHdDFN9Cq3JGSBKIYJTdOtE7oIvcB6Dbib+CR+5g7fuzZ3Id",
	"7mFLdMOfOJ8nBJ0mPI/RrSfwIXlUaN/sHDo5N72sM0B3A3mG7L7AnSuNiOeEHfQZ3x/9jURHHfRz/v7s",
	"Zniwxp/Y4ijcxkm4zkE4mUyq7OkbOdDWn6UG4xkuSOVclEjd6TTWCQgeE0Ueg8Jr81sLl9mCVLaQZW4b",
	"y8KsZQurx/mTJBIlrccAfFtVXzhl1vxrHGKQbSCGaphXlC07bdvbQTMckSnnd70HfH90T6Iju+0rZeLn",
	"k79Vo4Q66PL6uIN+vDg57aDL1ye9k5PTqlC8JcQvrBJa8pIHq1VGtsosB4qWXS1i6+Tj8MeLv4+HZzeX",
	"58MXk1wVALxf3MkpMIachdGyeXsHXXQ+QyTN1LKjz7l0FxDPlm11UbLF4V7H4DwdljhdcbhPMu84dF41",
	"VDIg0f7JBxtLWI07tEf8R4JVLog5TEoQnFI272jCwHDtSrELS+yUgtiznEUqh5/blbRIL6Q7h1WBhlal",
	"NFDYqke0CKU0c4xLcwQDJXLSCRLM5jmek3EEXu2AsPDTreF7ejfGNDbW7DzKQvtb8/BGBXLGWjNfrdE7",
	"ToGjiOdMoX+/vfroVfxWbW79IkpqlllPW3xoO5bbXeU1fJTVOIea9swJ1xHpjp46oM+e/kOGZ7d7B61L",
	"dFkL1elyGUaEKYGTpt5YOduue3cHor4hEZ8zcDtZonYQw4WYGieczTXciiQkW3C21P9ISUwjnIxjGhmW",
	"uGJB5cPzZR3otiE6/1Dnaz9dXf10cTY+vbj69GF8fXP172enw+1NgFySMWELzCISb76q+SQJcq0NNoxH",
	"eEqUIkKf1VzgaIn2Iy6VRCkXpDWbZBUra+SnnYBXppql9gz/Vnvem/EQyaCptjZ5pNZJjSg3IPmkt6rI",
	"Hy6oLHimyJksGprbiWRZdkLZOwlwrut+EZGyM2K6Bc8VMmq27owZIo/2HqimTHTRuTKywwS12hQ2Sf8g",
	"IwYJWvQPK03jAhq4EWMcRThaQOrMPRELgt21tt5ppRfzsCDMKs83OWO6qblFCwHmmGQJX+pzJtE+3PrB",
	"uQBt+O88RzFnewox4hNwKJv3AAg/M44El9LcL7huD5gpBLFMONHafZ7ZKNZHqpYFhA4T9iqwDdg0TxQ1",
	"sNpLCmndk25+QeI8IhLBmXUAAMRXHz/+EuIoIgkREInnsWfOfgXajAhJpdIUB816RVqSnkmvreYPwI/m",
	"YDbz7Pz1ngvPaMvLkyTDLiVVo6Q9K+9pFWmtIartDeHGqHZH6nmlzxipjfTbjNpZniQQZjGGEK/Vl2Zt",
	"Yq9J6Ho4p5DH5BFIY2Z2VCLK0PuE3GsV/fOCMJQJIvWG75N7whC1mtxBx7Wv+r0NzQ2imRogmc9m9BEM",
	"WxOZFvvB9ySy58K4wtxkeKrn8mPnkqBBVBkJ6hiwZGlu7vRq7uE+tCA9aS5nqsy3FAMQyjuahdy6zkNw",
	"YusTqXH31NnJgbDqwBV+BHMFTTwRbJI+p5wpwROgX7UgwmDCXO5qtmsJEOKB/WUvoA6GK4oZeBxqhNmb",
	"FrMBKUm5rfIAiCwQB23NPtpB4TyhKVcLPxyLV/RoysBtkb6Ds+UE5avdLS0Cq9096VKB29N+1/CjZzCf",
	"9X6ABsQtzoCUR3clD0DHsc5VroDtGNbLqxgNtrXajF2A19VdYJatWnet5FXQVoNaG5WnmCGcSA7Mhyjw",
	"sO9gAFdjrNtM9mc4d93BWrPRFe8uOqNA5XvQcc/4TIyGA2esptF0EBzzkuENN75GUvdcjn/vi/701Kuu",
	"0oG2IXYG1tR6k7eN+uh2coXm6FQZqWnVmDP0DxKjn4fDa28NQhiC7SdrypzRdBTVjNGoNjbssYSSFGcQ",
	"9qI1G/t7ETSjW0hIjaIJBmJb8Ad0BXks6IGLO3ngK8vYib1rSqtCgMUBuq1roQWc06XZOmRs2v1pThMV",
	"UtbRmijA5PANCuQJWyIOZ8DcKmtpaqt4aOgSjuO1m1yszYJt0GLBvTgcoEvD70FBM1g8Ck3sHBoOL6DV",
	"0QBdF6rdNZlqO1nLHONQC9EtqMOzhM4XCsUkzgufiMm+YlEuhO5MY+MCSWCZBNTNnX1lNa3xq9n2bmpk",
	"SwK/UdRqafxbuJ3MJbw5AM6qKnTmpidVm0Bmkhidfxy+C3/PMVNAIzhJwkvK6MVlePE2vD8qn+9pzuKE",
	"xN78GjEXAEAZFssu+sgL08rSWcfdtAFTsXTCHxicOHdE6zePDSD2j9+9RjFNCZNaCHRMGrTWKw4a/i99",
	"kP4PInhNdP/H//X/GMpD2hy0ImHKH3XzjxwxovRXbXgTKT1k+ut1Lgj6iRduZZABP/HLi1+qR65pdqyy",
	"zlv2/j2JBY/unrf5J59vkR1g7cbrdiXHmSH5sujiAp2fXCLBEyKrYdkl37nJLOjCREUCwusOwin+g7Ou",
	"ogozk/MN+n94fzTotzsYYx7JLn6QXds14mlvahbSM16hXi6JgDvhnuFNoXRO9+5CpUm76rUCxCpV24kC",
	"k4gF6M1lSLBUbTfKU6yiBURwVoTxYZsYhrYm165aVsNxK810tZqa6iZqIXg+X2R52VddShRc5SRfEL/p",
	"hrDOP1iJ79WaFXjY66C9dZu1Vwt3Xo3OllSweWvs7dAeU/Pdn1y3AH+rZwH3G1EHpdihlsn1X9mYkYdx",
	"QhnZwhD6bO0fsHMEzaDWDPQtotwoy3Jl6jPZMHO/nys8ctuoOisZgalM8Tw+YPquYgGbgkRqpTDWBYk0",
	"mULtbBx3+95K7KDD/hHwb3nQsQ1BxUoom+c4sclWK/mDPX2aN/jITuMTqhI/bNTYHQpIThu727TS3VgT",
	"0lWJU1uGlAwLzPuwkjazoYrf7T3L5XWVzYDmEmsRbTaO1OTjwPU/n9njrE+MY0BlU7tsETbHt7/8nhOx",
	"DDpBlGApTSyWuau0fkEN92/bmTKtm9FELysFojYOeT2SpWAWraM3wFIiZxFWNeyeffzQAOVn/gDKPNaK",
	"kMGkRAlnc81CFthoQyl+tLp5AsGWZZR+vPp4FnSC2+HJzTDowBy/PddYWslBmrzjOQ7JloHNPUqjzNSz",
	"xjKXoC8zljGsXmgsCGZ5ubFueK6IeJnx2nXEZw7WKmeeOZY1uV9msFYrqM1fDTIk5TFO2orLRQkW1syH",
	"6xfDJazyKBHjzDinbdI62qcpnkMacx5T3kFaHPAOuv7wozzojJjzSxfp+FSyPYW8xbUnCxuslq+/JArk",
	"Jjg7J0rkZNJxdpoSBCtZGhZLVCwMHKFgrUvCYmtoOZBHrA4zUVEX0hQqgV/uTofPtHkmcASJXHrxXTQs",
	"NdyTRkegEkml5xREZpxJqu10cH1GEclM5wXxiNOWFWB4luA5+kcutbKUJNKucMQYV4WCRQ0qPnJzl2W9",
	"6/YGFCeC4HiJrF3pEWi1wkmBGH9uJp0Rm9iqI0WZqaMwE+SekodJB02ihGbhK/dXlOBsctCec/oPydmI",
	"fRkxhEZeJRgFAzSyIVKjoGM+AsDmi+QpCWe5tj/DAsDQtnDt/QfdSR+BEXtysWPNkIBdrgfWSIBnRRqu",
	"dX6zVcrlmS8K6GpuuChDe1tTJBQrjqJcKg7Gz4I/+JAncPSPWMQZYBuuH9r1bjT0o2lz52cQyFMsJJJL",
	"pjBc4oyYJXbQrnheos8FSTIinIXrxkK3S6lIan0Ir17dwlCvXg3K49tl6PXvOy114T//Q4KaauzVAzOM",
	"9ZXpcQqoNW/yISI4SaznzOLKI15T3nB44VXpAXrjM1Lt6JoKH1V1dEEiQu8JENEsTxKPYc1dItPDrP29",
	"Q8nPBiW2MhaUrpKRyKc/qzR59QqF6Iak/J4gc1J6Ui2hhMrc3tUYvoIifYDNnoH99PPw8sLVoiqwBL98",
	"+eLHR9qQd9VDnp4qxavcxBJNRnm/fxwZAOBvMoHJ3QcNkvtdQ+ZKQMWx1HadMetMfYFpAq6ShNj79qyD",
	"YnrfQYvDcPG2gxJqeakHQeWCSZQlkMGmlwf7BLeW4h4KZ+AYT2liL9WhYhb5HRB39nuO9e9w744FlYU7",
	"012uypU4+gudoX3yO5IKq1yiUaC59z0ZBQdPTyfwpyYA8eVLj84s5opO/1Nbe6MAgns14zl4ero1fxur",
	"r9zL5qkfa8BTElMMsP9E2F+pQjFXmeBpphB8sh5APTkw70Jcecm0Yjmmey6SH0ByfcAKf7o594AXn7VA",
	"6UKbcS6SlgYjX7TGqvtAeNCj+49sPgpa+8hj3cFe/vRMRpHtlLFVnWY0IYNezyeANCexyEMIlWNCP91c",
	"oFvNqK1fEo7SJMYKDyYoRO+xJG9fI8IirsUgXL5+ujmXXtpBS5is94+MzP/7FDp0ut3uxB3MiXVuT1DP",
	"/C3hHyH6TKZ6fltxvwhGc0IbrMGYKBKZ6D8zml1pEXQNSWfAFSH5y5HUBPCom90eh3CsFSgJLghnf2Zz",
	"7ietCL8jy8mBR9iJB87W/UHXJnzHXTDAlK9enYOuoxndB+tAJnFH6yhgwu7TmVUoDjqoIkE8Yv1IWqcz",
	"DPNROdZFwAdi61roNQjCzDsGWCLYBN9dMzXd/QZoXrPB6jgmxf6S/0GTBNtWnjOYM0KiXGiW4C7i3Trd",
	"yoyAyATXG2SrKFrkSNfXheqjfUlItb5hUf/+wJXRO0kS/kBitOBSoYcFVSShUtmP14LeawF4fm04I0g3",
	"rUEBd7y9vfkRYaVwdCfdwXOAGicnFJCXJSl12O9D5k+1ra31UG543PdDwv4WXv7moEf91++yRxPAGtp9",
	"d8folpCB9xoV1asgo6iixvzF4S8MI3gfYcReA7MGMhxyzgzThn/aiAiGhldXH5E51Gh/CHemV4ISpvfm",
	"Cuxx9JGb+MSDlcyvmAL05S7wYOlZTvtn60S4xOKOiB9M+AVlMWHqh9ebusYEcAg1REYj1cquPmsDiUpY",
	"4f+wpxBWa65PNW1HqoMWeYpZKNyJt6iIiaRz5qpZYiBZrefnkQLFD9CnOLq4uNTKFkLovHTp+urVcT98",
	"2//frLcEosc0BuGKQYtKQ78Qr/uwoElRuUtPs6DzhR4YhtXtBVnYk+OiJ7t+lX8lS1S5I7JFgGF1Tmc0",
	"dDsZTGA5d2QZ3uMkJyjDVHhlQgi8tHuCUtgUOUATrW78+pfj3wYI047xknXSxGkwQzzNEywc1vToWsXm",
	"ULoN6ilYjElf1NJ55nTbi4tLlGEhTfRijHLNmKTCTKvCtselxYw0O1XXRwAJ7wkjM6pkmale8AciTHkf",
	"LpW0ml6cR4B7vS251GSZEswkSqC1hsf38CP9iKXWrKzNSMxQF0RKM4602fOasfs+l1DY1GmwKEQ/UgWx",
	"riWTwMV4Go8a8AS/IhsUUpKuZWqZoH1tUh0MtAqI/uIylxVH8PiNuTqXpg7MRO/epMRstInmpawhuAna",
	"p0wdDNA5/NMWk8lwBAUhuECMQNCUcdBVOJcfyZNkUbFggH4EF7y/PjbufHtmANTyWIwzAhkOaGKpeuI6",
	"yEKoOgc9z1WWK4cgp1QrqhKi16F8KrZGy99MjNstnF9TaRYqGg/Qv2NG0AduZGD7YYdPLsnYPe5C3AMu",
	"R/YHLVrlAL02bzdUOJGLaqcM3Zz8NHj1yvOhcjmpEg15o8aIalNGQ/d1JekK+vfysHRWYHTrIzce7EKC",
	"zKla5FNQKRXnLDSzwt+uLC1H5xrDPlWntTNOsjsi7yjrzbnpXDE47S45q+uDW5CJQilwWZMmQ7N9Wks1",
	"TbqwoZq7f8Cq+iXGCj4M8VzqD3+BkohFRzyXT09fvmix8fTUQV++9HQD3WPEvnwp2WR2q7Ty43UR507i",
	"rAnktTlaek6IIdHAFX6GQcX+KzkgxtoW1I2vBY3IAP3bly+Z/qsEwmVhbwCiQDtbC4BHT8MCaQGrBExp",
	"0tPCWrNnUCtfzVkrk2lDzJDQ09P7pR7c/cubXoW1FmFF5lwswfVEUpqnYLH9x//7f6Nr82+nIJc6T3m8",
	"LEFZLdP8N1+O2uZs1kooa3lm7wRL2Usn59C2njJebWvc5OWGLovZmTZg/hRNy2bCyfW5eZjq6uLi5PJk",
	"/PPV7RASSU2AlKmqC/2tKdQI4Tk8fH382sZ+nKfa3tLUfy0ITJNrLnzm3WKWuv7Oc/BNUWiPyCM1Fa1K",
	"cab74LQwAHfsRZOJhmNL7+46MEUwoyQ38lctSFqkJFCGljwXJQFm1AooOVPy1dmL1y6CRIepq9ylFsQ9",
	"EaB7ueIlULWMZMYdbIp2mYBkWcxs3b4QBO0yHxXJzPIPu+jUvKni21hjxzjnajW4vRYOrozPopyYaG3K",
	"8mIG6AsaBcYNA2N/xKl1xYyCAfq12+2aj76L+djtdn9DT5PNvligKeNuvVwixye9d9W5HaCB56Lg4e52",
	"fasSwLrlFyOSRkG6HBtkmrh3gLjfPeygfvdI/99xB2lAdfMn57UtMidOsfQEdknnptSM8X5hZmLubOy4",
	"C3Uz+Gs5f3qIT7J2Jouo6umyFF4FRjn0KM5/Vj7/LafYQOPvBaoTv4eYlcyb3mUY+GwGtY6sH5ayOZHN",
	"9NTnPPmw+RZzfWRz0xvdEtpsy46X8pxtSfFOkQKt/xBwVxd0SpFBNhigs3N49LbXp1tGdnjejPZNQfyD",
	"50Z51GXATlEejYuWfv+wFOdx3P/uyMR5tIdzYOqSSWNy37OD4YwaO71AWTOUEwIvAs1ZdftQ/7MTeC4V",
	"DPTMnXoV+gqYqyrR7xDk4TZhXZBHFb3bB3mU1lKKQjDLakJSeElsUERxGCyz2f/u7bsOOnxz/BZIH3am",
	"nJTeHmpWTQtdsf5qCmg5ZMslj+4ddNGNvW6CI+xTnjvIZWcYlQO2ofY2ytqAkRVbuz5kZJtYkRUD75Ro",
	"2kBSkWyK9lcsvOODTauYak9z3SbRoXRMizwHN3s1OR7RGWJcFSXnDjZn7X9teEprtMaWbNBqiCtYn/FZ",
	"l+SWeWSF3uPIZiJZOQZJERpjwCRzkVRqJZWVUvsYyUqGyHhKo1L4JNCdC3Uz9bXNxwSLOUH75Ug4nCSh",
	"PgVJ6gOcVzFOI69MCj4Y3P8j+sGvs10K1yFrfVNjZV1vULCb7HFNKGqZ3uw2lYnNs4k6XJDkXUdUPeqz",
	"ZTGrScOxihWL6qynHgt7mXraOX3pnDwn/ccB842JrS2caVtiM3V9nqlnbFly7NYF5LSbiXUKXUmI7Upn",
	"OQb1zfFbR3mNxpY6N+kvm4qWbdZg5F3Y7XZL0ai7vY+2g7JSL3TWeoSfWe6sSMVoKbAGHseShuKOU3GO",
	"9kEEXVr/QNHS3wCA+uB1lQE6evO2g94cHplI4ppaszFo3vGDlajewMwMIldrDivH3Y5FgWKc0dKZ2sii",
	"iq0tWFS5FrNpsCdBsYKdb276xqpzzedhGlB+e97VGj65A/8y/VfxsFILfyuFffiTxq+Pb9DcpqZG2hyB",
	"mM7AuVyU+JHd7djjzdWn4dnNM00xWwRpA9876KxsCDyvM2LGIuu16b8d9PsDYT39f8elL++mK7QUb0N3",
	"sbXptHFXC9rfxB+5qLHItSttckprxe/OLe1J2Mgxq9v2n8c16Qz53CdIAHUxowdbs8BNqFyLGBv2Ctlj",
	"M0pEvR5X+6hav1tzxOqa3iYIX5jHtEcub8lgXKbxCu5SSkRuhghfXlRK2CV108V4jYvsS81TypfnrT7i",
	"FdnLaN9WY/hvpdoqB93W1EljQ0G9FpMV3jaRSfp1NR5KOb/1wEWT91uu6FJL+zWdvz75t51H1t+ErVhn",
	"K7NMjfZ3aUOSBUEm1qhUOt5mSfunfF2a9KTIk+7uko78jHdsOy9YBeEbVzk4+opCgC3OG1MK0OXfr9qK",
	"YidqDKYFvy/MU1pTW3atHuj9QE2tY58wRUQmqCThXOCYvEQdQeevkz4BGE0gDbiHqTd7cknE5Oudwx3U",
	"EsjvEjB6kMvQg/SLgy3LEhq/fohpz/GoexLihlu5NycqrEqWRt2Ahk+5cInWyuNtdjavrGZYIWl7KfHN",
	"KhyikwQujSBeV3F08uHURKtwFv50el0mavlf5prWALUh8r+jw6N34eHr/rtaqLFvtZUne+cCh6U05YIS",
	"Nc9s83Z30B7J9d6FD0Sqw1VlYyr1BS+uTk+G51cfa4/olIf9pi7xlfzlmznHV1Zh3IirHWsx7sS/UxrH",
	"CXnAovTu1NXN7apnG3CS8IdxiTQ355ifsxheKyhV2yoz5IjzO/N8Zq4WaEGwlmIHJkHExOx20UeuyACd",
	"z2ylLPv7mAs6pwwybhhXGn2/7r3a+629yqjrZGeowP1rYCNLwqF59eKk/JJ90Al+CW+MqkXi8DNVC90E",
	"ksGCTnAFUASNPKKfzUSVNwahnBplSKPYa2/lk7YBkt86AVUkBeibebzmB4iYK684JWrB4/qKfzobBp3g",
	"+uoW/vNJ//+Hs4uz4Zle0rUmzVv94WR4+nPL2obDa2THddsBzGLNwlZP+KxV2c1v0tkFlVDgxIHlTkkD",
	"PHjvzRwZCIrU7eGtL9ujyppMO1eZz2T9QKnbGEL0RF5lGb+25WcEnZIvKeuWv+yEAzvxxlq8jTp3sH4q",
	"HeSthEIeMy7rhNJ2sG1D5F/uokTr0vYRPTozgUBaaAibP2TS3hyRu+RUqK+lD30MGQzSPGGF4xo+fwmH",
	"XOEkPNUyfjd8pfhxbB8fLOT32+Zb5z/zB0hnR/uUIUkizmJ5YFMxJRwEeDo8E85Os0fJ5/xBDlvlUeW3",
	"lTe1Wx5CX1Ujp/kOsjGia68hP7M8kh99t/JIUGA1NOH2opfKMMUi4t6MDGslk0asXjMJfaOSSVsBtv82",
	"TPCSCGR+rnb6/2clpeYpMfFOzzsltrTEisPxTeuntLznXHbi2s9fXTbFjNN+Y7zDk9J/ksooRQk3eCcz",
	"5tHqd2RZnk6JKJWgzUgphNz44Ni8+AWCeqs1ftb7VtvRt1Utk+LArVbB24dvsn6ejVvCdz761accHmRP",
	"yD1mqhTUCUJHiyl4SKESFNLxAgyXcoltHKiMuCCyDUs76eFNQjYX8c8jZHuJ30LIwQuGNOjZisf0nxuu",
	"0xZw8LJ3a03cNrFalIipFYXW7K25BpOyAghS3Kd/m/swfz4242eXOgerV1EuhOzKDLSobY0kfmIOPYvL",
	"nMAkr2+AfGU5heYO7FJzZ0udZ5vCKlvS0/OGsk7kFxmrVV4/byjj06gPtXN953auURKYliZc2HnJFxgT",
	"No8w7/3vcGPqIAn73bfvBz8evm2NwXraooA1OBY2UvP6UOnmslpCpX29fB8gVkQ8+1ho67FcFfq87XnZ",
	"8ZbtBZl5Xd5ap15FHy7dNjw/FLP1tuVbM/dWMtgtzrzwDt5YRJ1cn+96y8CFNpETGlFVcXllWC2sHnwt",
	"CKxUUuVNDvuAzgcqI35PxBKdsTllgMMBmszB+e9sJWfJo9i1JtDYXg7gjEJBloke9yehFR53uzFw1xv1",
	"njhOKYNUzyjJYyLRpN7C4tsgUMI/J1qbTKmUJgHcm2aglUuSavsxCi03sCrj/zQFTstafr3lDEsV9vuv",
	"t7wGqVx+hDjLQm32aoMQLkIs3DZr6uTya8Yy1l0YGQdLuz2xft1/gisScz3S+gjQyfX1xbnx0I9Pb84+",
	"nH0cnp9c3O5gmjQNhI34aOHZG82CjYP++V5KWmGiNA01QSIu4v9S02TFC+InTC0Ez2hUf5l824LNrj8q",
	"6Exz25K/IdjJyi4GdIb2KnvZ1SLfjP4ib9/loBWF2UyS/9a2cZTgPCah5IwRFb4O34RH/aM3/e+Pvm89",
	"9lCzytc0trK0WOJqalg7T/MgkjTT68oFad044zsWmMU8ZUTCqzWlaJv9frcfHnb71ZyJWcKxfXvd+DwP",
	"W/2fBs2OHO5adpVn4R2SemWg82CBU6KM0tPEuR4kazP7o4TksmWYl4J+Gy2oeji/gR60gkptvczn0mip",
	"qPr2VPq1JPZSJcCrdIHdDnRXU0h4fzjov3xJ7+6/KK85zHNh/lqKOF1gWpQyqMWGsjERgoug5RbNtDdb",
	"LJYun52RR+W2hQu9R5Eef6C1bZw84KUcoBP4r+5lmgsyxyJO9J7yGeK5ingK8X9u+gEauracQeI9/Fyo",
	"ybaxLSZVaZ4sdR/7xfSTtrmmrTHUXmnpAbINPvpOZZsYlqBt4gJDBQDmH8XwrWbxqu0Ai/qZ/Mn6jl9I",
	"gai56duIdga3fSxajjX4iWoZ6dp8MDBCxR7f6aWI9r9Oh+FpilkcijBLcrmta3+NrlIfr0VTJ5KwiOyC",
	"b9fnxXjkv3Skr4T+a3l2C3vYtZ77qpHB2quPv8n3umIw4zJ6ocGMr/qFBrNOuJcCDXKrXnAwk13xQgOu",
	"UHmfOdpKM/eZ47XLu7ba7tteDG2imZevgL1W4NYepXVy6qj/+l0pYDhT4evuYWuOZ43h9rvfPW3BGdY7",
	"/tsBftk6Kd7AKN8TFFcHUD1lB8WonTPt5sNesWxXP2VnDalW/WPzq+pfUz7jW3hvttZ0bLTvUfdNOEuw",
	"XGzUdUqo3hhDXB71pYprfDMb82ij7D/6p7Mxn11k5Ns7dNrVgt1iQv7ErpwN8SZVcoLvx93jwXf96Z/4",
	"+FsjuRmNMRxeexvMm+xF2KkpHViExkQ4ScCV76c7XEUp/4zk9m2DhHZSdXerHvJC7olaNYtv4Z7Qp11T",
	"2m6HPjz6Bj6K7SW1VyW/soZFMdALeyFeEKt/HoH+Z2MOLfVA/lOYQ7vpunt5jhdkErUiDv/kjGJnZ2bl",
	"fUjIuG+UdfDPxZsPxetcaS4hyczuT9xauGENIzHDNOEwNfUhNLkKiVECZjhJIPBAm53w+NO28MH52T5L",
	"5l+M7usY3Yu5S7dlQTdEieUqpgMfWxw4xX0VqJRB853n6I7PZmNb9Yc6r4oVuY2c50vfzrz1/GhcVBQn",
	"yA61FhlvWjXaYhcoo3qssQermsd42G9mcZ2bLm56FJMEQ+JRSpOEWv26okn3+61sAz+OsdKHUVUnPe5s",
	"Ebqjse97l3e/v0mH1/OuWO5xv2W9bvZN690m82w3F/KOEay7iblvF1/a+a81bQsKhA41McLYo8iZNgh7",
	"P5E0xeFxePXx4y//rCZueQf/aW3cr9U12++Wnl9Spe6vlG00+FL1NzY7il+sOsWfK+hvZzdysZZv50X+",
	"lwf5T3v3ndApnpl8zsolZB5Tfqp/tc89tVTPMx9cWHAE5Qx0N+RGa6aK8HsiEpyNY8svvKpRGdg0Qq5R",
	"XatAU6IeCGHl2cqPNfVXVKd5oCzmD+vn/gxtVk8NthF9JHFoRqutuPLIXr/fDsnTbluxfheuiQh9QYAG",
	"K/Y7gU4S+/6oqa7m66KH6A8ieI+nVCkSI3h8zbzvC32JcFXLZXM3Ye3bXBZvfcgq6cU7pBWXOWc5xXgF",
	"XZJH9RVgD8mjqkOtFoLIBW/L2gQBGYO96lsV72/bgn/FAVrLAbY027YFfCuaNg+2byTpVdLuY4uUs308",
	"IUdaxEU56AZmR7vwNrL0jw+6B+sQhnwx0wpNec5iDK+OoSuWLE2pm+nSkig8k2mPsWw/Cv79txZPjX8a",
	"zggn2DOZJVSZh6jtFfJoxEYjtmdfYxR4LnC2kAc7AVSSfljMiVqJzCF8bmoO+szDuLvzm4TP59VwkXY9",
	"78K0a2EyTpt26WGNI5KQe6OmbEdwdYguoLveLLU0YR7PG+cWuu+IjgsHe6FiUTbjDbXKoeeeiCmXVC2R",
	"WXUR6BGTaT4POq77AxYQvAKxrb+VtS3boDVsY93KanW3RUoZTlYCah4pdE/7AWq7aM9127P1PxMuTA0W",
	"ziRPSAft/UNye9pLb45q5buD9hI+n6Vqr3DVhWQ2oxElTGnV/IfS057wKAHP7Eg0sczaIasEvp4w0Nq7",
	"HjvoBLpbFWGlxmuQJo+LM14tJVaTapBlN74jy1Zd9uTzrSuzoq2N8w9d5Mvp35GlVFwQ97gprI1EgiiU",
	"cH6XZ/WcrpPPt+OT09Oz29vxX8/+Pj7/0JrQ5R8MIaqql5uneUxW4B1ZhjRuQ4HzUbSwuMpD0sW7JZa1",
	"yeMuTvEfnOEHyOjcQ1zoTXZlRr/v9/tmAy8pO786qObI1TobC/sCngot29gFnAZT4wL/7ci3CC324Gs3",
	"4Pbs9OZsWNqHZ2yCmaS0F0HrAiFX1XD3VcIXJ8isEtq6ixBNUCTNuMBiWc7r3WntbWDDLKGBqC3fWpKx",
	"lMnGol82f/j29qI3vLiFuW+PNddg5rFzWXvlFVqcfL7tIPO6clGO2R+lepGw9XxbRgJnNTmmCFPu1e+1",
	"tQVJPNYHus0ecI92l4u76bbahJa982tjEiSU3fl6URIyJqFiG5QNhPayXFwQ7ZPHiGTKvJMDb4BLfb7g",
	"HfCx/XFMM+mqvB3UypJVy7tFMetWfzn8/qjb7x51D59X5g6end8SGbqtfeWXOPsIHrSHanXwFD08il9H",
	"CsxRrbj4Y6mztkDwVPIk1yo9tLVsqfdJEiF7MVa4d2A6mVl0F/vYvX112PZIl6H9Pc9gg3p1fJbH1Iyq",
	"0WE3PDb2cSP9vNc9fJFA82yzfx5eYDYnEu0fHn3X7ev/9d510GG/9Pd3R93Dt/AveK/je/3Pd+bfbzvo",
	"8O333aM3r+2/D1oL8LnD6zJsxs6FX70JaHiTrIN1BqlIMb2ncY5LpdN4Zh0zsuSDrdSq2+pmwkOnNejx",
	"dKlI/Ubm9bs3371dfU0BmjefecCMSgPF0SlDZsASVKXx1pTRK9UQMb++fe0AhrLK4/YiviYwuR1O6Ice",
	"aKwWvQWBcn+UoYw+Qg1qU6wZPdAkQVNwDsJz/GXIbdTzWozmkogxnpM2lUATQngyh2JcUDERtha86iX+",
	"Vimfa8rlfHjfO+z298piEt3ylNiXZT35fqZ3NCMxxQdIEHAE+lP/QNVCHyaMCiiqQqs8VWt0xS4SQi+q",
	"0ARX2T2w9ELi1st4k9jrTS0eEm3ct98p+dd63QPpCyrL0+AsSyjRCN7maqlUNhPH7snk6woozQrTzWX6",
	"GpncvrVL1ugXdj9Hwb99MWrGALSIp1FQ9noVOyGtJN7egNtSpu+67zck5YrYsba/1hDQzbONGVH2nQfz",
	"4frDjx3b5lIfb/ePIXlUvvaVPOjCq9aSJzSG8sRaSyqVaQGZaZenaUjBuxTWS0FMrS+tu+YZ0puB5664",
	"YXGQ0Q0BsanhvhIxEe4t4jNXF2ZSmvGHUaBVmVEwKbmhKfMQw1vEP8KjxaXT+QBpdhMjJOUEzRM+1VJa",
	"EcFQilW0IFKfbnh8Q7cZseMumlgWOJbHk9JoI/a6iy7IHEdLH3cyQBO3vmpjifb19wcsNAc3tgtNqFoe",
	"tNwmFfM1N9iV0KlsgLkZeVgQhhi3oNfXVeVImaApFq3q/kKpbB1FPpMIWtlWg54/4pTEqMa85CbuVUql",
	"gSJYDCchzmiVlQWVipeunSs1XHCiahXpQfCeYEEEqrGL4KmVfs2WvTDqbo+3RVyNLNfQf7deRdWch6Yj",
	"oeCT2iK+I8unoGybtxnMLRZxdRTz5xMIdaZELpUp0LxyaqvPuuktAWsVWCsFof0cvtKklE8TGoWvwNfy",
	"fDDdjA7UqiBYqdw5DWzF6fizyJKWE1VJFd0SuHbXVDNDz+9X44a1xIDNcbXMC+zUhnYBdVaJ7KLPmtVh",
	"UEQc28ZunE6jG5WaefBQkoREitSLZTeOUKoFoTlB2xtP/5l728hCrEoDKGjkr8qq4qAmq/k9EYLGlcpH",
	"xQmySXljDbP7u+lwb3v1wCvdG03Iz7bculoQFGO5mHItI+WC5wn856Fe1trmwsvuiJX1ee+ekQqzGCec",
	"kZ58wCKF/l10S5RuZvw2VItFhuckHrGYZAlfmlJQVjn8az4lghGt6BhLkIsDqzykxVNPdgRflDtZmtCQ",
	"lvcUVoVotYRn+Xczev5yzd5QbHw8qb+Fyq21EMJibeVzd1xLLx1wxh61gZjgoBPMefM1g/emP3L9ERfO",
	"2jL7pPdIA109hDGBqBdXiwuePfwRQB2giYVpApWx7T8GpsfEot32j0sbPtE0Pam8nqYEhTJ/5r+UWeD0",
	"iYdnRKF+PiiF+B7TBHx/dr7/ZmYYsYinU8qM/gxF96WzJPwbelZ3taiQr16h/ZhkGiucQfX4GCk8lwdQ",
	"3GQy5xPUVs9839QKKUDpoNPrT1BnpINkwh+INAVMJnpT9BhQLP7GBLxp/d0+whTqyX4Ywd51rm6Go6CD",
	"Zlgq3/8xwbo7FE9Hv1yctPR9THDnl4sT3XV4/al3+unDSe/0+pN7VAlwI1+9MisCxKMQnWimGhOlreEp",
	"qWC1UoFlEuUxQPDxb+cfzk+QHh39dP3JfOOCpAkMl2UJQadckMsLtJ/i6OrWYsNdR2oEmBFVlpslQYTO",
	"8PoTPBQLjX65OLGzmjY/chERj9pKTXW/ol8N9vTyARfmjzkfBb/pIYZi6c6JLRenUVAcSmW8xeWhBnrN",
	"fryBynLzD/PN/cvPcA1l1zVSwLWceE//qUWTHxbQVettcAWAWfRppSbxL/BV5Z0HzxC6hg0K0xjA7I/m",
	"L8MBtheCVsscfzth2AnuCMnGOKH3tavDN823cP0bFYoj3c1xb+tK01LAPEuIZ9p+TLBU5v1xk0JXumXS",
	"BnDplT+9/SmGhwWTJcqdb84MA+qHD8XhM0QZjhS9p0oLiE8S+EBcstGBC46CN+koQPtvUEpZrm1uvcWH",
	"C/3bIVrwXMAPff1vgucaXMNpD2qC0A2U4D+Wvg1K6J3LDPSy0IwGNbmNiZ0sXY3UygwjZpgwdpX2Kk8d",
	"wjUsFirPgNEyck+ER0mt1IHZpJYQx/nz78eLkwExOP7tx7F/Wqd8TPqb49HLz0d6bu29fc7tP2In3sor",
	"+wKNj/P3nOQkRnkG7w7ixzH8AKZCd8Qs/vsgNnMGtaBIXDDNGtZer/IvGxyPy8kym5apuMJJjQ5scIre",
	"XkHmVCqxRHpCrQ+5txLdsxL6zxHzYdmy4wNDOoioqHtglXMtLE2VLCqRIPDYS8f8SrBUoSARYSpZhppt",
	"jxiNfXYROIswWxawUIk0p1Xm/ZwU3xEkOE/9Od4Wj8er8Gi4wDidbodDyzT2KUOX7w/KFf4tQn2gsEUF",
	"lQUucJYJbtEBqEAOFUbMlQisREQbV4qGehYKL9Lg+J5KDaGZNEQ4UrnedYB7xHKJ51psZSDPOLOI14fT",
	"mAcpXvp7W6qZwmNENPL1FBAMoZcGz7poPXsuaUxQ4zzaSzUGD09SZq8uBE/qp7v//dtVG1NQza5EXL6T",
	"glGMe2wFiygd0mLXLBXrb7M8STqIkYdiXL1r9J6gN/1jdGuDuj+xQgMCaQyJReEJiAXjYlq9l2ay0o5C",
	"JBaZzbRycb8B/lHe7x8T1K/hdlW2jt6gsVQCKzJ3dtsKn5ULbQGJEHQCLVaCTgAxbCRuLdTSDPWsmgZ2",
	"4rL1iS5xJktl1KV9KYuKRq9CEjOuTMA5lSjFGVAhmJHWR+rnMcGKnKFCdwC973xW+sWgsHhJxwrSgwEq",
	"S1K0by4IGYqJNkM7lkqt7Nd87KAx9A8gaQdVqWpHKsRnpyI7QfW2fg6DlwWWxZJGZkNGQRkDZlHAZprC",
	"eR9LlGEBt+CZIHYO174qtjuI3BNmjlwLhjLKWFl/AliBAYF0lCilj3qFZr2aowAKLV+wOQISpwRlvMEP",
	"vgTvT07Oe9M5MQ95+8d3B/4MplSoRS9acHa3DFNN8sq2rTx6dBgMzHFt844ZYMYxFStuufyjwMC3MGVF",
	"cW2ZT91XCOJ09id4mVwJeOnWqwWaMTO+FJM+lZ4h1ir8WePl3sLYqXRz4hZ6nToXwYZOXnZDr5vqkwbr",
	"ukV8zugfRUf4N+itG7s+CKpcx1vy+9Et+R25X+u9qxrs/9nrWm9Tz7Vzrz/d04yIg6K2N1EdU5nTP9oG",
	"IatFYDItGdh1ZbQxT2skHudJUwIddlbGC7eqjxnNSEIZMTGvxouAznC08F+AYuWIYRTxbOm8QtCygyRH",
	"CzpfEFGOdE+5IE4XmebKPsqofx2xEhDFE47maVC/IOTTVgEqy6SdkkCZURCMasJnTQFflzVtksYymtUv",
	"T9ZYvm1f4VutxthwQSRpsUZoCt5bRZKlYV8+zFcPJzsI33MKdAaOIJ+EkGBFWOSFi4XIuiHBx4zUglvX",
	"oT/nJSIuLpbb2dco0GC3yfSCwQIj5iz8gwheNeBgzro+++sqTulqsPWihGbhPVXmFfNML+P4aDeT3iJo",
	"XElddDZ389Uyb2dQ89zTA6bKv5VjUK04XIEmRJGOvbDXK7Ramm6vO681lY/70rhADlPzXzCLGXeZkx1U",
	"MgFunJJk1FhTkZhKn2VZaHKv0U9YkQe8RDZAqM4xjvutPEIe15/5/boLlFoqlHMfN5Ohnp5sYPaGQAAz",
	"tYleNI9axtq0otNca553ZBmaGGcTKaEFtn1/WxIsogWyr5notVNVCmlB1WluYRpTFNDEDwX9br97qHFk",
	"F6qR2O13j4NOYMP1WJ4kT/9fAAAA//+NhMxd9gYBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/ai/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/audio/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/embeddings/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef4.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/middleware/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef5.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/reranking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef6.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../pkg/generating/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef7.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../pkg/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef8.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../pkg/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef9.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../termite/pkg/termite/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
