// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package common

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/antflydb/antfly/lib/ai"
	externalRef1 "github.com/antflydb/antfly/lib/audio"
	externalRef2 "github.com/antflydb/antfly/lib/chunking"
	externalRef3 "github.com/antflydb/antfly/lib/embeddings"
	externalRef4 "github.com/antflydb/antfly/lib/middleware"
	externalRef5 "github.com/antflydb/antfly/lib/reranking"
	externalRef6 "github.com/antflydb/antfly/pkg/libaf/logging"
	externalRef7 "github.com/antflydb/antfly/pkg/libaf/scraping"
	externalRef8 "github.com/antflydb/termite/pkg/termite"
	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for StorageBackend.
const (
	StorageBackendLocal StorageBackend = "local"
	StorageBackendS3    StorageBackend = "s3"
)

// Config defines model for Config.
type Config struct {
	// Chains Named chain configurations for fallback/retry logic.
	//
	// Chains are ordered lists of generators with retry and fallback logic.
	// Each link references a generator by name from the `generators` map.
	// The first chain defined becomes the default when no chain name is specified.
	//
	// **Chain Conditions:**
	// - `on_error`: Try next generator on any error (default)
	// - `on_rate_limit`: Try next only on rate limit (429) errors
	// - `on_timeout`: Try next only on timeout errors
	// - `always`: Always try the next generator
	//
	// **Example:**
	// ```yaml
	// chains:
	//   default:
	//     - generator: gemini-flash  # Reference by name
	//       retry:
	//         max_attempts: 3
	//       condition: on_rate_limit
	//     - generator: ollama-local  # Reference by name
	//   with-inline:
	//     - generator: gemini-flash
	//     - generator_config:  # Inline config
	//         provider: anthropic
	//         model: claude-sonnet-4-5-20250929
	// ```
	//
	// Then in API calls: `chain: "default"` or `chain: "with-inline"`
	Chains map[string][]NamedChainLink `json:"chains,omitempty,omitzero"`

	// Chunkers Named chunker configurations for text chunking.
	//
	// Define named chunkers that can be referenced by indexes and API calls.
	// The first chunker defined becomes the default when no chunker name is specified.
	//
	// **Example:**
	// ```yaml
	// chunkers:
	//   fixed-500:
	//     provider: termite
	//     model: fixed
	//     target_tokens: 500
	//     overlap_tokens: 50
	//   semantic:
	//     provider: termite
	//     model: semantic-chunker
	//     api_url: "http://localhost:8080"
	// ```
	Chunkers map[string]externalRef2.ChunkerConfig `json:"chunkers,omitempty,omitzero"`
	Cors     externalRef4.CORSConfig               `json:"cors,omitempty,omitzero"`

	// DefaultShardsPerTable Default number of shards to create for a new table.
	DefaultShardsPerTable uint64 `json:"default_shards_per_table"`

	// DisableShardAlloc Disables automatic shard reallocation (splitting/merging).
	DisableShardAlloc bool `json:"disable_shard_alloc,omitempty,omitzero"`

	// Embedders Named embedder configurations for embedding operations.
	//
	// Define named embedders that can be referenced by indexes, templates, and API calls.
	// The first embedder defined becomes the default when no embedder name is specified.
	//
	// **API Key Configuration:**
	//
	// API keys can be provided via the encrypted keystore (recommended) or environment variables:
	//
	// 1. **Keystore** (recommended for production):
	//    ```bash
	//    antfly keystore create
	//    antfly keystore add openai.api_key
	//    ```
	//    Then reference in config: `api_key: ${secret:openai.api_key}`
	//
	// 2. **Environment variable** (simpler for development):
	//    Omit `api_key` from config and set the appropriate env var:
	//    - OpenAI: `OPENAI_API_KEY`
	//    - Gemini: `GEMINI_API_KEY`
	//    - Anthropic: `ANTHROPIC_API_KEY`
	//    - Cohere: `COHERE_API_KEY`
	//
	// See [Secrets Management](/docs/secrets) for complete documentation.
	//
	// **Example:**
	// ```yaml
	// embedders:
	//   openai-small:
	//     provider: openai
	//     model: text-embedding-3-small
	//   termite-local:
	//     provider: termite
	//     model: bge-base-en-v1.5
	//     api_url: "http://localhost:8082"
	// ```
	Embedders map[string]externalRef3.EmbedderConfig `json:"embedders,omitempty,omitzero"`

	// EnableAuth Enables authentication and authorization (RBAC) for the API.
	EnableAuth bool `json:"enable_auth,omitempty,omitzero"`

	// Generators Named generator configurations for AI operations.
	//
	// Define named generators that can be referenced by chains, templates, and API calls.
	// The first generator defined becomes the default when no generator name is specified.
	//
	// **API Key Configuration:**
	//
	// API keys can be provided via the encrypted keystore (recommended) or environment variables:
	//
	// 1. **Keystore** (recommended for production):
	//    ```bash
	//    antfly keystore create
	//    antfly keystore add gemini.api_key
	//    ```
	//    Then reference in config: `api_key: ${secret:gemini.api_key}`
	//
	// 2. **Environment variable** (simpler for development):
	//    Omit `api_key` from config and set the appropriate env var:
	//    - Gemini: `GEMINI_API_KEY`
	//    - OpenAI: `OPENAI_API_KEY`
	//    - Anthropic: `ANTHROPIC_API_KEY`
	//
	// See [Secrets Management](/docs/secrets) for complete documentation.
	//
	// **Example:**
	// ```yaml
	// generators:
	//   gemini-flash:
	//     provider: gemini
	//     model: gemini-2.5-flash
	//   ollama-local:
	//     provider: ollama
	//     model: llama3
	//   openai-gpt4:
	//     provider: openai
	//     model: gpt-4.1
	// ```
	Generators map[string]externalRef0.GeneratorConfig `json:"generators,omitempty,omitzero"`

	// HealthPort Port for the health/metrics server. Defaults to 4200.
	HealthPort int `json:"health_port,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef6.Config `json:"log,omitempty,omitzero"`

	// MaxShardSizeBytes Maximum size of a shard in bytes. Used to determine when to split shards.
	MaxShardSizeBytes uint64 `json:"max_shard_size_bytes"`

	// MaxShardsPerTable Maximum number of shards that can be created for a single table.
	MaxShardsPerTable uint64       `json:"max_shards_per_table"`
	Metadata          MetadataInfo `json:"metadata"`

	// RegistryUrl URL of the model registry for the Antfarm dashboard. Defaults to https://registry.antfly.io/v1
	RegistryUrl string `json:"registry_url,omitempty,omitzero"`

	// RemoteContent Configuration for remote content fetching (remotePDF, remoteMedia, remoteText templates).
	// Consolidates S3 credentials and security settings separate from backup storage.
	//
	// **Credential Resolution Order:**
	// 1. Explicit `credentials="name"` parameter in template
	// 2. First credential where `buckets` glob pattern matches URL's bucket
	// 3. `default_s3` credential
	// 4. Legacy fallback: `storage.s3` credentials (backward compatibility)
	RemoteContent externalRef7.RemoteContentConfig `json:"remote_content,omitempty,omitzero"`

	// ReplicationFactor How many replicas of each shard should be maintained.
	ReplicationFactor uint64 `json:"replication_factor"`

	// Rerankers Named reranker configurations for search result reranking.
	//
	// Define named rerankers that can be referenced by indexes, search queries, and API calls.
	// The first reranker defined becomes the default when no reranker name is specified.
	//
	// **Example:**
	// ```yaml
	// rerankers:
	//   cohere-english:
	//     provider: cohere
	//     model: rerank-english-v3.0
	//   termite-local:
	//     provider: termite
	//     model: mxbai-rerank-base-v1
	//     url: "http://localhost:8080"
	// ```
	Rerankers map[string]externalRef5.RerankerConfig `json:"rerankers,omitempty,omitzero"`

	// ShardCooldownPeriod Cooldown period after shard operations (start/stop/split). Format: duration string like '1m', '30s'. Default: '1m' (one minute).
	ShardCooldownPeriod time.Duration `json:"shard_cooldown_period,omitempty,omitzero"`

	// SpeechToText Named speech-to-text provider configurations.
	//
	// Define named STT providers that can be referenced by templates and API calls.
	// The first provider defined becomes the default when no provider name is specified.
	//
	// **Example:**
	// ```yaml
	// speech_to_text:
	//   whisper-local:
	//     provider: termite
	//     api_url: "http://localhost:8080"
	//     model: openai/whisper-base
	//   openai-whisper:
	//     provider: openai
	//     model: whisper-1
	// ```
	//
	// Then in templates: `{{transcribeAudio url="..." provider="whisper-local"}}`
	SpeechToText map[string]externalRef1.STTConfig `json:"speech_to_text,omitempty,omitzero"`

	// SplitTimeout Maximum duration for a shard split operation before triggering rollback. Format: duration string like '5m', '30s'. Default: '5m' (five minutes).
	SplitTimeout time.Duration `json:"split_timeout,omitempty,omitzero"`
	Storage      StorageConfig `json:"storage"`

	// SwarmMode Bypasses Raft consensus for shards, using direct writes instead. Useful for development and testing with a single node.
	SwarmMode bool                `json:"swarm_mode,omitempty,omitzero"`
	Termite   externalRef8.Config `json:"termite,omitempty,omitzero"`
	Tls       TLSInfo             `json:"tls,omitempty,omitzero"`

	// Version Internal version of antfly
	Version string `json:"version,omitempty,omitzero"`
}

// LocalStorageConfig defines model for LocalStorageConfig.
type LocalStorageConfig struct {
	// BaseDir Root directory for all antfly data storage. Defaults to 'antflydb'.
	BaseDir string `json:"base_dir"`
}

// MetadataInfo defines model for MetadataInfo.
type MetadataInfo struct {
	// OrchestrationUrls Mapping from Metadata Node ID (hex string) to its URL used by store nodes for enrolling into the cluster
	OrchestrationUrls map[string]string `json:"orchestration_urls"`
}

// NamedChainLink A link in a chain that can reference a generator by name OR provide an inline config.
//
// Use `generator` (string) to reference a named generator from the `generators` map.
// Use `generator_config` (object) to provide an inline generator configuration.
// Only one of `generator` or `generator_config` should be specified.
type NamedChainLink struct {
	// Condition Condition for trying the next generator in chain:
	// - always: Always try next regardless of outcome
	// - on_error: Try next on any error (default)
	// - on_timeout: Try next only on timeout errors
	// - on_rate_limit: Try next only on rate limit errors
	Condition externalRef0.ChainCondition `json:"condition,omitempty,omitzero"`

	// Generator Name of the generator from the generators map
	Generator string `json:"generator,omitempty,omitzero"`

	// GeneratorConfig A unified configuration for a generative AI provider.
	//
	// Generators can be configured with custom prompts using templates. Templates use
	// Handlebars syntax and support various built-in helpers for formatting and data manipulation.
	//
	// **Template System:**
	// - **Syntax**: Handlebars templating (https://handlebarsjs.com/guide/)
	// - **Caching**: Templates are automatically cached with configurable TTL (default: 5 minutes)
	// - **Context**: Templates receive the full context data passed to the generator
	//
	// **Built-in Helpers:**
	//
	// 1. **scrubHtml** - Remove script/style tags and extract clean text from HTML
	//    ```handlebars
	//    {{scrubHtml html_content}}
	//    ```
	//    - Removes `<script>` and `<style>` tags
	//    - Adds newlines after block elements (p, div, h1-h6, li, etc.)
	//    - Returns plain text with preserved readability
	//    - Useful for cleaning web content before summarization
	//
	// 2. **eq** - Equality comparison for conditionals
	//    ```handlebars
	//    {{#if (eq status "active")}}Active{{/if}}
	//    {{#if (eq @key "special")}}Special field{{/if}}
	//    ```
	//    - Use in `{{#if}}` blocks for conditional logic
	//    - Compares any two values for equality
	//
	// 3. **media** - GenKit dotprompt media directive for multimodal content
	//    ```handlebars
	//    {{media url=imageDataURI}}
	//    {{media url=this.image_url}}
	//    {{media url="https://example.com/image.jpg"}}
	//    {{media url="s3://endpoint/bucket/image.png"}}
	//    {{media url="file:///path/to/image.jpg"}}
	//    ```
	//
	//    **Supported URL Schemes:**
	//    - `data:` - Base64 encoded data URIs (e.g., `data:image/jpeg;base64,...`)
	//    - `http://` / `https://` - Web URLs with automatic content type detection
	//    - `file://` - Local filesystem paths
	//    - `s3://` - S3-compatible storage (format: `s3://endpoint/bucket/key`)
	//
	//    **Automatic Content Processing:**
	//    - **Images**: Downloaded, resized (if needed), converted to data URIs
	//    - **PDFs**: Text extracted or first page rendered as image
	//    - **HTML**: Readable text extracted using Mozilla Readability
	//
	//    **Security Controls:**
	//    Downloads are protected by content security settings (see Configuration Reference):
	//    - Allowed host whitelist
	//    - Private IP blocking (prevents SSRF attacks)
	//    - Download size limits (default: 100MB)
	//    - Download timeouts (default: 30s)
	//    - Image dimension limits (default: 2048px, auto-resized)
	//
	//    See: https://antfly.io/docs/configuration#security--cors
	//
	// 4. **encodeToon** - Encode data in TOON format (Token-Oriented Object Notation)
	//    ```handlebars
	//    {{encodeToon this.fields}}
	//    {{encodeToon this.fields lengthMarker=false indent=4}}
	//    {{encodeToon this.fields delimiter="\t"}}
	//    ```
	//
	//    **What is TOON?**
	//    TOON is a compact, human-readable format designed for passing structured data to LLMs.
	//    It provides **30-60% token reduction** compared to JSON while maintaining high LLM
	//    comprehension accuracy.
	//
	//    **Key Features:**
	//    - Compact syntax using `:` for key-value pairs
	//    - Array length markers: `tags[#3]: ai,search,ml`
	//    - Tabular format for uniform data structures
	//    - Optimized for LLM parsing and understanding
	//    - Maintains human readability
	//
	//    **Benefits:**
	//    - **Lower API costs** - Reduced token usage means lower LLM API costs
	//    - **Faster responses** - Less tokens to process
	//    - **More context** - Fit more documents within token limits
	//
	//    **Options:**
	//    - `lengthMarker` (bool): Add # prefix to array counts like `[#3]` (default: true)
	//    - `indent` (int): Indentation spacing for nested objects (default: 2)
	//    - `delimiter` (string): Field separator for tabular arrays (default: none, use `"\t"` for tabs)
	//
	//    **Example output:**
	//    ```
	//    title: Introduction to Vector Search
	//    author: Jane Doe
	//    tags[#3]: ai,search,ml
	//    metadata:
	//      edition: 2
	//      pages: 450
	//    ```
	//
	//    **Default in RAG:** TOON is the default format for document rendering in RAG queries.
	//
	//    **References:**
	//    - TOON Specification: https://github.com/toon-format/toon
	//    - Go Implementation: https://github.com/alpkeskin/gotoon
	//
	// **Template Examples:**
	//
	// RAG summarization with document references:
	// ```handlebars
	// Based on these documents, provide a comprehensive summary:
	//
	// {{#each documents}}
	// Document {{this.id}}:
	// {{scrubHtml this.content}}
	//
	// {{/each}}
	//
	// Valid document IDs: {{#each documents}}{{this.id}}{{#unless @last}}, {{/unless}}{{/each}}
	// ```
	//
	// Conditional formatting:
	// ```handlebars
	// {{#if system_prompt}}System: {{system_prompt}}{{/if}}
	//
	// User Query: {{query}}
	//
	// {{#if context}}
	// Context:
	// {{#each context}}
	// - {{this}}
	// {{/each}}
	// {{/if}}
	// ```
	//
	// Multimodal prompt with images:
	// ```handlebars
	// Analyze this image:
	// {{media url=image_url}}
	//
	// Focus on: {{focus_area}}
	// ```
	//
	// Structured data encoding:
	// ```handlebars
	// User Profile:
	// {{encodeToon user_data indent=2 lengthMarker=true}}
	//
	// Please analyze this profile.
	// ```
	//
	// **Common Use Cases:**
	// - **RAG (Retrieval-Augmented Generation)**: Format retrieved documents with citations
	// - **Summarization**: Clean HTML content and structure summaries
	// - **Query Classification**: Format queries with metadata for better classification
	// - **Multimodal**: Include images/audio/video in prompts
	// - **Data Formatting**: Convert structured data to readable text
	//
	// **Best Practices:**
	// - Keep templates simple - complex logic belongs in application code
	// - Use clear, descriptive field names in context
	// - Handle missing fields gracefully (templates use "missingkey=zero" by default)
	// - Test templates with representative data before production use
	GeneratorConfig externalRef0.GeneratorConfig `json:"generator_config,omitempty,omitzero"`

	// Retry Retry configuration for generator calls
	Retry externalRef0.RetryConfig `json:"retry,omitempty,omitzero"`
}

// S3Info defines model for S3Info.
type S3Info struct {
	// AccessKeyId AWS access key ID. Supports keystore syntax for secret lookup. Falls back to AWS_ACCESS_KEY_ID environment variable if not set.
	AccessKeyId string `json:"access_key_id,omitempty,omitzero"`

	// Bucket S3 bucket name where SST files will be stored
	Bucket string `json:"bucket"`

	// Endpoint S3-compatible endpoint (e.g., 's3.amazonaws.com' or 'localhost:9000' for MinIO)
	Endpoint string `json:"endpoint"`

	// Prefix Optional path prefix within the bucket (e.g., 'antfly/production/')
	Prefix string `json:"prefix,omitempty,omitzero"`

	// SecretAccessKey AWS secret access key. Supports keystore syntax for secret lookup. Falls back to AWS_SECRET_ACCESS_KEY environment variable if not set.
	SecretAccessKey string `json:"secret_access_key,omitempty,omitzero"`

	// SessionToken Optional AWS session token for temporary credentials. Supports keystore syntax for secret lookup.
	SessionToken string `json:"session_token,omitempty,omitzero"`

	// UseSsl Enable SSL/TLS for S3 connections (default: true for AWS, false for local MinIO)
	UseSsl bool `json:"use_ssl,omitempty,omitzero"`
}

// StorageBackend Storage backend type
type StorageBackend string

// StorageConfig defines model for StorageConfig.
type StorageConfig struct {
	// Data Storage backend type
	Data  StorageBackend     `json:"data,omitempty,omitzero"`
	Local LocalStorageConfig `json:"local"`

	// Metadata Storage backend type
	Metadata StorageBackend `json:"metadata,omitempty,omitzero"`
	S3       S3Info         `json:"s3,omitempty,omitzero"`
}

// TLSInfo defines model for TLSInfo.
type TLSInfo struct {
	// Cert Path to TLS certificate file
	Cert string `json:"cert,omitempty,omitzero"`

	// Key Path to TLS key file
	Key string `json:"key,omitempty,omitzero"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y963Ibt7oo+CqoXnvKkk83SUm2k/BU6mxZlh3tSLaOJK9kTZgiwW6QxFI30GmgJTEu",
	"Tc0jzI95jXmp8yRT+HBp9IUXXZydvU5q116R2bh++PDd8F2+BDHPcs4IkyIYfglEvCAZhj+POJvRufor",
	"L3hOCkkJ/B4vMGXwF04SKilnOD2vtaCSZPDHvxVkFgyDv/WrSfpmhv5HnJHkSI11Stl1cB8GcpmTYBjg",
	"osBL9e+EiLiguZohGAbQHsHkKIallQVW3wSa8QLNcJpOcXzdL4gslijlcxr3RmzEYAqBcEEQLxJSkASl",
	"VEiB+AzNCSMFlrwQ6JbKBdJ9MUvccG6gYxwvUErZNSrIjBSExUQgXI2ApkvEcEbQrOAZkguCJtXoE5Th",
	"vDdiVwuCZrQQ0uwjITPKSIKmJOYZEdAtITNcphLdLghDjJuWMDQVSOQkpjNKEtjby5ewO3TEmT4JMXz5",
	"csQiNOFsTIqCF5MhuiqWiJE76a2VM4TZEkELtGNm3LUdCyzJOKUZlX5vztKl6qi+IviKdl7tf7erRxG2",
	"s6QZ4WVnT/PJ74DTW7wUkyE6hD+QAr8CQn29eqvHdzjLUwI7nEwmS5ylI6aRcThiyAIO/kYoqroP0Zxk",
	"lNFolmKxQOhv6MIeoT013QdpBBjafyGU4bsxlpJkuRRDdGA/xBbeQ1SDV8fUPE1xhqOUxzhdObVCvoiy",
	"lDKyafmtz2N9GYZq8BMYwlyPahd5wW9oQoohwkwuCp7T2NsiT0g6RHGKy4REgjNGZPQqeh3tD/ZfD77b",
	"/w6grY7gSmEkZejw/ATFOE3FEE0A/kM0Cgz0R8EE8cL73dvaKJiMWBAGRB+kIhCmVzD8RREiA9RgGNSg",
	"GoSB220wDHxoBGEAR6bG8s8qGB7c34dfav38kwjufw39pcECVk5SG8nAG2ZUoAuGwWrYBWFgga8om4V+",
	"cH//a0Xw+PSfJJaK4sWLkl2TYi1xXUdTUzodwxiUzcc8JwzndHykBzXkfCVdhUZdlFWqu2hHBbLzDsgW",
	"YK/rqYgXlijGDE1JRSMTheaUJeROkUuWVMjTIId6+u0Iom67iiSuoBN6lXC9ZvSOJNHrwcBctup+SFJk",
	"VBpyYG4GtNa/SFzMiRxLfk2YGKLXg4H+nd+QIsW590H9LkiGmaTxVrPYxpFZqf6ozq8sUnWRFlLmw34f",
	"0HfBhRx+O/h2MArM7axfK7dBH0vhxyAM6osNhq8HNSQ1iwvCoLZb1W5wHwZ2nYCienXBsHtxQejmbu4u",
	"6JzyvvNO8GIrvM9okqTkFhekwvxPF5c+2gMejcUCF4kY56QYSzy1dMi/Eu8MxrEym5JCCQq6D5IcxQVR",
	"DFBdDIwYuUUwRs+H/6swUMQjK7NguOd2RJkkc9j5XTTnkfm1pEy+eQXLo0KNpJc3xmnK4xqFnOFUkObl",
	"fac7CYRLyTMsaayXigoCI8A1RjsiT6mUlM37GSnmlM131YLNEqacpwQztQaSTUmSPJEA6UEomwt3EMdm",
	"3PU0yM7eRYTcoEgtRX9o0yK3/s3EKESKU6RYqj9XEya3pm0ok2u8ijSpOX4kS3TkbxAI1Yipb9dkKeyq",
	"zf1I0A3FMBthcbHMJUmgmeQFQTuFWk1GWEKSXcV3CbuhBWcZYRLd4IICcgzV8Hs99PLlj6bjy5e1rgDh",
	"vOBJGasF7WqCNZlMplbgwEzO0mU1sb4FnZ9wkiA4d9pTR39NlnY0+C8IEe5EkBPmh2himg/Rv30RJC6I",
	"HNbHuQcpZF9t5Lhjn2pTgqorWMCGEnJDUp6rNmZHn5TQaqeZaEldzw4YIIgEQONcKTwFVfecsBs1ge4f",
	"oU85YYcnQzT5dH788fBkfHh+Mv7x+B8T8/kDSA1DNPlwfHbysfX50PL/IZocfrz64eLT+clRs9ERX5CC",
	"DNHk6NMPxxfH3ucRuyQE/XIJsBHoDDM8J2p7v+70Ex6Lvoaa2IXtq9uZEklQwuNStQJkW8cj3e2B3WrY",
	"RyLDadriYPpjjYEpMSFy1zQ60D1VE0PeteS1FTOczkk0xYJEhEU3e73XWzHD/RXM0N+Izw+7F1znTLov",
	"KKf+JjYzv32P+TV38wDmRxjwBFzKxWZmcMwcL1gQxW019VeorX7iBf3d8IOLt4dHGksUvh+en3Szg0qB",
	"fQo/wNTxgQ92wPWMoFJUOzjB4claFuCp9Kt5gNYat2QB1Wq24QFV6//dmYBWoZ7OBOrj/AmYwAYqv4FH",
	"bGICX5vKVxcE9uMrui3arD/WSLNpv997XdkjfM26zSrgY20M+OXAYzLzXL7ahsfMcxm96u11kvmaxu6R",
	"+eaC69RXf1WEqGYe8PrrxTbYAvwIvaoN1CbVC+1mJl2EfkFwKhfjnBeyRuhf7Q8GTSJ5zgvpiLfu2M+I",
	"LGgskCDFDSl6yKgwoLKoMeoKCgza0EvuwyDl800EPb+ej1M6xbNxyufzmpnBkfQM3xktRtDfyXi6lJpR",
	"1Hdxhu+UioRUG6ViYaO5UIagRw99FiRR608I8EhGNJGVHIE+Y5Sy2s72Bt8cfPNq79v9V7AMrYO9erP3",
	"zeDb777d3/8GNl4pZ4NX377+5s3WKprb2Frt0W6srT16/EjTzsTokYKyeUo6VMm9+nq3XymROMESbzrO",
	"M9PuhM246leQORWyWGrJprmzzxenajsK7QDRkW1eiRJMznCRoQSLxZTjIqljopKUxLDft/16mm/0KO/f",
	"7Pn7Dja1nPEiw1LtuaCV7CJkQdlcbyTjkoxjziRhcnusFnGBcx+tL2CgIz1OheMFyVMjYI1nOAajYRNc",
	"P/BblGG2RKYxPDkQHC8MposFL1MlTaAMUyaxki1qp3/gIfHrR+FBQQr8ZIuiHqQOFD3sejHOTt4lxQmC",
	"i3iBCiKU8ORmaMtzbgfbqPRm1N9KUtD1Qp1b2zYynWv8IJOjWzlwthjUuoiweUo7OK3+XGN2ur/tEd0c",
	"9AaP06ayuymmkRkOFJGbPd3gEabF+j58ntex3jr/0107lSk7RtdSgxXmyXWWx04eq3lSzHma8FumSDjl",
	"SfvaHpkGSDdAeCZJYa5spXmgHSFxIftC8rwP/Gi3h94DVRqixOA60gQJpfSaoBd72YsQvTgYiBeOKg7h",
	"V7TDGUEZZaUkuzUKEOxlLepWv+uSZqT3zswHu8wJiRdjycdKwX2S4lYmlLs7f3l1tf6664kjySN4MbBn",
	"1rj97Rt+eXXlGq+75U5ZW3Ot3aTbXGvX+EHXug5fuIC3CypyUmxzJbcx6HtXV4uMfTuBuhGe2Gx+3kZy",
	"tiPstV7zHFiHaPLliywwU0c7JYfq9BWF+H4U9Hq9UeAm+H4U1HY8Cu7vV1ldTEP/jrulrDK11AZ/2DtD",
	"B7weYG2Ba2xfsFcLdu52G+FNM3MQSR19QFMyU4qwLOh8ToAIFFy7FGwiE687ycRrRSZm9MbSCdEgFK8f",
	"TigkL/CcbKIEl7pZdffFLS6ysYL4ZpPU22WOhSACXeCZVJRAECZKIwKAVByiUkm/KKEFiSW6Lai64ZQJ",
	"SXACOsCsTJuqPFAASYRUPcFzw8nQjCek25plj37Dfk2zsZIJ7d9tHUemG0no1emlFatvSCEAIE2UOmGS",
	"FAynyLQARQgk3drhDnoDUCYbYi4IeL+VtCBJMPylEvqrs+0UVFdoaCv0mzUPZ7923KFTdTXrONPyIFLX",
	"cpzQooY/gd53Mg2aSHTBuTT4wY2ugdPU2pzUjpHZb13beGFHfFG/Kt5EGWWnhM3lwheqV4DXrbpr2zVF",
	"qrVhXsQLIqS+e4qUrZXHN+k2TaqUK4VFG7LsMtBHnhB08g7tLMidIS+7CiZUCqTUuFJopqrNderSmHc2",
	"psiUGo8yyYFtxmkpJOgYHnnf6yLGrwcDhaX7K77tB2FwsOLbQdAmyA34dwCx6yQafmWtK3eovbgoQ9j4",
	"VjmRo7JIdjl2fbqwHBBhxTk9VxuQFz4L3+drogREB3Z/5Iadeq3DWH1M43oyQTt6uzB0e00rzOe9Efuk",
	"PbHA3uIvlRdds1T6qS8YaX7q+wNWfjsPegyAM3Kea7X3hvapqVO1tocO0HlW/wznXZemy3/naS8XzvHo",
	"AcNcqD52iC4R5PLAUhCcpp9m4Je0peXioIJsQRLCJMWpAN+lBvUt42vSId5cHiD9SaP7rVLW0OXlFZrR",
	"lAh0S9MUcEFRjKRGULNlpGlqZMYGVmIJ65uDGp096DicvCAzetde0qdc00eUY7lAuhXwe7i1xK53h/Tm",
	"vdDS+371iNF/sVtbqPdlIzclLMk5ZWozZldtatNFfwzve4vja8KSOovTEm2TgpseaKq7IBgyDAgrM7UQ",
	"20kcqBVUm7G/t6C5gftuYxdsbAJsw0YYX9etg/k/wBjZnlQcbOyj70vz8PRqu47HSmVtt2ZSdFyKc4V4",
	"kqOr00ukWtCZEqYI3IkaavUVivYl76tWvZxkXSdzTZbrp7gmyzVDX5Nl98hdlKRBedyzU5OSddg/PKbh",
	"W3Z1f0trlSpyeFIp0TtH4AWpFU6x2/OeM+H10ntyoyRNgOe03786Hy/r6jg6gxmGL1+ucVqtvJpD24rn",
	"pXBt9vYGe+7LQfQ6WmB6XapPr/YG+/t6wnc8hmmsMTrhseg5J85ezLM+YfpRDk95KSM9Xl+DoM9vSHFD",
	"yW1TNVZitnWqezX47k34BEdSpdZkoHSWBQmGg943903+bODePuir2rGas+qhkxli3JlSkhB84QVQJ4Wm",
	"rTPrPrIu9Pc3vvnVRLdUUxqMg4dihYsFEblSJb1JvFcsA0yf7q6FaxsoszJNzQvHyTsrdVSQ0l8kV0K0",
	"4z2rp3hRfW2h4IuGFr92oS141o6+4xrLgqcCFZglPGNEKLXa3V7O0M6gN4j2eoPdHvqBzhekQDc4LYkS",
	"oa4J4qXMS4kypR/oIXr+u8ss5dgwevco4R4oqtdFfZywWJ6PO8TxK55H10goACitI8cFzogkRQ+BsCr0",
	"lXeCnuQ5+hHx3PMMhAeVcirIb6XCQECbbsxQS8g7ZMsyTkkpOhbhg+gwBVUd6J7SjCrYPw0unS9tCgu9",
	"17b6LbWSCdrhRj4KFSoKZ+Ck+gY7qX23t/HFrGlKgDv062a28pYkBY+vH8tUfrpEZoQVbAVI/7n+h0A4",
	"jhUaS264jMYLB50Q9N8QHWb4d85C40oXojOq1MZUvwdxuSCFWMlSPPK+8i5GN3vDQYiUXNPT7gHRQfTN",
	"YBpRJmRRxtI0wLCOHuM3OMoLDr+u4yy3ome6KNYy1YDpg3FW9ktBinlJHXuJRJnnvJAk6S1klnYoZk8l",
	"txvJaxNj7VE60tmgkVvDtkkWt+7Y/RQ877S9XRkE1N8dTtpNCMW8425G9myE9w+lqM9DE5+y5sdSmYap",
	"oMbbbaRbi5O79vpoi6XaRju4DLzPIFppxCKkA9Jq8WjQvCBzXCSpOks+U7wx5hlRHez0tXi3VdF1VXzc",
	"VuFxtSio9aF4tpOnN+qtBKEPoWoB+h9ekNWvHXjePAagp4+k9brzau2BZ5kizw9RHxoe0g/UHfSEURHl",
	"aSlq+oL9Uv2Jo8EBUJo15Fs/bwPpdua+frzA8gHyf21Nna/nTxX4zTFsK+3XQby9qD8rQByLl2OFO6ns",
	"0nv1B40gChzIdXouCvmfp3A0D7J9EMyzaJpD8RWLhl7QHK/LhCYUxj0E3rbPszGkv/SR/+r6yGM5dAdT",
	"qAzYnJEtTNnNETmfp6Rtd3/QIH8nhSR3TxzkE8j4TxzkSj8lP3Up4Fv+DINc8FKS4okDrVD+HjjKSsvk",
	"A8fplk7uf22/gFRc9XFvQOe2f/O6uIF/vf81bL07lgy08fqrnHEiWaP9fqjetqzzsBmAJNr5IS6F5Jnq",
	"leVSGIcK59fTQ1fOc6oUZMR+wCxJyRQXAoklk/hOBz5odRLYOi8FmpY0lRFlaEHSnBQmywaQFXC7UH3g",
	"qTnDjOZl6gce2AnR5VJIkpmkFC9fXsJ0L18OkbcGs1A15o4VqBbu8z8FSFRa893VwxzheEHZXI1TbQ0X",
	"pIqCxWm6RDGOFw5EFubTlKCrq1Mn7w3Ra+dRY0bnTJI7WR+9IDEBSmvNg7FupUEATi7gq157jNTAeGsB",
	"+YMGpAn1gVgcERfl9AeZpS9foghdkIzfEKSxpi/kEnzC59rhjdzJAscSxSnBTAflAxf64ers1AbXVGCD",
	"X758ceOjhcxS6w59f1+LxrETCzQZlYPBQawXAH+TCUxuP6gl2d/VymxMS5IIxMhtSpk6CXCYnKZKiyYp",
	"xK4ItJOHKKE3IVrsRYs3IUppiIiMe7tuCbIsmEB5Ck/yantwcCCjFDfgCYwTPKUplUvTx3MOAqiANxCZ",
	"IrNN64MlyizDNvjNRQ+R3wDmx7+VWA0JkTS4oMJcSfeqjVOxErx/ozO0Q35DQmJZCjQKcKyu8CjYvb8/",
	"hD+/fOnTmYF31f7flVYzCsBAh1Nofqn/1tqN36s6pc8CBNIJjHN/P9EgFs3l6pQ1LppU7Qp8JpdI3nIr",
	"UoGkYrauQHKgQJKRhGKAygfCfqQSJVxqooLgk3HCUfdA9c/KVNKMJzi1EF8JKN29LNLvaYbn5B2W+PPF",
	"iYNL9VkuqOhBm3FZpB0NRi40wEjHQB6gR++f+XwUdPYRB6qDsZv29Xuu6ZSzVZ1mNCXDft89v7UnMa6U",
	"CCnaZs1xYLi9VCyE6LsOBzFRhGI4QRF6iwV58woRFvOEGBr6+eJEWDOZbgmT9f+Zk/l/n0KHsNfrText",
	"mRgfmgnq678F/CNCP5Gpmt/kM6qyAtgroeQ4CKiJ9WXQo5mdqgHgCVc/+QPthqd3e88nAEfV7PIgggsj",
	"qSKoxv0K7cyMZ+OkE+BKfd91ADt0izPRFei84DERintVcHv58kRBQihy/I7fspRjUFMLIujvJEE7dIYY",
	"IQlJQHNnNwTOQPIKsG6k83fvhSbrd9LSUwKmBOM9rPZQEKazRGGB4BBcd0VpVfcLIESKNtfH0Xz3jP9O",
	"0xSbVtReMI0jJC4LRWysMmT3aXem2VhecHVAJlbVAEfYvoIAAxZoRxBSjyKtsgvt2mDFwzTltyRBCy4k",
	"ul1QSVIqpPl4XtAbxaZPzjUtAR6cF+QGSPbl5cV7hKXE8bWwiGcXqsO2wHIkPF66NxicvW21NSYnv+HB",
	"wA0J54sSmhEGLpCtQfcHr77N70LA5sicu0WjS0KGzgxTxQjBm2xNzvqbhV8UxWApG7FXwAbgGl5xzjQ7",
	"gH9q3KEMXX369NEIPWjnSmly0aeCEqbO5hPoQugj1zGXuyuJXzUFAvIGJF44ktP9GaXgL3OGi2tSfA/O",
	"tRDnwuT3rzZ1TQjAEDy1RyPZSa5+WmCJqIAd/g+DhbBbKhDWzDCWIVqUGWZRYTHegCIhgs6ZjRnGcGWR",
	"fvoAqRTAJzk6PT0TPRj6xJmYBHr58mAQvRn8H8YKURDjk6ONcopdwf39j8tPHxXGplV8lJpmQecLNTAM",
	"q9oXZGEwB8dxWeB42XO7/JEs0XsCWrFHi4/07qz0q+/tZDiB7VyTZQRMEuWYFk7CKQq8NGeCMjgUMUQT",
	"JQP98reDX4cI01BHH4VZahn2FZ6WKbZSM4yudAAOAXLgtWogJlzosKQZkDXV9vT0TKn+wkrbpSJMQmKW",
	"UDY3Pc4MZIQ+qbqQZIDwljAyo1L4RPWU35JCB1FwIYURP5MyBtirYymFupYZwUygFFqr9bgebqT3WChx",
	"z5rI9FCn+pnO2tNyTdhdnzMIH7dyNorQe2osOzaMWTg3L1iMpgluR9ovzOeu/m2ZoJ0p5+nuUMml6G/W",
	"b0xyBKkFUcxLNQF420/U6U08YiOLkjguqy/cBO1QJneH6AT+aVz2cxyD2y0vECMC+AgQhBrlciO5K1n5",
	"hQ7Re7BkC5Jj487ICyQNzsBS/bEYZwTeedHE3OqJ7SAqpmrt3NpaZgFkZUhJZUrUPqRzhFNg+Tt4VqNL",
	"wF8dzw/5IoboPzAj6B3XPLAb2eGTdfGyqfOITY+3b35QrFUM0SudGatGiWy2JcrQxeGH4cuXjg75QTve",
	"HbI4Yli1dlZWfW3gX3X/HT/0cAVGv9Rv49oxvuIgcyoX5RRESsk5i/Ss8LcN/ufoREHYxdp3dsZpfk3E",
	"NWX9Odeda2qxOSWrCqql15QULb15+3S7gPAdn8MoaTKB56MFEd79CSvHYJ9K3lh1aAkJIb58+RvYK103",
	"xSne2Xm/fNHieHJ/P1RtK20Sfve0SfW1r0bS//g7TmlSrf/knRiijqm88b98+VvJ4Hnt31Ms5P19iL58",
	"6euf1Fc3uMGcI0/fqYwSbfBonUuLsmOty9zfG6uE0o/rH5zeBZ7XBfqfJSmWqp1CrKXdqBrREC/1k7EX",
	"DCtoeh8jA0T1t7cLN5HZzlmlShmFCzAA5M+OQz9kOF3+TuAYdCOYvaFlWQ1qxN7zuBRI4eqXLzP19xgX",
	"BHvzXzZ4NwgWnQAFuJwXHFQGNakng5SCFGMjOoGksl+XYhRt1Qs6TwkWBGF/H7ketOcW9fLlEc8yzkDx",
	"PcKCCGdIUjdm54LIgpIbnEaH5TzTQtkH95ywq0R1HWkFaT0puSFJg7+gmOpLLIx9yr+Eqv8RGFuU4O/k",
	"cLCVWXDZa0vMAIAw6ChVIpGlLt46DH3Sc1uaCTRtSqTionGtpx6zwg010gmL0zIhBjX6EKPZV/ecKyJo",
	"TIC6o9KyzczSmMuOtILUJasVvlZjLFdEKKUMx5LGDvg/EpJ7sZg62QqKTCaSO219QFOScqWjUIZw7iKQ",
	"kEIVNYg60TgluAiRs5LeEPO0y3AGIWD2HqkO2l6IMqplTSPozgsck1mZpku0I30jJxoFpuk1WX7/Oyn4",
	"KFDKlP8Yf6V2V/UyCYD1m5jUpliAjbEiVb7jaoLVL7pKWwm3SgTS8ZS75mHl3DNat18TVzyre2+JxivA",
	"JDyBmDRJ7gKb+CQIq2WpPwp4IAjCwLghBWHN69R7jbbx2JlqtYUXQffDzpZeBLrzSi8CnZpnd+WjfzMZ",
	"jP/s733LC+7+fdAbqH93P/xj2pvDinoJuembHjinWgHVvgwdnllrX+jNFu0Lfddjr83suHaAo5SXCaqS",
	"QBonrFJEMWGywKnxPn12N92tX8k7UvOsfyf3jr3TCbc54Iv6b3nBvV/MwTZ9zToW1fHYzpWoP6bJFidg",
	"GqOTd1/Nl2x/49P9/r+cL9l2nrPeZbLWyK/nDNv9ULwlZdOd1z0EmhbOjqJziiutnDIbXqiTuNEbHOs8",
	"9nw2g5hAxQVWEUXtwto7GH4zmIbot1vC9nuvh9/sTxVzJrkg5Doq9vTXTLvSDr+ZhqrfDR4evJp200bN",
	"V0AdSum0wMXyz+Cj6pMTA9BOUuIDRRENDyzqnw4wSqIphgcH0yYd8Qf4E9/7VckOfri6OndGHeebSBkS",
	"JOYs0S9IBoBVLo5a/PXrVwO0812Vr0DJrgXI/apviou5jRZS+qtI+S1a4CK5xdqFZU26o39hguWB9A8g",
	"WJ3uJNsSLOi8jmB1SmBaIK4JXvqnSMEuRPwgRPxVpBMPdtEVJa8rcPRMdmBFYJ4gbpltrBO3nurMqO6p",
	"uhAPu67R/lfwaNxeNnOKywYaqsHXLY7pMV5Uf8Kxqn+bE24JX27WZ3ZwfMYj+PMIbH820lXdpD+GdHU7",
	"sT2AfOkB1spcVSsnd2HnyaW26jwhFJ2DJxuXy6rxBu9qCindWie72+Th/un8+OPFp89XxxdbebkDmUWX",
	"JNXP+8ZiA0kkALCTer5JfWnNbR3Z5Ek2yWqgfnM6f39NgZhgtz6NmJiXFr8wk921yZBrgCrBHmakAMp0",
	"iSZUMklTSFQhyjgmJBGr2El9zSHaZr0h0jp7v6nqhSOWEYkjYMF9nQ/2oFcP7Voh6zqLSQ8b5R/nVP1/",
	"VI8F6AvCkkj9FZnUvZSzCFiFeECgQH3bbeuSs948LVjAOygXMHCEGcKp4JALgkhA3Taa/nGRAn8i5vrg",
	"cIFaFgj/TlLI3zGjpHDMtH7kL3Z76JjKBSlMD17YW5SVQvq5w+sctoU5bfMPDNOROAeuNJ+1lig673mv",
	"fc3hccT0Nld9xNp3ffud1S/ML+3NbUMOgjBYQQ8UH3K17NoKXKNc3b+egPIcYRjPLsf8ITEQm6QPP49P",
	"a+3wscPL28vLpJTllpqibg+fzcZGmqCkniBtv5X5y7XT7px32n+d4hSZodYCoTujcHUylFE11tgtS9SW",
	"szdoZyY/0V3s9CghKV4q9MpomlJjOaip9t2JyOul3LxJD8KNZNnUcLS9/VMfbDIqqHlXbPdg0LFfO/um",
	"/TZn2gLDVsSLbCncmt7rJFvbhArI2p0uX3g+/2enNv5Z22o6LI3gNTVinz5+/BldKCKeEfSh0gVFr+bz",
	"Jb2YW+fg4ETjEdOkPqEi5jekWHpJ0UwylSrDV39SJQNcaWbgjN0VelX9DyRTglwES93RTvMlJK9/j2Oy",
	"q4eoeYlZN9hqt7BexhG5MwkblTyUkJywhLDYvP92wAIu5mxGY6oEoaPzz/0P558RuSNxaV94D0vJo2rn",
	"lsGa5Abr9w+zgtrlu+Mq8dJ4RaywhmyjzlkEeZg+F/7nmnQrGmuUmwznXsIIH4xfVL/7fgXMhi1iFQr9",
	"qxpz/fP+y5r7tQIluyMStyDrtTdFPQqqm18N9HcIk6TICypINC9wQnZtekqBDj1fDOt352ULRDuH70xh",
	"qHoRKXXa6MPRua/WiRHb0au5KFmIPvx4HIJnbSkJOmZzysiucVDyyhNC8mPDTxJyE6KiZCM2mccwkJrU",
	"9xeJrPdfyueUTXroQoNcoJPDM1TwlKCJ+l/Rx9SZhUtBiskf5gEAC7dOADHP+tqvIlJqiDuayBoFUoIL",
	"5huqPW2/etQPvDf6IFxjBuiubeOepoNsGc3jPDK/1c0Ezv9jo4kgrhBknGNbiawrhZ2VGXAMPrbahdvm",
	"tOuhSyIF+vDp04fT4/Hh+fnpydHh1cmnj+Oji+N3xx+vTg5PL7vtBk1B//DdkXa85SxqYuUWDhPWxl0H",
	"c31LtevmpYipbp6ik11OFSF6QUoFwOiWCAmaepfNxMDh6PTT53fj008aFI0Exv6wf66Mag923ajgtjrL",
	"wVNdL1a5XWyG//nFp/84Prra3mr1X07H/ivVwdM4eK0Whha5q4oYW7Bv8zhyeXWFdn7S5Ql26wrZNm8B",
	"Xjm5je8Aikt5ZR/U71WMonYLBU6W5QchusU3Ibol0yxEfD4P0SzFsRKe79D+a4joetBLLERri369IkjD",
	"tt2qBrG9abrxZIve11LW1OG0/ZWG/O6dipGaSH1V2tGK2d4eXh6PlfK0arqNWlObxvqFMuoLMgjUIqXb",
	"poVdUdjlsUk71t6NrbI41EbQrOIpIxhVxhviqVkgmhB7VAqIz6sTQLBaGZyeLgOZKv6lSG/lz7vMCfh1",
	"uRQQ7ltk0j3GLkC017z0dtHWyDHR93biilYii1g7DvfgaW+ihcUJxL94PPbSXXAIqd1xTF73Mr7BVVix",
	"VTGtnGgpYYh+wjf7fyfxfoh+KN8eX1ztrqnA01FaZ5uyOutK6kwmkzp5+kolZ9bjUqd1w8eLDn9u57Tt",
	"yfN6vpWu2Ouvyha8zB6jz8w6jrCOzqB/pp1oANVg6tWjnOWthcStt18LeUnZMuw63hDNcEymnF/3b/HN",
	"/g2J982xr+SJPx3+vV5XN0Rn5wchen96eBSis1eH/cPDozpTvCSVyaxWjPU5Eet+e2OeZ83pYFuHH6/e",
	"n/5jfHV8cXZy9Wycq7YAV0nK8ilQBxrPmf7hKU3pZIZIlstlPaPto3lbk5U81M7SIHBVoEFF6Z7BuNKy",
	"QKNLWRCcUTYP1cXAUKiQusik0HMqyUsWy9KlNtnCQFG/aSCw1VG0Kjqu5xh7cwRDWZQkDFLM5iWek3EM",
	"daACwqLPlxvMD1/NsNCFles34YlZej9dldS7odxdXKoBD1+Ms6CpT2ERxHaE0Ch3O6APWBJEdHy5Ik7j",
	"iUYN2733gEt9QWI+Zzqras176IXOUjxOOZurdUuSknzB2VL9IyMJjXE6TmisSeKKDT1Kt6/Ttadp9aUg",
	"Y8IWmMUk2Vzc7LMgyLZ2bzZVLJ/NRoB2IGAe1PndLuxZRcriRVkvu6rf6Y7Uz6Qz0d52lWJa48KIJqY+",
	"aIut3U+MmpXrJSE7ZOOJ0YR1appZlExUDfWrS7r0y7nYNDJMXQWTMyAcMdWClxJpMVtnQ6ge4hrCBDw7",
	"Au8wkYkzekeSSNDfyYiBgYL+brhpUq3GPu/FOrMY4jekWBBsC0GqkwZT9u2CWK+6i5JBPgrtSxfBmhOS",
	"p3xpEl5BnTzAC5CG/8FLlHD2QkK6GkSyKUkSyuZ9WISbGccFF0JX5LLdbjGTCCwZOFXSfZnbaEuT5kGv",
	"0L3o6uJ5XYsF1wK9VlPWS5hCP3Z+yMZBhE3yoBcAK/708ePPEY5jkoLp0IOetWd7q81JIaiAgFlo1nf7",
	"1WnZRJevG7QUwfD1oFntQhfEswVN1emkOHeWT9XeZVEIhoECiWqOizmRXqvB/f2qq7XmUm2vCLdGNSdS",
	"H3wbdXarq9+l1M7KNIXCpGMoiry6zFwX22tfdDWcFcgTcgdXY6ZPFEyab1Nyo0T0nxbOmUmiHXJDGKJG",
	"ktsNbft6BSl954bxTA6RKGczqtMQ6lrOiRv8hUAGL7QpzE6Gp2ouN3YpCBrGtZFwQXSmbKh1p3Zzo/Nc",
	"OFQU2oGsTny9qpmRuKZ5ZIssRPACrjAS4tjDBxkQViFcZUfQRRuJuwSbuI8zMt8uCHjLaTqiw++Fu4CQ",
	"SseVRwTQ6WRCfsJrDUNcpefWB5CRjBcmjkwBsgIctNXnaAYFfEJTLhduOJas6NHmgdsC/dnybbYZVrd5",
	"ErjHqgrU6+jRI4jPejtAa8UdxoBMB2pXKzSkc5UpYDuC9fwiRotsPcUnxYmgnQr1que3ByjA1QPVKpX9",
	"EcZdi1hrDrpm3bU+sS+g4wttM9ESDuBYQ6IJEaC5p3jDO47xgon1+TofmPou7dIeF6mxpfhoT3KF5Fg5",
	"p2Fk1BnIiwWeLFYbhMKdzsWsLsxpSUdSRRi1aGMKhXsgsb5B4LdlPdBsmVmdhWJH0IymGC7bgt/a8Lxb",
	"XlwLm2bgyE7sTFNKFAIoDtFlUwqt1jldGi9grdPuWO+7UEmisCYLbxAgD9lSF68x9RkVNzVujmp1kGlv",
	"3SH7XmOwbA0W6/C2N0Rnmt6DgKahuB9pfx90dXUKrfaH6LwS7c7JVOnJiudog1qEtBv7LKXzhUQJScrK",
	"JmLylMZlUajO2oFcKREm/KElE25hK2tIjU8m2w8TIyv21hDUjuEDeaDXpnO/NFpVJTO3LalKBdKTJOjk",
	"49W30W8lZhLuCE7T6IwyenoWnb6JbvZ9/J6WLElJ4tSvEbOlNCnDxbKHPno+juaehfalLXS++CixuR0t",
	"ijZfHluL2Dn49lWV5VGE4BIaKbmi2wPz/yQFb7Du//V//7/65iGlDhqWMOV3qvlHjhiR6qutEmVXpr6e",
	"lwVBH7jn0AkuAPzs9Oc6yrXVjlXaecfZm3zojzt8vxbWuoNX7TzDmb7yPuvihfOOEmuqn0CxEpgoImye",
	"UrGIbl65mlWSSswi/RkO6mb/69Wu6ha9Viyxfqur7DS2zFNQiohgIbtelKdYxguoeV53Ze9iw9BWpzmd",
	"+UqDo1aK6HKTsBHJRcHL+SIv5bNXzVoBhxcherHusFqlBVeC85krZvlOUfogmkupTqhjcvVXPmbkdgzZ",
	"xDcrQj8Z/Qf0nILmiJFbpDORO98VyvJSaid0k87JnecKi9z2riEdhECXIngcHTC1YFaQgK9aEqmBGwe9",
	"gdMSQ7Q32Af6LXZD0xBErJSyeYlTaP3Q4kgwTP3yw0GNLVJAjsmxfU3z3sbaK+0slvS00khdasNj6yH5",
	"+/LVgPYWG1GBpoajToYJz/98ZtBZYQx3GWM9q4anEbbHN79ARsMgDOoZ5+AHsAuqdf+6nSrTeRhbFTyq",
	"kHy1U2Dn6G1/vKJkMZYN6B5/fNdayg/8FoR5nVAOIClQytlckZAF1tJQhu9s5llIYOiD9OOnj8dBGFxe",
	"HV5cBSHM8evTwto7KEibdjzGINkxsH5HaQy/jUmyYyz9CPo8Y2nF6pnGAmeW5xtLB7E+z3jdMuIjB+vk",
	"M48cy6jczzNYpxbUZa+uaki0afI7Eqe4MGo+PL9oKmGERwHu38DTbW7OHZ0VM0TgBRAiyIsZovN378Vu",
	"OGLWLi2dGYAK9gICYdohcLqBEnWELJZoSSTwTTB2TmRRkklo9TRZECyFNywWfnEMzBKtrQvCEqNoVRUz",
	"mmuGoii2lIyz9dk3HT6zBQd0jZ872UNXXsMXQssIVCAh1ZzGs5ua7O2gHOXSlsK0gFOaFUB4luI5+mcJ",
	"mTHT1IYGjhjjshKwqAbFRy5N6QWdBEO/gOK0IDhZVp7lBoC2ukUFGIc3k3DEJsb52/0Y7Ud5QW4ouZ2E",
	"aBKnNI9e2r/iFOeTRpZH6yP2T8HZiH0ZMYRGTiQYBUM0Mi5SoyDUH2HB+ovgGYlmpdI/o2qBkWlh27sP",
	"qpNCgRG7t75jbZeAhzwPrOEAz19siq0SLu2UKwtNVdlSJTdVp5Tys+C3XmJdXJARq1Xi6Ja762WpUGdV",
	"qhHbVJbqf5+KUy6dNhZVZty/Ckx9pQJTf2iVKMic/Uylov6q5fRXLae/ajn9Vcvpr1pOf9Vy+quW01+1",
	"nP6q5fRXLae/ajn9YbWcXPGkWo2Xdh2dK318SkrVTXpwoFB/Ccv6lwRL+HCF514hpaojnrtiSqZwUlWK",
	"6csXTyczR1WrZ2PNSZy1F3muUUvNCT4kanGVnWFY0/88A8RY6YKq8XlBYzJE//blS67+6i54VFU6WrsA",
	"B56WBtKxLG8xjyoa5U2mFDF9he7v30IxKPsvp3pV2lqMJZnzYgmmJ5LRMgON7X/9f/8POtf/tgKy13nK",
	"k6W3ypcvj71Xpb+bVyUXs/nh+OzkoxcGHtkHKz966fAE2jZDxutttZncb2ijmK1qA+pP1dRXEw7PT4Tu",
	"enp6eHY4/uHT5RUEkmoHKVCpC+hvVKGWC8/e3quDV8b34yRT+pa6/ecFgWlKRYWPnVnM3K5/8BJsUxTa",
	"I3JHBfTy/Ex1gi+94NA8NGlvOLZ05q5dJY1TKKUE/FcuSFaFJFCGlrwsPAZmSqovCJp4tjrz8NpDEOgw",
	"XUIZcCB1I1aZ2Ly0D0KSXJuDCyqJMA7JoprZmH3BCdpGPkqS6+3v9dBRQRTNcW2MsqONcwuCcJ4XPC+o",
	"auSkcDBl/FT4gYlGp/Q3M0Rf0CjQZhgY+yPOjClmFAzRL71eT390XfTHXq/3K7qfbLbFwp3S5tazJbJ0",
	"0llXrdkBGjgqChbuXs+18hasWn7RLGkUZMuxBqb2e4cVD3p7IRr09tX/HIRILVQ1v7dW2ypywi8udkbn",
	"hbYNAiJhpn3ujO+4dXXT8OvAP50JuYGTlVf1dOm5V4FSDj0q/M99/O/AYr0a9y5Qn/gt+KzkTvX212Ar",
	"gRg7LGVzItrhqfaBHdxIKlv8QSQynKadZazuN79irvdsblujn7dulatV9VD36G2fTx9Wu+rwxNWpeqyX",
	"R5MHPMjLo/XQMhjseX4eB4Nv9rWfx2NKXlUga7tyguNFoCirah+pf4aBo1LBUM3cym1VW2Yd/wxK3D+l",
	"ulZ3aqAaeLd38vD2Ussc+s1+lz9EZSUxThEVMhhis/PNm29DtPf64A1cfTgZPyi929Xs+YqD2XRrST3z",
	"VYhsdIYWOeAYFER7W/q+rzja9S4j2/iKrBj4uep3oZ0VGw+ds2kdUt1hro+sW1XNXg+OR3SGGJfI5P8w",
	"ePGMVRe29dZ4WKGrFaRP26w9vrWuohVADIhkWaS1XEm+UErYjbq3Kwki4xmNPfdJuHfW1S27m2KDUZFO",
	"crnje8LhNIVCJmnmHJxXEU6vHpZWuP9H/L3bZzcXbq6swX8tA1zhIw8Cdps8PkNxrOa6IMi7Caim12fH",
	"ZlZfDUsqVmwqfHgRpe7CBRWePCb8xy7mK1+2LnemhxVpeqScsWXKsUvrkNOtJjZv6MqL2C10+j6orw/e",
	"2JvXamxu5yb5ZVPSss0SjLiOer2e5436EGH5KbWpVtbeOHyKsNKROvKTTkBYSSgWnSo82gEWdGbsA1VL",
	"9wIA4oOTVYZo//WbEL3e29eexA2xZuu8kytB/eAqVfWrvXLc7UgUCMY59XBqI4nqKJZUS/6pG7wQIFjB",
	"ybcPfWPWuTrt6lzl16ddne6TD6/StIKGPbBCU0OMNDECCZ2BcblK8SOevzrTyupFG+jebriyIdC8cMTq",
	"BUxq8q+u6NlX/3Pgffl2+qBKRg2n/U30kRcNErl2pyvrF/35qhU9lWrSGXKxTxAAan1Gd7cmgZtAuRYw",
	"m8oLdY8KFfxWo1hT0tu0wmemMd2eyw+slLGCujy8SoanumircRV9qWiK/3jeaSNeEb2Mdkw2hv/m5VbZ",
	"7a0pXgH5WnRUeNdEOujX5njwYn6bjos67tfP6NII+9Wdnx78200jp3MCu4gIi272eq9r2tnKKFMt/Z0Z",
	"l+SCIO1r1K4rQqzPqw2T9quLPCQced+jds01r0gI+ayVOb5uloP9JyQC7DDe6FSAjdocraNYWZqjA77P",
	"TFM6Q1seX6WhJXV8nSINz1YeYbNxOEQdjvw2AKMPsQx9CL/YfY66CdUJ9edERnXO0sob0LIpry6tsNHY",
	"/KBiCl+vdMJTCyD8EaZpXeOsDcj/jvb2v432Xg2+bbgau1ZbWbL/hao2PJNJfCV9+WrG8T+swsKD6HdG",
	"kyQlt7ggVWTcp4vLimo32Gya8tuxdzU3x5ifsEQRWeJl2/IJcsz5NdUxXHKBFgQrLrarA0S0z24PfeSS",
	"DNHJzGTKMr+PeUHnlEHEDeNQ3fKXFy9f/NqdZdR2MjPU1v1LYDxLoivVLwwOwU3FpIwNwuDn6EKLWiSJ",
	"fqJyoZpAMFgQBp9gFUErjugHPZEOwTNBQZBOjTKkQOykt3odzrUreVBRTbvjjMgFT5o7/nB8FYTB+adL",
	"+M9n9b/vjk+Pr47Vls7V1bxUHw6vjn7o2NvV1Tky49rjAGKxZmOrJ3zUrszht+/ZKRWQ4MQuy2JJa3k9",
	"KLsMKANOkaq9+l/bo06adDubmU9H/UCq2wRc9IqyTjJ+6YrPCELPlpT3/C8PgoGZeGMu3laeO9g/FXbl",
	"nReF3OVcNC9KF2KbhtbxJk4pUbL0Z0FmZaogBY5AimkUJn5Ih73ZS26DUyG/lkL6BCIYANoFwUkDnj9H",
	"V1ziNDpSPP5h8IKamPN6gPvBm3ZNyh/4LYSzo52qvtuuLfIDiKDwChxptZ5mUMnF/EEMm79sPUtHJZWN",
	"9SwLUuCuPJYX8PtT0yO50R+WHgkSrEba3b7oZyLKcBFzp0ZGjZRJI9bMmYS+UsqkrRa28yZK8ZIUSP9c",
	"7/RfM5NSG0u0v9PjsMSklliBHF81f4qeszuBym5oPz85bYoep/vFuGMJf/LMKFUKt3FOinHC421KmZkc",
	"oznxXMi1DY7Nq1/Aqbee42e9bbUbfFvlMqkQbrUI3j18m/TzfMy6imXZ3WdcKLqdkhvMpOfUCUxHsSko",
	"pFBzCgkdA8NeLLHxAxUxL4jodVcq3l4Ob19k/RD/uItsHvE7LnLwjC4NajY3xaPddbocDp73ba0N2zZU",
	"qxQxjaTQiry196BDVgBAkrvwb/0e5vBjM3wekudg9S78RMg2zUCH2NYK4ica6VniUwIdvL5h5SvTKbRP",
	"4CE5d7aUebZJrLLlfXrcUMaI/CxjdfLrxw2lbRrNoR6c37mbangM09wJ63bu2QITwuYx5v3/CS+mdiXR",
	"oPfm7fD93ptOH6z7LRJYg2Fh421e7yrd3laHq7TLl+8cxCqPZ+cLbSyWq1yft8WXB76yPSMxb/JbY9Sr",
	"ycPea8PjXTEfVwf9icS98xo8zM+8sg5eGEAdnp889JWBF0pFTmlMZc3klWO5MHLweUFgp4JKp3KYAjrv",
	"XFV7XRBarWCIbLVnoytZTb6q/k+gsXkcwDmFhCwTNe6HQgk89nVjaJ83mj1xklEGoZ5xWiZEoEmzhYG3",
	"BqCAf06UNJlRIXQAuFPNQCoXJFP6YxwZamBExn/XCU59Kb/ZcoaFjAaDV1s+g9QePyKc55FSe5VCCA8h",
	"Zt0maurw7Cljae0uirWBpVufWL/vP8ETiX4e6SwC9KAS01va6TfCo4Nmb1QLNg7656uUtEJFaStqBYl5",
	"kfynqiZryhIclgnltdoEHcVmdcFjV15Tcp2qzSVyb7Mwm1k8MaR5nHUNrBsh2wgqbtA0pcZoh6ZE3hLC",
	"/Nn8IPLBilezW8oSfrt+7p+gzeqpofYLpKzXozV2XEv+MRh0r+T+YUex/hTOSRE5Q2WL67mTQIepyYuk",
	"vT5cvEaEficF7/OMSkkSW21bKYAmTb6NphDt04S9b9JuHoRk9/XM9VubO/zK7b7pY0XNbZPn/pHLviJ3",
	"srlquSiIWPAubRJYaQIWQdeqygvYLLhVVffuquDdrtT9EExqLXyrO60TSW680quq7X/sqLJv+riLHHMm",
	"SFzCI74+0R7kbBMuKYpNpGHLgOmaPlNesgRDNgRdmh2e4KbLVlUJUohuVPDKGjQXfulSVmjqbqqxplTq",
	"BHnmrXw0YqMRe2GyxBR4XuB8IXYftCCPfdRrKrQkcPjs4b+BaW7LHD2c3qR8Pq+rrN0i9alu10FkGoXm",
	"RAtFUnKjxYXtLlxzRafQHTKgL7UQ9rhxLqH7A8FxatdeiTqUzXhLoLHguSHFlAsql0jvutI+EzIt50Fo",
	"u9/iArxzioKDaaWSekyDtmyzYWeNeIAiowynKxeqk6fYlCMA2h56Ybu9MH6JKS/02xBngqckRC/+KbjB",
	"di8XkpI4Q/Qi5fNZJvVXXXyHzGY0pkpquibL772UQxAsxXNbryc1xNoCy1u+mjAIAz12EAaqWx1gXuM1",
	"QBMHFY7XXRwaXA2k//E1WXZKkYc/Xdrnn2uyBPnRhflckyVU8rJJl2BvJC6IRCnn12Xeqjb80+X48Ojo",
	"+PJy/OPxP8Yn7zoFTRfISGRdPtYhw1pbuSbLiCbdFV+1bt5B4moJ7lp1o8SBKV2Bb0HTfKG03heV++N3",
	"g8FAH+AZZSefduuye6NzAC+lp5DCCCpLtAscAKTGFfy7gW8AWp3BUw/g8vjo4vjKO4dHHIKexDuLzgoO",
	"BHRoTd1XMV+cIr1LaGtSQ8GFIlnOC0iRXKHvg/betWyYJdIrWlH4VYh028LAl5en/avTS5j78kBRDaaT",
	"MIpG9ilocfjTZWiK7lVu4g6VtqkG693uuMB5g49JwqTNRrjW54kkY4XQXfqATSboO52otlAFq39yrlWC",
	"lLJr944t/GrdSnODsX2nJ7RD7mKSSx2/C7kJhcIvyE84Nj+OaS6s98luw12i7nYSJ6xX/2Xvu/3eoLff",
	"23uc+w2kw9wSGKqtyT5GrH4EiTbBiwZSZEKyziZQYI66J9h7r7PSQPBU8LRUIj20NWSp/1mQQvQTLHF/",
	"V3fSs6guJgmnyYZmemTLyPxe5nBA/SY8/TEVoWp1eBgcW+e48f68hZy9fgWdCjVQgdmcCLSzt/9Nb6D+",
	"r/9tiPYG3t/f7Pf23sC/II7wO/XPb/W/34Ro7813vf3Xr8y/dzsdgyzyjk0ey7HReBtusS07jm4N505Z",
	"Qm9oUmLPpUNdNawJQOV1U/Oh8T1o9jpfo/Hd2K1OSdDj6VI26t/sDV59+/qbDqcfqzGC5M1nbmFapIGg",
	"DcqQHtBblTfeGvce721D//rmlV2wzu7b7Vy8P3j17ap1Qj90SxO56C8IuCFRhnJ6B77x2onc1Yu1aUL9",
	"levB10O0FKQY4znpEgnURYgO5+AkAJ5ccLTgEujRt5pbr37Ge/e2v9cbvPDZJLrkGTEZr9z1/Yle05wk",
	"FO+igoAJzmG9rWeNUbWKOtPyp+p8WngIh1CbqiTBVXoPbL3iuM3wApI4uanDQqKU++7IFZdFzCZuXFDh",
	"T4PzPIXqNry3RYSJ587XXdW4g2h1bNP57nGTA4yskS/MeY6Cf/uixYwhSBH3o8C3elUnYXPTbq/AbcnT",
	"H3ruFyTjkpixtn9BKqCbIxszIk38mf5w/u59aNqcKfS2/4A8zK4+wG4Psu0JntIE3KaVlOQ9HwHPbCVB",
	"NlYKU6tUya5l7moXm6KVFepcEGCbat2fioQUNkfasX2vmngzfj8KlCgzCiZgvciIhKIabsWQI+09JFPz",
	"sFOXRp9oJikmaJ7yqeLSkhQMZVjGCyIUdkNQoGoDydcnhgSOxcHEGw2SFJ+SOY6XShpM1f6GaGL3V28s",
	"0I76fouLBFndBTLB7kKwS/36VfN1FVHRT3u1AzAVRBeEIcbN0pv7qlOkvKAZLjrF/YWU+bob+chL0Em2",
	"Wvf5I85sVdhaUcT11KtWcEx7bkY4p3VSFtQ88Ww76wJdUaK6d/sweEtwQQrUIBfBfef91Uf2zKC7PNgW",
	"cI1rueb+95renRof2oaEik4qjfiaLO8DXzfvUpg7NOL6KPrPe2DqTBalkNpxfOXURp6105sLrERgJRRE",
	"5nP0Ul2lcprSOHoJtpbHL9POaJdaZwQrhTsrga3Ajj8LL+nAqEdUBV9hmmpXhXLn1Xrb9AiwRldDvHS1",
	"5qZ0oZO6ClOiHoMgYsk2tuOErW5U6Pz0gqSQur+hRbVQCPLRagzaXnn6I8+25TxV5wbw0OqeyursoMGr",
	"+Q0pCprUXmQrDDJ+RmO1Zvt32+DeFY3lhO6NKqQr97kgKMFiMeWKR4oFL1P4z23T3T7mWYZZInoj5svz",
	"zjwDWdhxyhnpi1tc6PrZPXRJoOKVzdaPMszwnCQjlpA85UtTdEYLhz+WU1IwogQdrQnyYtcID1kVgm5G",
	"cMEC6bI3Yt1xXqsCwTvcklw8X989rpkXimcpXa+kEMISpeVzi65eBBZn7E4piCkOwmDO21FWb3V/ZPsj",
	"XlhtS5+TOiNXtd0hYULA1cP6CEA6lve2IIlZ0wQ89s0/hrrHxIDd9E+8A5+oOz2pZXWQBQX3I/1fyszi",
	"IEG/yeRrMuziG0xTsP2Z+f6bnmHEYp5NKdPyMwQDufJ0LreHkV0NKMTLl2gnIbmCCmcQ1ZJAPvbdISRU",
	"nvMJ6oqz2MHpLV6KaikhOjr/jDhLlyESKb8lQkJBqYk6FMjF/PHjz+iiZJJmRMnvJjg8UpN9P4KzCz9d",
	"XI2CEM2wkK7/XYonkB797PRn9PPpYUffuxSHP58eqq5X55/7R5/fHfaPzj/bYG+AjXj5Uu8IAI8idKiI",
	"qi5Yg6akBlXnQAUd4jKBFXz8+8m7k0OkRkcfzj/rb7wgWQrD5XlK0BEvyNkp2slw/OnSQMM+RyoA6BFl",
	"XuotgW/M1flnSGAFjX4+PTSz6jbveRETB9parIfb0S8aemr7AAv9x5yPgl/VEFfF0uKJV72nQkpXsqca",
	"aqj27MYbyrzU/9Df7L/cDOcQDqKAAqbl1Fn6jwyY3LAArkZvDStYmAGfEmpSlxmkzu/c8vRFV2sLQrcw",
	"86P+S1OA7ZmgkTLHX48ZhsE1IfkYp/Sm8XT4OgtWxs5JjlQ3S72NKU1xAZ0uRVcgS7GQOi+i9sv2XpmU",
	"AuxlH6mXiSutbU4PA+KHc8WB8r5QIYxKxSA+C6ADiaejAxUcBa+zUYB2qmJy6oj3Fuq3PbTgZQE/DNS/",
	"CZ6r5WpKu9tghHagFP++dG10RQ29LccL9WgQK6BV7HRpfTdrM4yYJsIKL7NWChZ4hsWFLHUqdEZuSOFA",
	"0qsjnz6ktocynz/+fbzCDPDBcTlpxi7k10eTlaZWzznHS2vjqLWz9lmz/4gdOi3PtwVqG+dvJSlJgsoc",
	"8qHguzH8AKpCb8QM/Aem7IwuP5JURLMBtVer7MsaxmN9JtttU3KJ08Y9MM4pOPXqo6oJlTxkc7jYcDf1",
	"54gZryWufreOIaY8nxHOFbOEfSnpuyAQhBrqX6FWfEFiwmS6jBTZHjGapLbYqknTvqzWQgVSlNbUDsvw",
	"NUEF55nD423heLAKjpoKjLPpdjA0RGOHMnT2dtePPDIAddmhDCioqGABKf0NOAAUyIJCsznvgnmXaONO",
	"dc0CCpGyOLmhQq1QTxohHMtSnTqse8R0+SAtsggls5g6vPR3otWDDC/duy1VROEuJgr4agpwhlBbg3BT",
	"JWfPBU2gxHYdH82jGoOEOJSZp4uCp03sHnz3ZtXBVLfmoZfYf5OCUbR5bAWJ8JC0OjVzi9W3WZmmIWLk",
	"thrX1vN8PThAl8aT+TOrJCDgxhdEFsvoENiCNjGtPks9mXei4IlFZjNT1nHt+nXtBjRowHZvMFgZKTkW",
	"ssCSzK3etsJmZV1bgCMEYaDYShAG4MNGks6Ak7arZ101MBP72ic6w7nwwjuEieCnRatXxYkZlzp2mwqU",
	"4RxuoV+XyM2jnRU5Q5XsAHLfycz7RYOwivA1jHR3iHxOinb0AyFDCVFqaGhuqeH9io7ttob+HjjtsM5V",
	"zUgV+wxrvHPXVae2EY4LLKotjfSBjAIfAnpTQGbazHkHC5TjAl7B84KYOWz7OtsOEdTWBpTrgFBOGfPl",
	"J1grECDgjgJl9A7KVcB+FUUBEBq6YMLtBc4IynmLHnwJ3h4envSnc6ITDLqkYEOHgxkt5KIfLzi7XkaZ",
	"uvLStK0FY+8FQ42uXdYxvZhxQosVr1wuWRnQLVPhzlYsn9qv4MRp9U+wMtnQFOFnJNVqxpdq0nsvPZoS",
	"4Y9bGcUqZafWzbJb6HVkTQQbOjneDb0u6qFW67rFfM7o71VH+DfIrRu7Qk0c0/GS/LZ/SX5D9tdm77oE",
	"+3/1e8ba1LftbFT6Dc1JsVvFHBAZglpXJZMAl9XKMZl6CnZTGG3N0+mJx3na5kB74Up/4U7xMac50cWO",
	"c7v7HjrG8cJ9gRsrRgyjmOdLaxWCliESHGorksL3dIeifEYWmZbSJItRv0K9bruIKrWMTlnkNmST6FK9",
	"KkOkrZBAmRYQtGjCZ20G3+Q1XZzGEJrVGXEaJN+0r9GtTmXsakEE6dBGaAbWW0nSpSZfzs1XDSdChG84",
	"hXsGhiAXhJBiSVjsmItZkTFDgo0ZyQU3pkOH594lrh6Wu8nXKFDL7uLpFYEFQsxZ9DspeF2Bgzmb8uwv",
	"qyilraHThzL7N1Tq7Iq52sbB/sNUegMg62BT17nb2RScnkF1GPotptLF8GpQSw5PoCmRJKyKdlkpTbVX",
	"ndeqygcDoU0ge5n+L6jFjNtytiHyVIALKyRpMVZX/qLCtvUkuVfoA5bkFi+RcRBqUoyDQSeNEAfN9GNP",
	"e0BphEJZ83E7GEq1BL/rDY4AemrtvaiT7SRKtaJTKEtVlVXVnhKKYZu8gLqyBTJRlmrvVHouLY0Sx1BZ",
	"G+toZO0/FAx6g96egpHZqAJib9A7CMLAuOuxMk3v//8AAAD//9Foiq64LgEA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/ai/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/audio/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/embeddings/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef4.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/middleware/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef5.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/reranking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef6.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../pkg/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef7.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../pkg/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef8.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../termite/pkg/termite/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
